// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: proto/orchestrator/v1/orchestrator.proto

package orchestratorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrchestratorQuery_GetScheduleGraph_FullMethodName       = "/orchestrator.v1.OrchestratorQuery/GetScheduleGraph"
	OrchestratorQuery_ListRuns_FullMethodName               = "/orchestrator.v1.OrchestratorQuery/ListRuns"
	OrchestratorQuery_GetRunGraph_FullMethodName            = "/orchestrator.v1.OrchestratorQuery/GetRunGraph"
	OrchestratorQuery_ListActiveRunDrifts_FullMethodName    = "/orchestrator.v1.OrchestratorQuery/ListActiveRunDrifts"
	OrchestratorQuery_ListScheduleTopologies_FullMethodName = "/orchestrator.v1.OrchestratorQuery/ListScheduleTopologies"
	OrchestratorQuery_GetNodeAncestry_FullMethodName        = "/orchestrator.v1.OrchestratorQuery/GetNodeAncestry"
)

// OrchestratorQueryClient is the client API for OrchestratorQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrchestratorQueryClient interface {
	GetScheduleGraph(ctx context.Context, in *GetScheduleGraphRequest, opts ...grpc.CallOption) (*GetScheduleGraphResponse, error)
	ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error)
	GetRunGraph(ctx context.Context, in *GetRunGraphRequest, opts ...grpc.CallOption) (*GetRunGraphResponse, error)
	ListActiveRunDrifts(ctx context.Context, in *ListActiveRunDriftsRequest, opts ...grpc.CallOption) (*ListActiveRunDriftsResponse, error)
	ListScheduleTopologies(ctx context.Context, in *ListScheduleTopologiesRequest, opts ...grpc.CallOption) (*ListScheduleTopologiesResponse, error)
	GetNodeAncestry(ctx context.Context, in *GetNodeAncestryRequest, opts ...grpc.CallOption) (*GetNodeAncestryResponse, error)
}

type orchestratorQueryClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorQueryClient(cc grpc.ClientConnInterface) OrchestratorQueryClient {
	return &orchestratorQueryClient{cc}
}

func (c *orchestratorQueryClient) GetScheduleGraph(ctx context.Context, in *GetScheduleGraphRequest, opts ...grpc.CallOption) (*GetScheduleGraphResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScheduleGraphResponse)
	err := c.cc.Invoke(ctx, OrchestratorQuery_GetScheduleGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorQueryClient) ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRunsResponse)
	err := c.cc.Invoke(ctx, OrchestratorQuery_ListRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorQueryClient) GetRunGraph(ctx context.Context, in *GetRunGraphRequest, opts ...grpc.CallOption) (*GetRunGraphResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRunGraphResponse)
	err := c.cc.Invoke(ctx, OrchestratorQuery_GetRunGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorQueryClient) ListActiveRunDrifts(ctx context.Context, in *ListActiveRunDriftsRequest, opts ...grpc.CallOption) (*ListActiveRunDriftsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActiveRunDriftsResponse)
	err := c.cc.Invoke(ctx, OrchestratorQuery_ListActiveRunDrifts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorQueryClient) ListScheduleTopologies(ctx context.Context, in *ListScheduleTopologiesRequest, opts ...grpc.CallOption) (*ListScheduleTopologiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListScheduleTopologiesResponse)
	err := c.cc.Invoke(ctx, OrchestratorQuery_ListScheduleTopologies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorQueryClient) GetNodeAncestry(ctx context.Context, in *GetNodeAncestryRequest, opts ...grpc.CallOption) (*GetNodeAncestryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeAncestryResponse)
	err := c.cc.Invoke(ctx, OrchestratorQuery_GetNodeAncestry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorQueryServer is the server API for OrchestratorQuery service.
// All implementations must embed UnimplementedOrchestratorQueryServer
// for forward compatibility.
type OrchestratorQueryServer interface {
	GetScheduleGraph(context.Context, *GetScheduleGraphRequest) (*GetScheduleGraphResponse, error)
	ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error)
	GetRunGraph(context.Context, *GetRunGraphRequest) (*GetRunGraphResponse, error)
	ListActiveRunDrifts(context.Context, *ListActiveRunDriftsRequest) (*ListActiveRunDriftsResponse, error)
	ListScheduleTopologies(context.Context, *ListScheduleTopologiesRequest) (*ListScheduleTopologiesResponse, error)
	GetNodeAncestry(context.Context, *GetNodeAncestryRequest) (*GetNodeAncestryResponse, error)
	mustEmbedUnimplementedOrchestratorQueryServer()
}

// UnimplementedOrchestratorQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestratorQueryServer struct{}

func (UnimplementedOrchestratorQueryServer) GetScheduleGraph(context.Context, *GetScheduleGraphRequest) (*GetScheduleGraphResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetScheduleGraph not implemented")
}
func (UnimplementedOrchestratorQueryServer) ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRuns not implemented")
}
func (UnimplementedOrchestratorQueryServer) GetRunGraph(context.Context, *GetRunGraphRequest) (*GetRunGraphResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRunGraph not implemented")
}
func (UnimplementedOrchestratorQueryServer) ListActiveRunDrifts(context.Context, *ListActiveRunDriftsRequest) (*ListActiveRunDriftsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActiveRunDrifts not implemented")
}
func (UnimplementedOrchestratorQueryServer) ListScheduleTopologies(context.Context, *ListScheduleTopologiesRequest) (*ListScheduleTopologiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListScheduleTopologies not implemented")
}
func (UnimplementedOrchestratorQueryServer) GetNodeAncestry(context.Context, *GetNodeAncestryRequest) (*GetNodeAncestryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeAncestry not implemented")
}
func (UnimplementedOrchestratorQueryServer) mustEmbedUnimplementedOrchestratorQueryServer() {}
func (UnimplementedOrchestratorQueryServer) testEmbeddedByValue()                           {}

// UnsafeOrchestratorQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorQueryServer will
// result in compilation errors.
type UnsafeOrchestratorQueryServer interface {
	mustEmbedUnimplementedOrchestratorQueryServer()
}

func RegisterOrchestratorQueryServer(s grpc.ServiceRegistrar, srv OrchestratorQueryServer) {
	// If the following call panics, it indicates UnimplementedOrchestratorQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrchestratorQuery_ServiceDesc, srv)
}

func _OrchestratorQuery_GetScheduleGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScheduleGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorQueryServer).GetScheduleGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorQuery_GetScheduleGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorQueryServer).GetScheduleGraph(ctx, req.(*GetScheduleGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorQuery_ListRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorQueryServer).ListRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorQuery_ListRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorQueryServer).ListRuns(ctx, req.(*ListRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorQuery_GetRunGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorQueryServer).GetRunGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorQuery_GetRunGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorQueryServer).GetRunGraph(ctx, req.(*GetRunGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorQuery_ListActiveRunDrifts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActiveRunDriftsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorQueryServer).ListActiveRunDrifts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorQuery_ListActiveRunDrifts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorQueryServer).ListActiveRunDrifts(ctx, req.(*ListActiveRunDriftsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorQuery_ListScheduleTopologies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScheduleTopologiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorQueryServer).ListScheduleTopologies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorQuery_ListScheduleTopologies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorQueryServer).ListScheduleTopologies(ctx, req.(*ListScheduleTopologiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorQuery_GetNodeAncestry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeAncestryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorQueryServer).GetNodeAncestry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorQuery_GetNodeAncestry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorQueryServer).GetNodeAncestry(ctx, req.(*GetNodeAncestryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrchestratorQuery_ServiceDesc is the grpc.ServiceDesc for OrchestratorQuery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestratorQuery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orchestrator.v1.OrchestratorQuery",
	HandlerType: (*OrchestratorQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetScheduleGraph",
			Handler:    _OrchestratorQuery_GetScheduleGraph_Handler,
		},
		{
			MethodName: "ListRuns",
			Handler:    _OrchestratorQuery_ListRuns_Handler,
		},
		{
			MethodName: "GetRunGraph",
			Handler:    _OrchestratorQuery_GetRunGraph_Handler,
		},
		{
			MethodName: "ListActiveRunDrifts",
			Handler:    _OrchestratorQuery_ListActiveRunDrifts_Handler,
		},
		{
			MethodName: "ListScheduleTopologies",
			Handler:    _OrchestratorQuery_ListScheduleTopologies_Handler,
		},
		{
			MethodName: "GetNodeAncestry",
			Handler:    _OrchestratorQuery_GetNodeAncestry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/orchestrator/v1/orchestrator.proto",
}
