// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/remediation/v1/remediation.proto

package remediationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Proposal is a read-only projection of a remediation proposal row, including
// all PR-lifecycle columns. Fields mirror proposal.View (snake_case).
type Proposal struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source              string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	ReleaseId           string                 `protobuf:"bytes,3,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	NodeId              string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ErrorSignature      string                 `protobuf:"bytes,5,opt,name=error_signature,json=errorSignature,proto3" json:"error_signature,omitempty"`
	Attempt             int32                  `protobuf:"varint,6,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Status              string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Confidence          string                 `protobuf:"bytes,8,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Rationale           string                 `protobuf:"bytes,9,opt,name=rationale,proto3" json:"rationale,omitempty"`
	ProposedSqlUri      string                 `protobuf:"bytes,10,opt,name=proposed_sql_uri,json=proposedSqlUri,proto3" json:"proposed_sql_uri,omitempty"`
	DiffUri             string                 `protobuf:"bytes,11,opt,name=diff_uri,json=diffUri,proto3" json:"diff_uri,omitempty"`
	CandidateFixSqlUri  string                 `protobuf:"bytes,12,opt,name=candidate_fix_sql_uri,json=candidateFixSqlUri,proto3" json:"candidate_fix_sql_uri,omitempty"`
	CandidateFixDiffUri string                 `protobuf:"bytes,13,opt,name=candidate_fix_diff_uri,json=candidateFixDiffUri,proto3" json:"candidate_fix_diff_uri,omitempty"`
	SourceResolved      bool                   `protobuf:"varint,14,opt,name=source_resolved,json=sourceResolved,proto3" json:"source_resolved,omitempty"`
	Repo                string                 `protobuf:"bytes,15,opt,name=repo,proto3" json:"repo,omitempty"`
	CommitSha           string                 `protobuf:"bytes,16,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	FilePath            string                 `protobuf:"bytes,17,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Model               string                 `protobuf:"bytes,18,opt,name=model,proto3" json:"model,omitempty"`
	// created_at is an RFC3339-formatted timestamp string.
	CreatedAt string `protobuf:"bytes,19,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	PrUrl     string `protobuf:"bytes,20,opt,name=pr_url,json=prUrl,proto3" json:"pr_url,omitempty"`
	PrNumber  int32  `protobuf:"varint,21,opt,name=pr_number,json=prNumber,proto3" json:"pr_number,omitempty"`
	PrState   string `protobuf:"bytes,22,opt,name=pr_state,json=prState,proto3" json:"pr_state,omitempty"`
	// pr_opened_at is an RFC3339-formatted timestamp string, empty when not yet set.
	PrOpenedAt    string `protobuf:"bytes,23,opt,name=pr_opened_at,json=prOpenedAt,proto3" json:"pr_opened_at,omitempty"`
	PrOpenedBy    string `protobuf:"bytes,24,opt,name=pr_opened_by,json=prOpenedBy,proto3" json:"pr_opened_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proposal) Reset() {
	*x = Proposal{}
	mi := &file_proto_remediation_v1_remediation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proposal) ProtoMessage() {}

func (x *Proposal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remediation_v1_remediation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proposal.ProtoReflect.Descriptor instead.
func (*Proposal) Descriptor() ([]byte, []int) {
	return file_proto_remediation_v1_remediation_proto_rawDescGZIP(), []int{0}
}

func (x *Proposal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Proposal) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Proposal) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

func (x *Proposal) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Proposal) GetErrorSignature() string {
	if x != nil {
		return x.ErrorSignature
	}
	return ""
}

func (x *Proposal) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Proposal) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Proposal) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

func (x *Proposal) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

func (x *Proposal) GetProposedSqlUri() string {
	if x != nil {
		return x.ProposedSqlUri
	}
	return ""
}

func (x *Proposal) GetDiffUri() string {
	if x != nil {
		return x.DiffUri
	}
	return ""
}

func (x *Proposal) GetCandidateFixSqlUri() string {
	if x != nil {
		return x.CandidateFixSqlUri
	}
	return ""
}

func (x *Proposal) GetCandidateFixDiffUri() string {
	if x != nil {
		return x.CandidateFixDiffUri
	}
	return ""
}

func (x *Proposal) GetSourceResolved() bool {
	if x != nil {
		return x.SourceResolved
	}
	return false
}

func (x *Proposal) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *Proposal) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *Proposal) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Proposal) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Proposal) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Proposal) GetPrUrl() string {
	if x != nil {
		return x.PrUrl
	}
	return ""
}

func (x *Proposal) GetPrNumber() int32 {
	if x != nil {
		return x.PrNumber
	}
	return 0
}

func (x *Proposal) GetPrState() string {
	if x != nil {
		return x.PrState
	}
	return ""
}

func (x *Proposal) GetPrOpenedAt() string {
	if x != nil {
		return x.PrOpenedAt
	}
	return ""
}

func (x *Proposal) GetPrOpenedBy() string {
	if x != nil {
		return x.PrOpenedBy
	}
	return ""
}

// ListProposalsRequest filters the proposal list. Empty fields are ignored.
type ListProposalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PrState       string                 `protobuf:"bytes,2,opt,name=pr_state,json=prState,proto3" json:"pr_state,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProposalsRequest) Reset() {
	*x = ListProposalsRequest{}
	mi := &file_proto_remediation_v1_remediation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProposalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProposalsRequest) ProtoMessage() {}

func (x *ListProposalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remediation_v1_remediation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProposalsRequest.ProtoReflect.Descriptor instead.
func (*ListProposalsRequest) Descriptor() ([]byte, []int) {
	return file_proto_remediation_v1_remediation_proto_rawDescGZIP(), []int{1}
}

func (x *ListProposalsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListProposalsRequest) GetPrState() string {
	if x != nil {
		return x.PrState
	}
	return ""
}

func (x *ListProposalsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListProposalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proposals     []*Proposal            `protobuf:"bytes,1,rep,name=proposals,proto3" json:"proposals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProposalsResponse) Reset() {
	*x = ListProposalsResponse{}
	mi := &file_proto_remediation_v1_remediation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProposalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProposalsResponse) ProtoMessage() {}

func (x *ListProposalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remediation_v1_remediation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProposalsResponse.ProtoReflect.Descriptor instead.
func (*ListProposalsResponse) Descriptor() ([]byte, []int) {
	return file_proto_remediation_v1_remediation_proto_rawDescGZIP(), []int{2}
}

func (x *ListProposalsResponse) GetProposals() []*Proposal {
	if x != nil {
		return x.Proposals
	}
	return nil
}

type GetProposalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProposalRequest) Reset() {
	*x = GetProposalRequest{}
	mi := &file_proto_remediation_v1_remediation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProposalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProposalRequest) ProtoMessage() {}

func (x *GetProposalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remediation_v1_remediation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProposalRequest.ProtoReflect.Descriptor instead.
func (*GetProposalRequest) Descriptor() ([]byte, []int) {
	return file_proto_remediation_v1_remediation_proto_rawDescGZIP(), []int{3}
}

func (x *GetProposalRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// BeginPullRequestRequest identifies the proposal to claim for PR creation.
type BeginPullRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginPullRequestRequest) Reset() {
	*x = BeginPullRequestRequest{}
	mi := &file_proto_remediation_v1_remediation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginPullRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginPullRequestRequest) ProtoMessage() {}

func (x *BeginPullRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remediation_v1_remediation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginPullRequestRequest.ProtoReflect.Descriptor instead.
func (*BeginPullRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_remediation_v1_remediation_proto_rawDescGZIP(), []int{4}
}

func (x *BeginPullRequestRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// BeginPullRequestResponse carries all data needed to open a GitHub pull-request.
type BeginPullRequestResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProposalId     string                 `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	Repo           string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	CommitSha      string                 `protobuf:"bytes,3,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	FilePath       string                 `protobuf:"bytes,4,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	ProposedSqlUri string                 `protobuf:"bytes,5,opt,name=proposed_sql_uri,json=proposedSqlUri,proto3" json:"proposed_sql_uri,omitempty"`
	DiffUri        string                 `protobuf:"bytes,6,opt,name=diff_uri,json=diffUri,proto3" json:"diff_uri,omitempty"`
	ReleaseId      string                 `protobuf:"bytes,7,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	NodeId         string                 `protobuf:"bytes,8,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Attempt        int32                  `protobuf:"varint,9,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Rationale      string                 `protobuf:"bytes,10,opt,name=rationale,proto3" json:"rationale,omitempty"`
	Confidence     string                 `protobuf:"bytes,11,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Model          string                 `protobuf:"bytes,12,opt,name=model,proto3" json:"model,omitempty"`
	// branch is the git branch name to open the PR from.
	Branch        string `protobuf:"bytes,13,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginPullRequestResponse) Reset() {
	*x = BeginPullRequestResponse{}
	mi := &file_proto_remediation_v1_remediation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginPullRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginPullRequestResponse) ProtoMessage() {}

func (x *BeginPullRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remediation_v1_remediation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginPullRequestResponse.ProtoReflect.Descriptor instead.
func (*BeginPullRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_remediation_v1_remediation_proto_rawDescGZIP(), []int{5}
}

func (x *BeginPullRequestResponse) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

func (x *BeginPullRequestResponse) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *BeginPullRequestResponse) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *BeginPullRequestResponse) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *BeginPullRequestResponse) GetProposedSqlUri() string {
	if x != nil {
		return x.ProposedSqlUri
	}
	return ""
}

func (x *BeginPullRequestResponse) GetDiffUri() string {
	if x != nil {
		return x.DiffUri
	}
	return ""
}

func (x *BeginPullRequestResponse) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

func (x *BeginPullRequestResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *BeginPullRequestResponse) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *BeginPullRequestResponse) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

func (x *BeginPullRequestResponse) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

func (x *BeginPullRequestResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *BeginPullRequestResponse) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

// RecordPullRequestRequest stores the PR metadata after a PR is opened.
type RecordPullRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PrUrl         string                 `protobuf:"bytes,2,opt,name=pr_url,json=prUrl,proto3" json:"pr_url,omitempty"`
	PrNumber      int32                  `protobuf:"varint,3,opt,name=pr_number,json=prNumber,proto3" json:"pr_number,omitempty"`
	OpenedBy      string                 `protobuf:"bytes,4,opt,name=opened_by,json=openedBy,proto3" json:"opened_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordPullRequestRequest) Reset() {
	*x = RecordPullRequestRequest{}
	mi := &file_proto_remediation_v1_remediation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordPullRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordPullRequestRequest) ProtoMessage() {}

func (x *RecordPullRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remediation_v1_remediation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordPullRequestRequest.ProtoReflect.Descriptor instead.
func (*RecordPullRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_remediation_v1_remediation_proto_rawDescGZIP(), []int{6}
}

func (x *RecordPullRequestRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecordPullRequestRequest) GetPrUrl() string {
	if x != nil {
		return x.PrUrl
	}
	return ""
}

func (x *RecordPullRequestRequest) GetPrNumber() int32 {
	if x != nil {
		return x.PrNumber
	}
	return 0
}

func (x *RecordPullRequestRequest) GetOpenedBy() string {
	if x != nil {
		return x.OpenedBy
	}
	return ""
}

type RecordPullRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordPullRequestResponse) Reset() {
	*x = RecordPullRequestResponse{}
	mi := &file_proto_remediation_v1_remediation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordPullRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordPullRequestResponse) ProtoMessage() {}

func (x *RecordPullRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remediation_v1_remediation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordPullRequestResponse.ProtoReflect.Descriptor instead.
func (*RecordPullRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_remediation_v1_remediation_proto_rawDescGZIP(), []int{7}
}

// FailPullRequestRequest identifies the proposal whose PR attempt failed.
type FailPullRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailPullRequestRequest) Reset() {
	*x = FailPullRequestRequest{}
	mi := &file_proto_remediation_v1_remediation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailPullRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailPullRequestRequest) ProtoMessage() {}

func (x *FailPullRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remediation_v1_remediation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailPullRequestRequest.ProtoReflect.Descriptor instead.
func (*FailPullRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_remediation_v1_remediation_proto_rawDescGZIP(), []int{8}
}

func (x *FailPullRequestRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FailPullRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailPullRequestResponse) Reset() {
	*x = FailPullRequestResponse{}
	mi := &file_proto_remediation_v1_remediation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailPullRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailPullRequestResponse) ProtoMessage() {}

func (x *FailPullRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remediation_v1_remediation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailPullRequestResponse.ProtoReflect.Descriptor instead.
func (*FailPullRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_remediation_v1_remediation_proto_rawDescGZIP(), []int{9}
}

var File_proto_remediation_v1_remediation_proto protoreflect.FileDescriptor

const file_proto_remediation_v1_remediation_proto_rawDesc = "" +
	"\n" +
	"&proto/remediation/v1/remediation.proto\x12\x0eremediation.v1\"\xf1\x05\n" +
	"\bProposal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"release_id\x18\x03 \x01(\tR\treleaseId\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12'\n" +
	"\x0ferror_signature\x18\x05 \x01(\tR\x0eerrorSignature\x12\x18\n" +
	"\aattempt\x18\x06 \x01(\x05R\aattempt\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"confidence\x18\b \x01(\tR\n" +
	"confidence\x12\x1c\n" +
	"\trationale\x18\t \x01(\tR\trationale\x12(\n" +
	"\x10proposed_sql_uri\x18\n" +
	" \x01(\tR\x0eproposedSqlUri\x12\x19\n" +
	"\bdiff_uri\x18\v \x01(\tR\adiffUri\x121\n" +
	"\x15candidate_fix_sql_uri\x18\f \x01(\tR\x12candidateFixSqlUri\x123\n" +
	"\x16candidate_fix_diff_uri\x18\r \x01(\tR\x13candidateFixDiffUri\x12'\n" +
	"\x0fsource_resolved\x18\x0e \x01(\bR\x0esourceResolved\x12\x12\n" +
	"\x04repo\x18\x0f \x01(\tR\x04repo\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x10 \x01(\tR\tcommitSha\x12\x1b\n" +
	"\tfile_path\x18\x11 \x01(\tR\bfilePath\x12\x14\n" +
	"\x05model\x18\x12 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"created_at\x18\x13 \x01(\tR\tcreatedAt\x12\x15\n" +
	"\x06pr_url\x18\x14 \x01(\tR\x05prUrl\x12\x1b\n" +
	"\tpr_number\x18\x15 \x01(\x05R\bprNumber\x12\x19\n" +
	"\bpr_state\x18\x16 \x01(\tR\aprState\x12 \n" +
	"\fpr_opened_at\x18\x17 \x01(\tR\n" +
	"prOpenedAt\x12 \n" +
	"\fpr_opened_by\x18\x18 \x01(\tR\n" +
	"prOpenedBy\"_\n" +
	"\x14ListProposalsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x19\n" +
	"\bpr_state\x18\x02 \x01(\tR\aprState\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"O\n" +
	"\x15ListProposalsResponse\x126\n" +
	"\tproposals\x18\x01 \x03(\v2\x18.remediation.v1.ProposalR\tproposals\"$\n" +
	"\x12GetProposalRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\")\n" +
	"\x17BeginPullRequestRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8e\x03\n" +
	"\x18BeginPullRequestResponse\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\tR\n" +
	"proposalId\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x03 \x01(\tR\tcommitSha\x12\x1b\n" +
	"\tfile_path\x18\x04 \x01(\tR\bfilePath\x12(\n" +
	"\x10proposed_sql_uri\x18\x05 \x01(\tR\x0eproposedSqlUri\x12\x19\n" +
	"\bdiff_uri\x18\x06 \x01(\tR\adiffUri\x12\x1d\n" +
	"\n" +
	"release_id\x18\a \x01(\tR\treleaseId\x12\x17\n" +
	"\anode_id\x18\b \x01(\tR\x06nodeId\x12\x18\n" +
	"\aattempt\x18\t \x01(\x05R\aattempt\x12\x1c\n" +
	"\trationale\x18\n" +
	" \x01(\tR\trationale\x12\x1e\n" +
	"\n" +
	"confidence\x18\v \x01(\tR\n" +
	"confidence\x12\x14\n" +
	"\x05model\x18\f \x01(\tR\x05model\x12\x16\n" +
	"\x06branch\x18\r \x01(\tR\x06branch\"{\n" +
	"\x18RecordPullRequestRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06pr_url\x18\x02 \x01(\tR\x05prUrl\x12\x1b\n" +
	"\tpr_number\x18\x03 \x01(\x05R\bprNumber\x12\x1b\n" +
	"\topened_by\x18\x04 \x01(\tR\bopenedBy\"\x1b\n" +
	"\x19RecordPullRequestResponse\"(\n" +
	"\x16FailPullRequestRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x19\n" +
	"\x17FailPullRequestResponse2\xf6\x03\n" +
	"\x14RemediationProposals\x12\\\n" +
	"\rListProposals\x12$.remediation.v1.ListProposalsRequest\x1a%.remediation.v1.ListProposalsResponse\x12K\n" +
	"\vGetProposal\x12\".remediation.v1.GetProposalRequest\x1a\x18.remediation.v1.Proposal\x12e\n" +
	"\x10BeginPullRequest\x12'.remediation.v1.BeginPullRequestRequest\x1a(.remediation.v1.BeginPullRequestResponse\x12h\n" +
	"\x11RecordPullRequest\x12(.remediation.v1.RecordPullRequestRequest\x1a).remediation.v1.RecordPullRequestResponse\x12b\n" +
	"\x0fFailPullRequest\x12&.remediation.v1.FailPullRequestRequest\x1a'.remediation.v1.FailPullRequestResponseBTZRgithub.com/carolsimone/continuo/remediation-agent/api/remediation/v1;remediationv1b\x06proto3"

var (
	file_proto_remediation_v1_remediation_proto_rawDescOnce sync.Once
	file_proto_remediation_v1_remediation_proto_rawDescData []byte
)

func file_proto_remediation_v1_remediation_proto_rawDescGZIP() []byte {
	file_proto_remediation_v1_remediation_proto_rawDescOnce.Do(func() {
		file_proto_remediation_v1_remediation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_remediation_v1_remediation_proto_rawDesc), len(file_proto_remediation_v1_remediation_proto_rawDesc)))
	})
	return file_proto_remediation_v1_remediation_proto_rawDescData
}

var file_proto_remediation_v1_remediation_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_remediation_v1_remediation_proto_goTypes = []any{
	(*Proposal)(nil),                  // 0: remediation.v1.Proposal
	(*ListProposalsRequest)(nil),      // 1: remediation.v1.ListProposalsRequest
	(*ListProposalsResponse)(nil),     // 2: remediation.v1.ListProposalsResponse
	(*GetProposalRequest)(nil),        // 3: remediation.v1.GetProposalRequest
	(*BeginPullRequestRequest)(nil),   // 4: remediation.v1.BeginPullRequestRequest
	(*BeginPullRequestResponse)(nil),  // 5: remediation.v1.BeginPullRequestResponse
	(*RecordPullRequestRequest)(nil),  // 6: remediation.v1.RecordPullRequestRequest
	(*RecordPullRequestResponse)(nil), // 7: remediation.v1.RecordPullRequestResponse
	(*FailPullRequestRequest)(nil),    // 8: remediation.v1.FailPullRequestRequest
	(*FailPullRequestResponse)(nil),   // 9: remediation.v1.FailPullRequestResponse
}
var file_proto_remediation_v1_remediation_proto_depIdxs = []int32{
	0, // 0: remediation.v1.ListProposalsResponse.proposals:type_name -> remediation.v1.Proposal
	1, // 1: remediation.v1.RemediationProposals.ListProposals:input_type -> remediation.v1.ListProposalsRequest
	3, // 2: remediation.v1.RemediationProposals.GetProposal:input_type -> remediation.v1.GetProposalRequest
	4, // 3: remediation.v1.RemediationProposals.BeginPullRequest:input_type -> remediation.v1.BeginPullRequestRequest
	6, // 4: remediation.v1.RemediationProposals.RecordPullRequest:input_type -> remediation.v1.RecordPullRequestRequest
	8, // 5: remediation.v1.RemediationProposals.FailPullRequest:input_type -> remediation.v1.FailPullRequestRequest
	2, // 6: remediation.v1.RemediationProposals.ListProposals:output_type -> remediation.v1.ListProposalsResponse
	0, // 7: remediation.v1.RemediationProposals.GetProposal:output_type -> remediation.v1.Proposal
	5, // 8: remediation.v1.RemediationProposals.BeginPullRequest:output_type -> remediation.v1.BeginPullRequestResponse
	7, // 9: remediation.v1.RemediationProposals.RecordPullRequest:output_type -> remediation.v1.RecordPullRequestResponse
	9, // 10: remediation.v1.RemediationProposals.FailPullRequest:output_type -> remediation.v1.FailPullRequestResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_remediation_v1_remediation_proto_init() }
func file_proto_remediation_v1_remediation_proto_init() {
	if File_proto_remediation_v1_remediation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_remediation_v1_remediation_proto_rawDesc), len(file_proto_remediation_v1_remediation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_remediation_v1_remediation_proto_goTypes,
		DependencyIndexes: file_proto_remediation_v1_remediation_proto_depIdxs,
		MessageInfos:      file_proto_remediation_v1_remediation_proto_msgTypes,
	}.Build()
	File_proto_remediation_v1_remediation_proto = out.File
	file_proto_remediation_v1_remediation_proto_goTypes = nil
	file_proto_remediation_v1_remediation_proto_depIdxs = nil
}
