// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: proto/remediation/v1/remediation.proto

package remediationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RemediationProposals_ListProposals_FullMethodName     = "/remediation.v1.RemediationProposals/ListProposals"
	RemediationProposals_GetProposal_FullMethodName       = "/remediation.v1.RemediationProposals/GetProposal"
	RemediationProposals_BeginPullRequest_FullMethodName  = "/remediation.v1.RemediationProposals/BeginPullRequest"
	RemediationProposals_RecordPullRequest_FullMethodName = "/remediation.v1.RemediationProposals/RecordPullRequest"
	RemediationProposals_FailPullRequest_FullMethodName   = "/remediation.v1.RemediationProposals/FailPullRequest"
)

// RemediationProposalsClient is the client API for RemediationProposals service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RemediationProposals serves the proposal read-path and pull-request lifecycle
// for the remediation-agent. The UI reads proposals via ListProposals/GetProposal
// and drives the PR workflow via BeginPullRequest/RecordPullRequest/FailPullRequest.
type RemediationProposalsClient interface {
	// ListProposals returns proposals filtered by status, pr_state, and limit.
	ListProposals(ctx context.Context, in *ListProposalsRequest, opts ...grpc.CallOption) (*ListProposalsResponse, error)
	// GetProposal returns a single proposal by ID.
	GetProposal(ctx context.Context, in *GetProposalRequest, opts ...grpc.CallOption) (*Proposal, error)
	// BeginPullRequest atomically claims a proposal for PR creation and returns
	// the data needed to open a GitHub pull-request.
	BeginPullRequest(ctx context.Context, in *BeginPullRequestRequest, opts ...grpc.CallOption) (*BeginPullRequestResponse, error)
	// RecordPullRequest stores the PR URL, number, and opener after a PR is opened.
	RecordPullRequest(ctx context.Context, in *RecordPullRequestRequest, opts ...grpc.CallOption) (*RecordPullRequestResponse, error)
	// FailPullRequest marks a proposal's PR attempt as failed.
	FailPullRequest(ctx context.Context, in *FailPullRequestRequest, opts ...grpc.CallOption) (*FailPullRequestResponse, error)
}

type remediationProposalsClient struct {
	cc grpc.ClientConnInterface
}

func NewRemediationProposalsClient(cc grpc.ClientConnInterface) RemediationProposalsClient {
	return &remediationProposalsClient{cc}
}

func (c *remediationProposalsClient) ListProposals(ctx context.Context, in *ListProposalsRequest, opts ...grpc.CallOption) (*ListProposalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProposalsResponse)
	err := c.cc.Invoke(ctx, RemediationProposals_ListProposals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remediationProposalsClient) GetProposal(ctx context.Context, in *GetProposalRequest, opts ...grpc.CallOption) (*Proposal, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Proposal)
	err := c.cc.Invoke(ctx, RemediationProposals_GetProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remediationProposalsClient) BeginPullRequest(ctx context.Context, in *BeginPullRequestRequest, opts ...grpc.CallOption) (*BeginPullRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginPullRequestResponse)
	err := c.cc.Invoke(ctx, RemediationProposals_BeginPullRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remediationProposalsClient) RecordPullRequest(ctx context.Context, in *RecordPullRequestRequest, opts ...grpc.CallOption) (*RecordPullRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordPullRequestResponse)
	err := c.cc.Invoke(ctx, RemediationProposals_RecordPullRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remediationProposalsClient) FailPullRequest(ctx context.Context, in *FailPullRequestRequest, opts ...grpc.CallOption) (*FailPullRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FailPullRequestResponse)
	err := c.cc.Invoke(ctx, RemediationProposals_FailPullRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemediationProposalsServer is the server API for RemediationProposals service.
// All implementations must embed UnimplementedRemediationProposalsServer
// for forward compatibility.
//
// RemediationProposals serves the proposal read-path and pull-request lifecycle
// for the remediation-agent. The UI reads proposals via ListProposals/GetProposal
// and drives the PR workflow via BeginPullRequest/RecordPullRequest/FailPullRequest.
type RemediationProposalsServer interface {
	// ListProposals returns proposals filtered by status, pr_state, and limit.
	ListProposals(context.Context, *ListProposalsRequest) (*ListProposalsResponse, error)
	// GetProposal returns a single proposal by ID.
	GetProposal(context.Context, *GetProposalRequest) (*Proposal, error)
	// BeginPullRequest atomically claims a proposal for PR creation and returns
	// the data needed to open a GitHub pull-request.
	BeginPullRequest(context.Context, *BeginPullRequestRequest) (*BeginPullRequestResponse, error)
	// RecordPullRequest stores the PR URL, number, and opener after a PR is opened.
	RecordPullRequest(context.Context, *RecordPullRequestRequest) (*RecordPullRequestResponse, error)
	// FailPullRequest marks a proposal's PR attempt as failed.
	FailPullRequest(context.Context, *FailPullRequestRequest) (*FailPullRequestResponse, error)
	mustEmbedUnimplementedRemediationProposalsServer()
}

// UnimplementedRemediationProposalsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRemediationProposalsServer struct{}

func (UnimplementedRemediationProposalsServer) ListProposals(context.Context, *ListProposalsRequest) (*ListProposalsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProposals not implemented")
}
func (UnimplementedRemediationProposalsServer) GetProposal(context.Context, *GetProposalRequest) (*Proposal, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProposal not implemented")
}
func (UnimplementedRemediationProposalsServer) BeginPullRequest(context.Context, *BeginPullRequestRequest) (*BeginPullRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginPullRequest not implemented")
}
func (UnimplementedRemediationProposalsServer) RecordPullRequest(context.Context, *RecordPullRequestRequest) (*RecordPullRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordPullRequest not implemented")
}
func (UnimplementedRemediationProposalsServer) FailPullRequest(context.Context, *FailPullRequestRequest) (*FailPullRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FailPullRequest not implemented")
}
func (UnimplementedRemediationProposalsServer) mustEmbedUnimplementedRemediationProposalsServer() {}
func (UnimplementedRemediationProposalsServer) testEmbeddedByValue()                              {}

// UnsafeRemediationProposalsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemediationProposalsServer will
// result in compilation errors.
type UnsafeRemediationProposalsServer interface {
	mustEmbedUnimplementedRemediationProposalsServer()
}

func RegisterRemediationProposalsServer(s grpc.ServiceRegistrar, srv RemediationProposalsServer) {
	// If the following call panics, it indicates UnimplementedRemediationProposalsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RemediationProposals_ServiceDesc, srv)
}

func _RemediationProposals_ListProposals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProposalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemediationProposalsServer).ListProposals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemediationProposals_ListProposals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemediationProposalsServer).ListProposals(ctx, req.(*ListProposalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemediationProposals_GetProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemediationProposalsServer).GetProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemediationProposals_GetProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemediationProposalsServer).GetProposal(ctx, req.(*GetProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemediationProposals_BeginPullRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginPullRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemediationProposalsServer).BeginPullRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemediationProposals_BeginPullRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemediationProposalsServer).BeginPullRequest(ctx, req.(*BeginPullRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemediationProposals_RecordPullRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordPullRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemediationProposalsServer).RecordPullRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemediationProposals_RecordPullRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemediationProposalsServer).RecordPullRequest(ctx, req.(*RecordPullRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemediationProposals_FailPullRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailPullRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemediationProposalsServer).FailPullRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemediationProposals_FailPullRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemediationProposalsServer).FailPullRequest(ctx, req.(*FailPullRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RemediationProposals_ServiceDesc is the grpc.ServiceDesc for RemediationProposals service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RemediationProposals_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "remediation.v1.RemediationProposals",
	HandlerType: (*RemediationProposalsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProposals",
			Handler:    _RemediationProposals_ListProposals_Handler,
		},
		{
			MethodName: "GetProposal",
			Handler:    _RemediationProposals_GetProposal_Handler,
		},
		{
			MethodName: "BeginPullRequest",
			Handler:    _RemediationProposals_BeginPullRequest_Handler,
		},
		{
			MethodName: "RecordPullRequest",
			Handler:    _RemediationProposals_RecordPullRequest_Handler,
		},
		{
			MethodName: "FailPullRequest",
			Handler:    _RemediationProposals_FailPullRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/remediation/v1/remediation.proto",
}
