// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/deadletter/v1/deadletter.proto

package deadletterv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeadLetter struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source            string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`                              // consumer | outbox | quarantine
	FailureKind       string                 `protobuf:"bytes,3,opt,name=failure_kind,json=failureKind,proto3" json:"failure_kind,omitempty"` // permanent | transient_exhausted | trimmed
	Stream            string                 `protobuf:"bytes,4,opt,name=stream,proto3" json:"stream,omitempty"`
	ConsumerGroup     string                 `protobuf:"bytes,5,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`               // empty for an outbox dead letter
	OriginalMessageId string                 `protobuf:"bytes,6,opt,name=original_message_id,json=originalMessageId,proto3" json:"original_message_id,omitempty"` // empty for an outbox dead letter
	Producer          string                 `protobuf:"bytes,7,opt,name=producer,proto3" json:"producer,omitempty"`
	Error             string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	DeliveryCount     int64                  `protobuf:"varint,9,opt,name=delivery_count,json=deliveryCount,proto3" json:"delivery_count,omitempty"`
	OriginalAt        string                 `protobuf:"bytes,10,opt,name=original_at,json=originalAt,proto3" json:"original_at,omitempty"`
	RecordedAt        string                 `protobuf:"bytes,11,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	ExpiresAt         string                 `protobuf:"bytes,12,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Status            string                 `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"` // open | redriven
	Redrivable        bool                   `protobuf:"varint,14,opt,name=redrivable,proto3" json:"redrivable,omitempty"`
	Redrive           *Redrive               `protobuf:"bytes,15,opt,name=redrive,proto3" json:"redrive,omitempty"` // set when status is redriven
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeadLetter) Reset() {
	*x = DeadLetter{}
	mi := &file_proto_deadletter_v1_deadletter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeadLetter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeadLetter) ProtoMessage() {}

func (x *DeadLetter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deadletter_v1_deadletter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeadLetter.ProtoReflect.Descriptor instead.
func (*DeadLetter) Descriptor() ([]byte, []int) {
	return file_proto_deadletter_v1_deadletter_proto_rawDescGZIP(), []int{0}
}

func (x *DeadLetter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeadLetter) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DeadLetter) GetFailureKind() string {
	if x != nil {
		return x.FailureKind
	}
	return ""
}

func (x *DeadLetter) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *DeadLetter) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *DeadLetter) GetOriginalMessageId() string {
	if x != nil {
		return x.OriginalMessageId
	}
	return ""
}

func (x *DeadLetter) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *DeadLetter) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DeadLetter) GetDeliveryCount() int64 {
	if x != nil {
		return x.DeliveryCount
	}
	return 0
}

func (x *DeadLetter) GetOriginalAt() string {
	if x != nil {
		return x.OriginalAt
	}
	return ""
}

func (x *DeadLetter) GetRecordedAt() string {
	if x != nil {
		return x.RecordedAt
	}
	return ""
}

func (x *DeadLetter) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *DeadLetter) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeadLetter) GetRedrivable() bool {
	if x != nil {
		return x.Redrivable
	}
	return false
}

func (x *DeadLetter) GetRedrive() *Redrive {
	if x != nil {
		return x.Redrive
	}
	return nil
}

type Redrive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         string                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	At            string                 `protobuf:"bytes,3,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Redrive) Reset() {
	*x = Redrive{}
	mi := &file_proto_deadletter_v1_deadletter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Redrive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Redrive) ProtoMessage() {}

func (x *Redrive) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deadletter_v1_deadletter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Redrive.ProtoReflect.Descriptor instead.
func (*Redrive) Descriptor() ([]byte, []int) {
	return file_proto_deadletter_v1_deadletter_proto_rawDescGZIP(), []int{1}
}

func (x *Redrive) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *Redrive) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Redrive) GetAt() string {
	if x != nil {
		return x.At
	}
	return ""
}

type ListDeadLettersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Stream        string                 `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeadLettersRequest) Reset() {
	*x = ListDeadLettersRequest{}
	mi := &file_proto_deadletter_v1_deadletter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeadLettersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeadLettersRequest) ProtoMessage() {}

func (x *ListDeadLettersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deadletter_v1_deadletter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeadLettersRequest.ProtoReflect.Descriptor instead.
func (*ListDeadLettersRequest) Descriptor() ([]byte, []int) {
	return file_proto_deadletter_v1_deadletter_proto_rawDescGZIP(), []int{2}
}

func (x *ListDeadLettersRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ListDeadLettersRequest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *ListDeadLettersRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListDeadLettersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListDeadLettersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeadLetters   []*DeadLetter          `protobuf:"bytes,1,rep,name=dead_letters,json=deadLetters,proto3" json:"dead_letters,omitempty"`
	TotalOpen     int64                  `protobuf:"varint,2,opt,name=total_open,json=totalOpen,proto3" json:"total_open,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeadLettersResponse) Reset() {
	*x = ListDeadLettersResponse{}
	mi := &file_proto_deadletter_v1_deadletter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeadLettersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeadLettersResponse) ProtoMessage() {}

func (x *ListDeadLettersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deadletter_v1_deadletter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeadLettersResponse.ProtoReflect.Descriptor instead.
func (*ListDeadLettersResponse) Descriptor() ([]byte, []int) {
	return file_proto_deadletter_v1_deadletter_proto_rawDescGZIP(), []int{3}
}

func (x *ListDeadLettersResponse) GetDeadLetters() []*DeadLetter {
	if x != nil {
		return x.DeadLetters
	}
	return nil
}

func (x *ListDeadLettersResponse) GetTotalOpen() int64 {
	if x != nil {
		return x.TotalOpen
	}
	return 0
}

type GetDeadLetterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeadLetterRequest) Reset() {
	*x = GetDeadLetterRequest{}
	mi := &file_proto_deadletter_v1_deadletter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeadLetterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeadLetterRequest) ProtoMessage() {}

func (x *GetDeadLetterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deadletter_v1_deadletter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeadLetterRequest.ProtoReflect.Descriptor instead.
func (*GetDeadLetterRequest) Descriptor() ([]byte, []int) {
	return file_proto_deadletter_v1_deadletter_proto_rawDescGZIP(), []int{4}
}

func (x *GetDeadLetterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDeadLetterResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DeadLetter        *DeadLetter            `protobuf:"bytes,1,opt,name=dead_letter,json=deadLetter,proto3" json:"dead_letter,omitempty"`
	Fields            map[string]string      `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OriginalEventType string                 `protobuf:"bytes,3,opt,name=original_event_type,json=originalEventType,proto3" json:"original_event_type,omitempty"`
	FailedOutboxId    string                 `protobuf:"bytes,4,opt,name=failed_outbox_id,json=failedOutboxId,proto3" json:"failed_outbox_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetDeadLetterResponse) Reset() {
	*x = GetDeadLetterResponse{}
	mi := &file_proto_deadletter_v1_deadletter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeadLetterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeadLetterResponse) ProtoMessage() {}

func (x *GetDeadLetterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deadletter_v1_deadletter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeadLetterResponse.ProtoReflect.Descriptor instead.
func (*GetDeadLetterResponse) Descriptor() ([]byte, []int) {
	return file_proto_deadletter_v1_deadletter_proto_rawDescGZIP(), []int{5}
}

func (x *GetDeadLetterResponse) GetDeadLetter() *DeadLetter {
	if x != nil {
		return x.DeadLetter
	}
	return nil
}

func (x *GetDeadLetterResponse) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *GetDeadLetterResponse) GetOriginalEventType() string {
	if x != nil {
		return x.OriginalEventType
	}
	return ""
}

func (x *GetDeadLetterResponse) GetFailedOutboxId() string {
	if x != nil {
		return x.FailedOutboxId
	}
	return ""
}

type RedriveDeadLettersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedriveDeadLettersRequest) Reset() {
	*x = RedriveDeadLettersRequest{}
	mi := &file_proto_deadletter_v1_deadletter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedriveDeadLettersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedriveDeadLettersRequest) ProtoMessage() {}

func (x *RedriveDeadLettersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deadletter_v1_deadletter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedriveDeadLettersRequest.ProtoReflect.Descriptor instead.
func (*RedriveDeadLettersRequest) Descriptor() ([]byte, []int) {
	return file_proto_deadletter_v1_deadletter_proto_rawDescGZIP(), []int{6}
}

func (x *RedriveDeadLettersRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *RedriveDeadLettersRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RedriveDeadLettersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeadLetters   []*DeadLetter          `protobuf:"bytes,1,rep,name=dead_letters,json=deadLetters,proto3" json:"dead_letters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedriveDeadLettersResponse) Reset() {
	*x = RedriveDeadLettersResponse{}
	mi := &file_proto_deadletter_v1_deadletter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedriveDeadLettersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedriveDeadLettersResponse) ProtoMessage() {}

func (x *RedriveDeadLettersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deadletter_v1_deadletter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedriveDeadLettersResponse.ProtoReflect.Descriptor instead.
func (*RedriveDeadLettersResponse) Descriptor() ([]byte, []int) {
	return file_proto_deadletter_v1_deadletter_proto_rawDescGZIP(), []int{7}
}

func (x *RedriveDeadLettersResponse) GetDeadLetters() []*DeadLetter {
	if x != nil {
		return x.DeadLetters
	}
	return nil
}

var File_proto_deadletter_v1_deadletter_proto protoreflect.FileDescriptor

const file_proto_deadletter_v1_deadletter_proto_rawDesc = "" +
	"\n" +
	"$proto/deadletter/v1/deadletter.proto\x12\rdeadletter.v1\"\xea\x03\n" +
	"\n" +
	"DeadLetter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12!\n" +
	"\ffailure_kind\x18\x03 \x01(\tR\vfailureKind\x12\x16\n" +
	"\x06stream\x18\x04 \x01(\tR\x06stream\x12%\n" +
	"\x0econsumer_group\x18\x05 \x01(\tR\rconsumerGroup\x12.\n" +
	"\x13original_message_id\x18\x06 \x01(\tR\x11originalMessageId\x12\x1a\n" +
	"\bproducer\x18\a \x01(\tR\bproducer\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12%\n" +
	"\x0edelivery_count\x18\t \x01(\x03R\rdeliveryCount\x12\x1f\n" +
	"\voriginal_at\x18\n" +
	" \x01(\tR\n" +
	"originalAt\x12\x1f\n" +
	"\vrecorded_at\x18\v \x01(\tR\n" +
	"recordedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\f \x01(\tR\texpiresAt\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"redrivable\x18\x0e \x01(\bR\n" +
	"redrivable\x120\n" +
	"\aredrive\x18\x0f \x01(\v2\x16.deadletter.v1.RedriveR\aredrive\"G\n" +
	"\aRedrive\x12\x14\n" +
	"\x05actor\x18\x01 \x01(\tR\x05actor\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x0e\n" +
	"\x02at\x18\x03 \x01(\tR\x02at\"v\n" +
	"\x16ListDeadLettersRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\tR\x06stream\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"v\n" +
	"\x17ListDeadLettersResponse\x12<\n" +
	"\fdead_letters\x18\x01 \x03(\v2\x19.deadletter.v1.DeadLetterR\vdeadLetters\x12\x1d\n" +
	"\n" +
	"total_open\x18\x02 \x01(\x03R\ttotalOpen\"&\n" +
	"\x14GetDeadLetterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb2\x02\n" +
	"\x15GetDeadLetterResponse\x12:\n" +
	"\vdead_letter\x18\x01 \x01(\v2\x19.deadletter.v1.DeadLetterR\n" +
	"deadLetter\x12H\n" +
	"\x06fields\x18\x02 \x03(\v20.deadletter.v1.GetDeadLetterResponse.FieldsEntryR\x06fields\x12.\n" +
	"\x13original_event_type\x18\x03 \x01(\tR\x11originalEventType\x12(\n" +
	"\x10failed_outbox_id\x18\x04 \x01(\tR\x0efailedOutboxId\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\x19RedriveDeadLettersRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"Z\n" +
	"\x1aRedriveDeadLettersResponse\x12<\n" +
	"\fdead_letters\x18\x01 \x03(\v2\x19.deadletter.v1.DeadLetterR\vdeadLetters2\xbc\x02\n" +
	"\x11DeadLetterService\x12`\n" +
	"\x0fListDeadLetters\x12%.deadletter.v1.ListDeadLettersRequest\x1a&.deadletter.v1.ListDeadLettersResponse\x12Z\n" +
	"\rGetDeadLetter\x12#.deadletter.v1.GetDeadLetterRequest\x1a$.deadletter.v1.GetDeadLetterResponse\x12i\n" +
	"\x12RedriveDeadLetters\x12(.deadletter.v1.RedriveDeadLettersRequest\x1a).deadletter.v1.RedriveDeadLettersResponseBWZUgithub.com/carolsimone/continuo/dead-letter-controller/api/deadletter/v1;deadletterv1b\x06proto3"

var (
	file_proto_deadletter_v1_deadletter_proto_rawDescOnce sync.Once
	file_proto_deadletter_v1_deadletter_proto_rawDescData []byte
)

func file_proto_deadletter_v1_deadletter_proto_rawDescGZIP() []byte {
	file_proto_deadletter_v1_deadletter_proto_rawDescOnce.Do(func() {
		file_proto_deadletter_v1_deadletter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_deadletter_v1_deadletter_proto_rawDesc), len(file_proto_deadletter_v1_deadletter_proto_rawDesc)))
	})
	return file_proto_deadletter_v1_deadletter_proto_rawDescData
}

var file_proto_deadletter_v1_deadletter_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_deadletter_v1_deadletter_proto_goTypes = []any{
	(*DeadLetter)(nil),                 // 0: deadletter.v1.DeadLetter
	(*Redrive)(nil),                    // 1: deadletter.v1.Redrive
	(*ListDeadLettersRequest)(nil),     // 2: deadletter.v1.ListDeadLettersRequest
	(*ListDeadLettersResponse)(nil),    // 3: deadletter.v1.ListDeadLettersResponse
	(*GetDeadLetterRequest)(nil),       // 4: deadletter.v1.GetDeadLetterRequest
	(*GetDeadLetterResponse)(nil),      // 5: deadletter.v1.GetDeadLetterResponse
	(*RedriveDeadLettersRequest)(nil),  // 6: deadletter.v1.RedriveDeadLettersRequest
	(*RedriveDeadLettersResponse)(nil), // 7: deadletter.v1.RedriveDeadLettersResponse
	nil,                                // 8: deadletter.v1.GetDeadLetterResponse.FieldsEntry
}
var file_proto_deadletter_v1_deadletter_proto_depIdxs = []int32{
	1, // 0: deadletter.v1.DeadLetter.redrive:type_name -> deadletter.v1.Redrive
	0, // 1: deadletter.v1.ListDeadLettersResponse.dead_letters:type_name -> deadletter.v1.DeadLetter
	0, // 2: deadletter.v1.GetDeadLetterResponse.dead_letter:type_name -> deadletter.v1.DeadLetter
	8, // 3: deadletter.v1.GetDeadLetterResponse.fields:type_name -> deadletter.v1.GetDeadLetterResponse.FieldsEntry
	0, // 4: deadletter.v1.RedriveDeadLettersResponse.dead_letters:type_name -> deadletter.v1.DeadLetter
	2, // 5: deadletter.v1.DeadLetterService.ListDeadLetters:input_type -> deadletter.v1.ListDeadLettersRequest
	4, // 6: deadletter.v1.DeadLetterService.GetDeadLetter:input_type -> deadletter.v1.GetDeadLetterRequest
	6, // 7: deadletter.v1.DeadLetterService.RedriveDeadLetters:input_type -> deadletter.v1.RedriveDeadLettersRequest
	3, // 8: deadletter.v1.DeadLetterService.ListDeadLetters:output_type -> deadletter.v1.ListDeadLettersResponse
	5, // 9: deadletter.v1.DeadLetterService.GetDeadLetter:output_type -> deadletter.v1.GetDeadLetterResponse
	7, // 10: deadletter.v1.DeadLetterService.RedriveDeadLetters:output_type -> deadletter.v1.RedriveDeadLettersResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_deadletter_v1_deadletter_proto_init() }
func file_proto_deadletter_v1_deadletter_proto_init() {
	if File_proto_deadletter_v1_deadletter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_deadletter_v1_deadletter_proto_rawDesc), len(file_proto_deadletter_v1_deadletter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_deadletter_v1_deadletter_proto_goTypes,
		DependencyIndexes: file_proto_deadletter_v1_deadletter_proto_depIdxs,
		MessageInfos:      file_proto_deadletter_v1_deadletter_proto_msgTypes,
	}.Build()
	File_proto_deadletter_v1_deadletter_proto = out.File
	file_proto_deadletter_v1_deadletter_proto_goTypes = nil
	file_proto_deadletter_v1_deadletter_proto_depIdxs = nil
}
