// Code generated by gen-streams. DO NOT EDIT.
// Source: pkg/streams/contract.yaml
package streams

// Stream names.
const (
	// SchedulerStartedV1 — Scheduler boot heartbeat; orchestrator hydrates its projections on receipt.
	SchedulerStartedV1 = "scheduler.started:v1"
	// SchedulesLoadedV1 — Schedules registered/refreshed by state; consumed by state for catalog projections.
	SchedulesLoadedV1 = "schedules.loaded:v1"
	// RunEntriesDispatchedV1 — Run entries that orchestrator successfully dispatched into the executor queue.
	RunEntriesDispatchedV1 = "run.entries.dispatched:v1"
	// RunEntriesDispatchFailedV1 — Run entries orchestrator failed to dispatch.
	RunEntriesDispatchFailedV1 = "run.entries.dispatch_failed:v1"
	// TaskStatusUpdatedV1 — Per-task status transitions emitted by executor-controller.
	TaskStatusUpdatedV1 = "task.status.updated:v1"
	// TaskExecutionRecordedV1 — Completed task executions emitted by k8s-controller's outbox processor.
	TaskExecutionRecordedV1 = "task.execution.recorded:v1"
	// NodeUpdatedV1 — Node state transitions; orchestrator updates its projections.
	NodeUpdatedV1 = "node.updated:v1"
	// TriggerRerunV1 — User-initiated rerun trigger.
	TriggerRerunV1 = "trigger.rerun:v1"
	// TriggerRebaseV1 — User-initiated rebase trigger.
	TriggerRebaseV1 = "trigger.rebase:v1"
	// TriggerSingleNodeRunV1 — User-initiated single-node run trigger.
	TriggerSingleNodeRunV1 = "trigger.single_node_run:v1"
	// ReleaseSeedsPendingV1 — Seeds a promoted release changed, emitted by orchestrator in the same transaction as the topology swap so the nodes exist before any run is projected onto them.
	ReleaseSeedsPendingV1 = "release.seeds.pending:v1"
	// TriggerPromotedSeedsV1 — Run trigger for the seeds a promoted release changed; state creates the run, orchestrator projects its tasks.
	TriggerPromotedSeedsV1 = "trigger.promoted_seeds:v1"
	// RunFinalizedV1 — Run finalization (success, failure, or cancellation) emitted by state; consumed for projections.
	RunFinalizedV1 = "run.finalized:v1"
	// QueryModelV1 — Tasks dispatched by orchestrator for the executor pool.
	QueryModelV1 = "query.model:v1"
	// RetryTaskV1 — Retry trigger for tasks; produced by k8s-controller, consumed by executor.
	RetryTaskV1 = "retry.task:v1"
	// NodeDeployedV1 — Pod-deploy intent from executor; consumed by k8s-controller.
	NodeDeployedV1 = "node.deployed:v1"
	// CheckK8sV1 — Delayed status-check tickets; a promoter moves due tickets from the delay queue into the stream.
	CheckK8sV1 = "check.k8s:v1"
	// TaskFailedV1 — Terminal task failure emitted by k8s-controller.
	TaskFailedV1 = "task.failed:v1"
	// OutboxDeadLetterV1 — Terminal outbox publish failures (permanent payload errors, or transient errors that exhausted their backoff budget), emitted by every service's outbox processor. Operational DLQ, not a domain event.
	OutboxDeadLetterV1 = "outbox.dead_letter:v1"
	// ScheduleCancelledV1 — Schedule cancellation broadcast; fanned out to orchestrator, executor, k8s.
	ScheduleCancelledV1 = "schedule.cancelled:v1"
	// ReleaseRequestedV1 — Candidate release accepted by release-controller; triggers manifest load for validation.
	ReleaseRequestedV1 = "release.requested:v1"
	// ManifestLoadedCandidateV1 — Resolved candidate topology from topology-controller back to release-controller.
	ManifestLoadedCandidateV1 = "manifest.loaded.candidate:v1"
	// ValidationRequestedV1 — dbt --empty validation run requested by release-controller; executor-controller dispatches per-node jobs.
	ValidationRequestedV1 = "validation.requested:v1"
	// ValidationNodeCompletedV1 — Per-node validation Job terminal status from k8s-controller back to executor-controller; settled into the validation.result:v1 stream (per-node kind=node, plus the terminal kind=complete once all nodes settle).
	ValidationNodeCompletedV1 = "validation.node.completed:v1"
	// ValidationResultV1 — Unified validation-leg stream from executor-controller. Carries per-node results (kind=node, one per node as it settles) and the terminal decision (kind=complete, emitted last). release-controller projects nodes and decides on complete; the decision reads aggregate_status, so it does not depend on delivery order. executor-controller drops the candidate schema on complete.
	ValidationResultV1 = "validation.result:v1"
	// SeedBuildRequestedV1 — release-controller requests candidate seed builds; executor dispatches per-seed team-image jobs.
	SeedBuildRequestedV1 = "seed.build.requested:v1"
	// SeedBuildNodeCompletedV1 — per-seed build terminal status from k8s-controller back to executor-controller.
	SeedBuildNodeCompletedV1 = "seed.build.node.completed:v1"
	// SeedBuildCompletedV1 — aggregated candidate seed-build result from executor-controller back to release-controller.
	SeedBuildCompletedV1 = "seed.build.completed:v1"
	// CompileRequestedV1 — release-controller requests the changed service's dbt compile; executor dispatches the compile Job.
	CompileRequestedV1 = "compile.requested:v1"
	// CompileNodeCompletedV1 — compile Job terminal status from k8s-controller back to executor-controller.
	CompileNodeCompletedV1 = "compile.node.completed:v1"
	// CompileCompletedV1 — aggregated compile result from executor-controller back to release-controller.
	CompileCompletedV1 = "compile.completed:v1"
	// ReleasePromotedV1 — Release promoted to production; orchestrator atomically replaces its Neo4j topology.
	ReleasePromotedV1 = "release.promoted:v1"
	// ReleaseRejectedV1 — Candidate release rejected (compile, parse, seed-build, or validation failure); consumed by the remediation classifier. A verification run's failure never rides this stream.
	ReleaseRejectedV1 = "release.rejected:v1"
	// PipelineRunFinishedV1 — A pipeline run of either kind (a candidate release or a fix-verification run) reached a terminal status; carries the run's candidate schema so executor-controller can drop it whatever the outcome.
	PipelineRunFinishedV1 = "pipeline.run.finished:v1"
	// RemediationRetryRequestedV1 — A human asked for another remediation round on a rejected release; release-controller replays the release's stored rejection payload plus remediation_round, and the remediation classifier re-classifies it as a fresh round.
	RemediationRetryRequestedV1 = "remediation.retry_requested:v1"
	// RemediationRequestedV2 — One batched remediation trigger per rejected release carrying its whole healable node set (each node with the classifier's evidence and its changed ancestors); emitted by the remediation classifier, consumed by the heal agent and by orchestrator's case-base rejections group.
	RemediationRequestedV2 = "remediation.requested:v2"
	// RemediationProposedV1 — One verified fix proposal per (release, attempt), carrying every node the attempt resolves and every file it edits; emitted by the remediation agent, consumed by the PR creator and approval surfaces.
	RemediationProposedV1 = "remediation.proposed:v1"
	// RemediationPrOpenedV1 — Emitted when an operator opens a GitHub PR from a fix proposal, one per (release, attempt) and carrying every node the PR resolves; consumed by orchestrator's case-base proposals group.
	RemediationPrOpenedV1 = "remediation.pr_opened:v1"
	// RemediationPrClosedV1 — Terminal PR outcome (merged, or closed without merge), one per (release, attempt, service); merged outcomes carry per-edit amended flags and diffs, and orchestrator's provenance group draws RESOLVED_BY/EDITED case-base edges from them.
	RemediationPrClosedV1 = "remediation.pr_closed:v1"
)

// Consumer groups.
const (
	// OrchestratorSchedulerStarted — orchestrator consumer group on scheduler.started:v1.
	OrchestratorSchedulerStarted = "orchestrator-scheduler-started"
	// StateScheduleCatalog — state consumer group on schedules.loaded:v1.
	StateScheduleCatalog = "state-schedule-catalog"
	// StateRunEntriesDispatched — state consumer group on run.entries.dispatched:v1.
	StateRunEntriesDispatched = "state-run-entries-dispatched"
	// StateRunEntriesDispatchFailed — state consumer group on run.entries.dispatch_failed:v1.
	StateRunEntriesDispatchFailed = "state-run-entries-dispatch-failed"
	// StateTaskStatusUpdated — state consumer group on task.status.updated:v1.
	StateTaskStatusUpdated = "state-task-status-updated"
	// StateTaskExecutionRecorded — state consumer group on task.execution.recorded:v1.
	StateTaskExecutionRecorded = "state-task-execution-recorded"
	// OrchestratorNodeUpdated — orchestrator consumer group on node.updated:v1.
	OrchestratorNodeUpdated = "orchestrator-node-updated"
	// OrchestratorRerun — orchestrator consumer group on trigger.rerun:v1.
	OrchestratorRerun = "orchestrator-rerun"
	// OrchestratorRebase — orchestrator consumer group on trigger.rebase:v1.
	OrchestratorRebase = "orchestrator-rebase"
	// OrchestratorSingleNodeRun — orchestrator consumer group on trigger.single_node_run:v1.
	OrchestratorSingleNodeRun = "orchestrator-single-node-run"
	// StateReleaseSeedsPending — state consumer group on release.seeds.pending:v1.
	StateReleaseSeedsPending = "state-release-seeds-pending"
	// OrchestratorPromotedSeeds — orchestrator consumer group on trigger.promoted_seeds:v1.
	OrchestratorPromotedSeeds = "orchestrator-promoted-seeds"
	// OrchestratorRunFinalized — orchestrator consumer group on run.finalized:v1.
	OrchestratorRunFinalized = "orchestrator-run-finalized"
	// ExecutorQueryModel — executor-controller consumer group on query.model:v1.
	ExecutorQueryModel = "executor-query-model"
	// ExecutorRetry — executor-controller consumer group on retry.task:v1.
	ExecutorRetry = "executor-retry"
	// K8sDeployed — k8s-controller consumer group on node.deployed:v1.
	K8sDeployed = "k8s-deployed"
	// K8sCheckStatus — k8s-controller consumer group on check.k8s:v1.
	K8sCheckStatus = "k8s-check-status"
	// OrchestratorScheduleCancelled — orchestrator consumer group on schedule.cancelled:v1.
	OrchestratorScheduleCancelled = "orchestrator-schedule-cancelled"
	// ExecutorScheduleCancelled — executor-controller consumer group on schedule.cancelled:v1.
	ExecutorScheduleCancelled = "executor-schedule-cancelled"
	// K8sScheduleCancelled — k8s-controller consumer group on schedule.cancelled:v1.
	K8sScheduleCancelled = "k8s-schedule-cancelled"
	// TopologyControllerReleaseRequested — topology-controller consumer group on release.requested:v1.
	TopologyControllerReleaseRequested = "topology-controller-release-requested"
	// ReleaseControllerManifestLoadedCandidate — release-controller consumer group on manifest.loaded.candidate:v1.
	ReleaseControllerManifestLoadedCandidate = "release-controller-manifest-loaded-candidate"
	// ExecutorValidationRequested — executor-controller consumer group on validation.requested:v1.
	ExecutorValidationRequested = "executor-validation-requested"
	// ExecutorValidationNodeCompleted — executor-controller consumer group on validation.node.completed:v1.
	ExecutorValidationNodeCompleted = "executor-validation-node-completed"
	// ReleaseControllerValidationResult — release-controller consumer group on validation.result:v1.
	ReleaseControllerValidationResult = "release-controller-validation-result"
	// ExecutorValidationResultTeardown — executor-controller consumer group on validation.result:v1.
	ExecutorValidationResultTeardown = "executor-validation-result-teardown"
	// ExecutorSeedBuildRequested — executor-controller consumer group on seed.build.requested:v1.
	ExecutorSeedBuildRequested = "executor-seed-build-requested"
	// ExecutorSeedBuildNodeCompleted — executor-controller consumer group on seed.build.node.completed:v1.
	ExecutorSeedBuildNodeCompleted = "executor-seed-build-node-completed"
	// ReleaseControllerSeedBuildCompleted — release-controller consumer group on seed.build.completed:v1.
	ReleaseControllerSeedBuildCompleted = "release-controller-seed-build-completed"
	// ExecutorCompileRequested — executor-controller consumer group on compile.requested:v1.
	ExecutorCompileRequested = "executor-compile-requested"
	// ExecutorCompileNodeCompleted — executor-controller consumer group on compile.node.completed:v1.
	ExecutorCompileNodeCompleted = "executor-compile-node-completed"
	// ReleaseControllerCompileCompleted — release-controller consumer group on compile.completed:v1.
	ReleaseControllerCompileCompleted = "release-controller-compile-completed"
	// OrchestratorReleasePromoted — orchestrator consumer group on release.promoted:v1.
	OrchestratorReleasePromoted = "orchestrator-release-promoted"
	// OrchestratorReleasePromotedVersions — orchestrator consumer group on release.promoted:v1.
	OrchestratorReleasePromotedVersions = "orchestrator-release-promoted-versions"
	// RemediationReleaseRejected — remediation consumer group on release.rejected:v1.
	RemediationReleaseRejected = "remediation-release-rejected"
	// ExecutorPipelineRunFinished — executor-controller consumer group on pipeline.run.finished:v1.
	ExecutorPipelineRunFinished = "executor-pipeline-run-finished"
	// RemediationRetryRequested — remediation consumer group on remediation.retry_requested:v1.
	RemediationRetryRequested = "remediation-retry-requested"
	// AgentRemediationRemediationRequested — agent-remediation consumer group on remediation.requested:v2.
	AgentRemediationRemediationRequested = "agent-remediation-remediation-requested"
	// OrchestratorRemediationRequestedRejections — orchestrator consumer group on remediation.requested:v2.
	OrchestratorRemediationRequestedRejections = "orchestrator-remediation-requested-rejections"
	// OrchestratorRemediationPrOpenedProposals — orchestrator consumer group on remediation.pr_opened:v1.
	OrchestratorRemediationPrOpenedProposals = "orchestrator-remediation-pr-opened-proposals"
	// OrchestratorRemediationPrClosedProvenance — orchestrator consumer group on remediation.pr_closed:v1.
	OrchestratorRemediationPrClosedProvenance = "orchestrator-remediation-pr-closed-provenance"
)

// All is every stream name from contract.yaml, in contract order — for callers
// that must operate over all streams (e.g. the stream reaper).
var All = []string{
	SchedulerStartedV1,
	SchedulesLoadedV1,
	RunEntriesDispatchedV1,
	RunEntriesDispatchFailedV1,
	TaskStatusUpdatedV1,
	TaskExecutionRecordedV1,
	NodeUpdatedV1,
	TriggerRerunV1,
	TriggerRebaseV1,
	TriggerSingleNodeRunV1,
	ReleaseSeedsPendingV1,
	TriggerPromotedSeedsV1,
	RunFinalizedV1,
	QueryModelV1,
	RetryTaskV1,
	NodeDeployedV1,
	CheckK8sV1,
	TaskFailedV1,
	OutboxDeadLetterV1,
	ScheduleCancelledV1,
	ReleaseRequestedV1,
	ManifestLoadedCandidateV1,
	ValidationRequestedV1,
	ValidationNodeCompletedV1,
	ValidationResultV1,
	SeedBuildRequestedV1,
	SeedBuildNodeCompletedV1,
	SeedBuildCompletedV1,
	CompileRequestedV1,
	CompileNodeCompletedV1,
	CompileCompletedV1,
	ReleasePromotedV1,
	ReleaseRejectedV1,
	PipelineRunFinishedV1,
	RemediationRetryRequestedV1,
	RemediationRequestedV2,
	RemediationProposedV1,
	RemediationPrOpenedV1,
	RemediationPrClosedV1,
}
