// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/graph/v1/graph.proto

package graphv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Criticality int32

const (
	Criticality_CRITICALITY_UNSPECIFIED Criticality = 0
	Criticality_CRITICALITY_REGULATORY  Criticality = 1
	Criticality_CRITICALITY_CORE        Criticality = 2
	Criticality_CRITICALITY_SECONDARY   Criticality = 3
)

// Enum value maps for Criticality.
var (
	Criticality_name = map[int32]string{
		0: "CRITICALITY_UNSPECIFIED",
		1: "CRITICALITY_REGULATORY",
		2: "CRITICALITY_CORE",
		3: "CRITICALITY_SECONDARY",
	}
	Criticality_value = map[string]int32{
		"CRITICALITY_UNSPECIFIED": 0,
		"CRITICALITY_REGULATORY":  1,
		"CRITICALITY_CORE":        2,
		"CRITICALITY_SECONDARY":   3,
	}
)

func (x Criticality) Enum() *Criticality {
	p := new(Criticality)
	*p = x
	return p
}

func (x Criticality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Criticality) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_graph_v1_graph_proto_enumTypes[0].Descriptor()
}

func (Criticality) Type() protoreflect.EnumType {
	return &file_proto_graph_v1_graph_proto_enumTypes[0]
}

func (x Criticality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Criticality.Descriptor instead.
func (Criticality) EnumDescriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{0}
}

type TableNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	SchemaName    string                 `protobuf:"bytes,2,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Owner         string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	ScheduleName  string                 `protobuf:"bytes,5,opt,name=schedule_name,json=scheduleName,proto3" json:"schedule_name,omitempty"`
	Criticality   Criticality            `protobuf:"varint,6,opt,name=criticality,proto3,enum=graph.v1.Criticality" json:"criticality,omitempty"`
	LastUpdatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_updated_at,json=lastUpdatedAt,proto3" json:"last_updated_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	NodeType      string                 `protobuf:"bytes,9,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"` // dbt-model | dbt-seed | dbt-snapshot
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`                    // runtime graph status: PENDING, RUNNING, SUCCEEDED, FAILED, or empty
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableNode) Reset() {
	*x = TableNode{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableNode) ProtoMessage() {}

func (x *TableNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableNode.ProtoReflect.Descriptor instead.
func (*TableNode) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{0}
}

func (x *TableNode) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *TableNode) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *TableNode) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *TableNode) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *TableNode) GetScheduleName() string {
	if x != nil {
		return x.ScheduleName
	}
	return ""
}

func (x *TableNode) GetCriticality() Criticality {
	if x != nil {
		return x.Criticality
	}
	return Criticality_CRITICALITY_UNSPECIFIED
}

func (x *TableNode) GetLastUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdatedAt
	}
	return nil
}

func (x *TableNode) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TableNode) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *TableNode) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Dependency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *TableNode             `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Depth         int32                  `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"` // Distance from the starting node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dependency) Reset() {
	*x = Dependency{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dependency) ProtoMessage() {}

func (x *Dependency) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dependency.ProtoReflect.Descriptor instead.
func (*Dependency) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{1}
}

func (x *Dependency) GetNode() *TableNode {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *Dependency) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

type CreateNodeRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	TableName    string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`               // Required
	SchemaName   string                 `protobuf:"bytes,2,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`            // Required
	ServiceName  string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`         // Required
	Owner        string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`                                        // Required
	ScheduleName string                 `protobuf:"bytes,5,opt,name=schedule_name,json=scheduleName,proto3" json:"schedule_name,omitempty"`      // Required
	Criticality  Criticality            `protobuf:"varint,6,opt,name=criticality,proto3,enum=graph.v1.Criticality" json:"criticality,omitempty"` // Required
	// Optional: upstream dependencies (creates DEPENDS_ON relationships)
	UpstreamDependencies []*UpstreamDependency `protobuf:"bytes,7,rep,name=upstream_dependencies,json=upstreamDependencies,proto3" json:"upstream_dependencies,omitempty"`
	NodeType             string                `protobuf:"bytes,8,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`                      // dbt-model | dbt-seed | dbt-snapshot
	ManifestVersion      string                `protobuf:"bytes,9,opt,name=manifest_version,json=manifestVersion,proto3" json:"manifest_version,omitempty"` // e.g. "v3" — set by manifest-controller at load time
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateNodeRequest) Reset() {
	*x = CreateNodeRequest{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeRequest) ProtoMessage() {}

func (x *CreateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeRequest.ProtoReflect.Descriptor instead.
func (*CreateNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{2}
}

func (x *CreateNodeRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *CreateNodeRequest) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *CreateNodeRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *CreateNodeRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *CreateNodeRequest) GetScheduleName() string {
	if x != nil {
		return x.ScheduleName
	}
	return ""
}

func (x *CreateNodeRequest) GetCriticality() Criticality {
	if x != nil {
		return x.Criticality
	}
	return Criticality_CRITICALITY_UNSPECIFIED
}

func (x *CreateNodeRequest) GetUpstreamDependencies() []*UpstreamDependency {
	if x != nil {
		return x.UpstreamDependencies
	}
	return nil
}

func (x *CreateNodeRequest) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *CreateNodeRequest) GetManifestVersion() string {
	if x != nil {
		return x.ManifestVersion
	}
	return ""
}

type UpstreamDependency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	SchemaName    string                 `protobuf:"bytes,2,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpstreamDependency) Reset() {
	*x = UpstreamDependency{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamDependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamDependency) ProtoMessage() {}

func (x *UpstreamDependency) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamDependency.ProtoReflect.Descriptor instead.
func (*UpstreamDependency) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{3}
}

func (x *UpstreamDependency) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *UpstreamDependency) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *UpstreamDependency) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type NodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *TableNode             `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeResponse) Reset() {
	*x = NodeResponse{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeResponse) ProtoMessage() {}

func (x *NodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeResponse.ProtoReflect.Descriptor instead.
func (*NodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{4}
}

func (x *NodeResponse) GetNode() *TableNode {
	if x != nil {
		return x.Node
	}
	return nil
}

type UpdateNodeTimestampRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`    // Required
	SchemaName    string                 `protobuf:"bytes,2,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"` // Required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNodeTimestampRequest) Reset() {
	*x = UpdateNodeTimestampRequest{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeTimestampRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeTimestampRequest) ProtoMessage() {}

func (x *UpdateNodeTimestampRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeTimestampRequest.ProtoReflect.Descriptor instead.
func (*UpdateNodeTimestampRequest) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateNodeTimestampRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *UpdateNodeTimestampRequest) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

type GetStaleRootNodesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HoursThreshold int32                  `protobuf:"varint,1,opt,name=hours_threshold,json=hoursThreshold,proto3" json:"hours_threshold,omitempty"` // Required: nodes not updated in last N hours
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetStaleRootNodesRequest) Reset() {
	*x = GetStaleRootNodesRequest{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStaleRootNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStaleRootNodesRequest) ProtoMessage() {}

func (x *GetStaleRootNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStaleRootNodesRequest.ProtoReflect.Descriptor instead.
func (*GetStaleRootNodesRequest) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{6}
}

func (x *GetStaleRootNodesRequest) GetHoursThreshold() int32 {
	if x != nil {
		return x.HoursThreshold
	}
	return 0
}

type GetStaleRootNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*TableNode           `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStaleRootNodesResponse) Reset() {
	*x = GetStaleRootNodesResponse{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStaleRootNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStaleRootNodesResponse) ProtoMessage() {}

func (x *GetStaleRootNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStaleRootNodesResponse.ProtoReflect.Descriptor instead.
func (*GetStaleRootNodesResponse) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{7}
}

func (x *GetStaleRootNodesResponse) GetNodes() []*TableNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type GetDownstreamDependenciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleName  string                 `protobuf:"bytes,1,opt,name=schedule_name,json=scheduleName,proto3" json:"schedule_name,omitempty"` // Required
	TableName     string                 `protobuf:"bytes,2,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`          // Required
	SchemaName    string                 `protobuf:"bytes,3,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`       // Required
	MaxDepth      int32                  `protobuf:"varint,4,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`            // Optional: limit traversal depth (0 = unlimited)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownstreamDependenciesRequest) Reset() {
	*x = GetDownstreamDependenciesRequest{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownstreamDependenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownstreamDependenciesRequest) ProtoMessage() {}

func (x *GetDownstreamDependenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownstreamDependenciesRequest.ProtoReflect.Descriptor instead.
func (*GetDownstreamDependenciesRequest) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{8}
}

func (x *GetDownstreamDependenciesRequest) GetScheduleName() string {
	if x != nil {
		return x.ScheduleName
	}
	return ""
}

func (x *GetDownstreamDependenciesRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *GetDownstreamDependenciesRequest) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *GetDownstreamDependenciesRequest) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

type GetDownstreamDependenciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dependencies  []*Dependency          `protobuf:"bytes,1,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownstreamDependenciesResponse) Reset() {
	*x = GetDownstreamDependenciesResponse{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownstreamDependenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownstreamDependenciesResponse) ProtoMessage() {}

func (x *GetDownstreamDependenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownstreamDependenciesResponse.ProtoReflect.Descriptor instead.
func (*GetDownstreamDependenciesResponse) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{9}
}

func (x *GetDownstreamDependenciesResponse) GetDependencies() []*Dependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *GetDownstreamDependenciesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CheckUpstreamFreshnessRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TableName        string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`                       // Required
	SchemaName       string                 `protobuf:"bytes,2,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`                    // Required
	FreshnessMinutes int32                  `protobuf:"varint,3,opt,name=freshness_minutes,json=freshnessMinutes,proto3" json:"freshness_minutes,omitempty"` // Optional: default 30 minutes
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckUpstreamFreshnessRequest) Reset() {
	*x = CheckUpstreamFreshnessRequest{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUpstreamFreshnessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUpstreamFreshnessRequest) ProtoMessage() {}

func (x *CheckUpstreamFreshnessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUpstreamFreshnessRequest.ProtoReflect.Descriptor instead.
func (*CheckUpstreamFreshnessRequest) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{10}
}

func (x *CheckUpstreamFreshnessRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *CheckUpstreamFreshnessRequest) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *CheckUpstreamFreshnessRequest) GetFreshnessMinutes() int32 {
	if x != nil {
		return x.FreshnessMinutes
	}
	return 0
}

type CheckUpstreamFreshnessResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AllFresh       bool                   `protobuf:"varint,1,opt,name=all_fresh,json=allFresh,proto3" json:"all_fresh,omitempty"`
	FreshCount     int32                  `protobuf:"varint,2,opt,name=fresh_count,json=freshCount,proto3" json:"fresh_count,omitempty"`
	TotalCount     int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	StaleUpstreams []*StaleUpstream       `protobuf:"bytes,4,rep,name=stale_upstreams,json=staleUpstreams,proto3" json:"stale_upstreams,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckUpstreamFreshnessResponse) Reset() {
	*x = CheckUpstreamFreshnessResponse{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUpstreamFreshnessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUpstreamFreshnessResponse) ProtoMessage() {}

func (x *CheckUpstreamFreshnessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUpstreamFreshnessResponse.ProtoReflect.Descriptor instead.
func (*CheckUpstreamFreshnessResponse) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{11}
}

func (x *CheckUpstreamFreshnessResponse) GetAllFresh() bool {
	if x != nil {
		return x.AllFresh
	}
	return false
}

func (x *CheckUpstreamFreshnessResponse) GetFreshCount() int32 {
	if x != nil {
		return x.FreshCount
	}
	return 0
}

func (x *CheckUpstreamFreshnessResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *CheckUpstreamFreshnessResponse) GetStaleUpstreams() []*StaleUpstream {
	if x != nil {
		return x.StaleUpstreams
	}
	return nil
}

type StaleUpstream struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Node               *TableNode             `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	MinutesSinceUpdate int32                  `protobuf:"varint,2,opt,name=minutes_since_update,json=minutesSinceUpdate,proto3" json:"minutes_since_update,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StaleUpstream) Reset() {
	*x = StaleUpstream{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaleUpstream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaleUpstream) ProtoMessage() {}

func (x *StaleUpstream) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaleUpstream.ProtoReflect.Descriptor instead.
func (*StaleUpstream) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{12}
}

func (x *StaleUpstream) GetNode() *TableNode {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *StaleUpstream) GetMinutesSinceUpdate() int32 {
	if x != nil {
		return x.MinutesSinceUpdate
	}
	return 0
}

type GetScheduleGraphRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleName  string                 `protobuf:"bytes,1,opt,name=schedule_name,json=scheduleName,proto3" json:"schedule_name,omitempty"` // Required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduleGraphRequest) Reset() {
	*x = GetScheduleGraphRequest{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduleGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduleGraphRequest) ProtoMessage() {}

func (x *GetScheduleGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduleGraphRequest.ProtoReflect.Descriptor instead.
func (*GetScheduleGraphRequest) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{13}
}

func (x *GetScheduleGraphRequest) GetScheduleName() string {
	if x != nil {
		return x.ScheduleName
	}
	return ""
}

type GraphEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNodeId    string                 `protobuf:"bytes,1,opt,name=from_node_id,json=fromNodeId,proto3" json:"from_node_id,omitempty"` // "{service_name}.{schema_name}.{table_name}"
	ToNodeId      string                 `protobuf:"bytes,2,opt,name=to_node_id,json=toNodeId,proto3" json:"to_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphEdge) Reset() {
	*x = GraphEdge{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphEdge) ProtoMessage() {}

func (x *GraphEdge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphEdge.ProtoReflect.Descriptor instead.
func (*GraphEdge) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{14}
}

func (x *GraphEdge) GetFromNodeId() string {
	if x != nil {
		return x.FromNodeId
	}
	return ""
}

func (x *GraphEdge) GetToNodeId() string {
	if x != nil {
		return x.ToNodeId
	}
	return ""
}

type GetScheduleGraphResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*TableNode           `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*GraphEdge           `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduleGraphResponse) Reset() {
	*x = GetScheduleGraphResponse{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduleGraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduleGraphResponse) ProtoMessage() {}

func (x *GetScheduleGraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduleGraphResponse.ProtoReflect.Descriptor instead.
func (*GetScheduleGraphResponse) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{15}
}

func (x *GetScheduleGraphResponse) GetNodes() []*TableNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GetScheduleGraphResponse) GetEdges() []*GraphEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type GetScheduleInitNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleName  string                 `protobuf:"bytes,1,opt,name=schedule_name,json=scheduleName,proto3" json:"schedule_name,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduleInitNodesRequest) Reset() {
	*x = GetScheduleInitNodesRequest{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduleInitNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduleInitNodesRequest) ProtoMessage() {}

func (x *GetScheduleInitNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduleInitNodesRequest.ProtoReflect.Descriptor instead.
func (*GetScheduleInitNodesRequest) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{16}
}

func (x *GetScheduleInitNodesRequest) GetScheduleName() string {
	if x != nil {
		return x.ScheduleName
	}
	return ""
}

func (x *GetScheduleInitNodesRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type GetScheduleInitNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AllNodes      []*TableNode           `protobuf:"bytes,1,rep,name=all_nodes,json=allNodes,proto3" json:"all_nodes,omitempty"`
	RootNodes     []*TableNode           `protobuf:"bytes,2,rep,name=root_nodes,json=rootNodes,proto3" json:"root_nodes,omitempty"`
	SeedNodes     []*TableNode           `protobuf:"bytes,3,rep,name=seed_nodes,json=seedNodes,proto3" json:"seed_nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduleInitNodesResponse) Reset() {
	*x = GetScheduleInitNodesResponse{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduleInitNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduleInitNodesResponse) ProtoMessage() {}

func (x *GetScheduleInitNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduleInitNodesResponse.ProtoReflect.Descriptor instead.
func (*GetScheduleInitNodesResponse) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{17}
}

func (x *GetScheduleInitNodesResponse) GetAllNodes() []*TableNode {
	if x != nil {
		return x.AllNodes
	}
	return nil
}

func (x *GetScheduleInitNodesResponse) GetRootNodes() []*TableNode {
	if x != nil {
		return x.RootNodes
	}
	return nil
}

func (x *GetScheduleInitNodesResponse) GetSeedNodes() []*TableNode {
	if x != nil {
		return x.SeedNodes
	}
	return nil
}

type UpdateNodeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleName  string                 `protobuf:"bytes,1,opt,name=schedule_name,json=scheduleName,proto3" json:"schedule_name,omitempty"`
	SchemaName    string                 `protobuf:"bytes,2,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	TableName     string                 `protobuf:"bytes,3,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // PENDING | RUNNING | SUCCEEDED | FAILED
	RunId         string                 `protobuf:"bytes,5,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNodeStatusRequest) Reset() {
	*x = UpdateNodeStatusRequest{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeStatusRequest) ProtoMessage() {}

func (x *UpdateNodeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateNodeStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateNodeStatusRequest) GetScheduleName() string {
	if x != nil {
		return x.ScheduleName
	}
	return ""
}

func (x *UpdateNodeStatusRequest) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *UpdateNodeStatusRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *UpdateNodeStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateNodeStatusRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type UpdateNodeStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNodeStatusResponse) Reset() {
	*x = UpdateNodeStatusResponse{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeStatusResponse) ProtoMessage() {}

func (x *UpdateNodeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateNodeStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{19}
}

type GetReadyDownstreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleName  string                 `protobuf:"bytes,1,opt,name=schedule_name,json=scheduleName,proto3" json:"schedule_name,omitempty"`
	SchemaName    string                 `protobuf:"bytes,2,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	TableName     string                 `protobuf:"bytes,3,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	RunId         string                 `protobuf:"bytes,4,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReadyDownstreamRequest) Reset() {
	*x = GetReadyDownstreamRequest{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReadyDownstreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadyDownstreamRequest) ProtoMessage() {}

func (x *GetReadyDownstreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadyDownstreamRequest.ProtoReflect.Descriptor instead.
func (*GetReadyDownstreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{20}
}

func (x *GetReadyDownstreamRequest) GetScheduleName() string {
	if x != nil {
		return x.ScheduleName
	}
	return ""
}

func (x *GetReadyDownstreamRequest) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *GetReadyDownstreamRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *GetReadyDownstreamRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type GetReadyDownstreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*TableNode           `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReadyDownstreamResponse) Reset() {
	*x = GetReadyDownstreamResponse{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReadyDownstreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadyDownstreamResponse) ProtoMessage() {}

func (x *GetReadyDownstreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadyDownstreamResponse.ProtoReflect.Descriptor instead.
func (*GetReadyDownstreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{21}
}

func (x *GetReadyDownstreamResponse) GetNodes() []*TableNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type CheckScheduleCompletionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleName  string                 `protobuf:"bytes,1,opt,name=schedule_name,json=scheduleName,proto3" json:"schedule_name,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckScheduleCompletionRequest) Reset() {
	*x = CheckScheduleCompletionRequest{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckScheduleCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckScheduleCompletionRequest) ProtoMessage() {}

func (x *CheckScheduleCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckScheduleCompletionRequest.ProtoReflect.Descriptor instead.
func (*CheckScheduleCompletionRequest) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{22}
}

func (x *CheckScheduleCompletionRequest) GetScheduleName() string {
	if x != nil {
		return x.ScheduleName
	}
	return ""
}

func (x *CheckScheduleCompletionRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type CheckScheduleCompletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsComplete    bool                   `protobuf:"varint,1,opt,name=is_complete,json=isComplete,proto3" json:"is_complete,omitempty"`
	HasFailed     bool                   `protobuf:"varint,2,opt,name=has_failed,json=hasFailed,proto3" json:"has_failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckScheduleCompletionResponse) Reset() {
	*x = CheckScheduleCompletionResponse{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckScheduleCompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckScheduleCompletionResponse) ProtoMessage() {}

func (x *CheckScheduleCompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckScheduleCompletionResponse.ProtoReflect.Descriptor instead.
func (*CheckScheduleCompletionResponse) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{23}
}

func (x *CheckScheduleCompletionResponse) GetIsComplete() bool {
	if x != nil {
		return x.IsComplete
	}
	return false
}

func (x *CheckScheduleCompletionResponse) GetHasFailed() bool {
	if x != nil {
		return x.HasFailed
	}
	return false
}

type GetTransitiveDownstreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleName  string                 `protobuf:"bytes,1,opt,name=schedule_name,json=scheduleName,proto3" json:"schedule_name,omitempty"`
	SchemaName    string                 `protobuf:"bytes,2,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	TableName     string                 `protobuf:"bytes,3,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransitiveDownstreamRequest) Reset() {
	*x = GetTransitiveDownstreamRequest{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransitiveDownstreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransitiveDownstreamRequest) ProtoMessage() {}

func (x *GetTransitiveDownstreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransitiveDownstreamRequest.ProtoReflect.Descriptor instead.
func (*GetTransitiveDownstreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{24}
}

func (x *GetTransitiveDownstreamRequest) GetScheduleName() string {
	if x != nil {
		return x.ScheduleName
	}
	return ""
}

func (x *GetTransitiveDownstreamRequest) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *GetTransitiveDownstreamRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

type GetTransitiveDownstreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*TableNode           `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransitiveDownstreamResponse) Reset() {
	*x = GetTransitiveDownstreamResponse{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransitiveDownstreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransitiveDownstreamResponse) ProtoMessage() {}

func (x *GetTransitiveDownstreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransitiveDownstreamResponse.ProtoReflect.Descriptor instead.
func (*GetTransitiveDownstreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{25}
}

func (x *GetTransitiveDownstreamResponse) GetNodes() []*TableNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type SnapshotGraphRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"` // scheduler_tracker.schedule_id
	ScheduleName  string                 `protobuf:"bytes,2,opt,name=schedule_name,json=scheduleName,proto3" json:"schedule_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotGraphRequest) Reset() {
	*x = SnapshotGraphRequest{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotGraphRequest) ProtoMessage() {}

func (x *SnapshotGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotGraphRequest.ProtoReflect.Descriptor instead.
func (*SnapshotGraphRequest) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{26}
}

func (x *SnapshotGraphRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *SnapshotGraphRequest) GetScheduleName() string {
	if x != nil {
		return x.ScheduleName
	}
	return ""
}

type SnapshotGraphResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotGraphResponse) Reset() {
	*x = SnapshotGraphResponse{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotGraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotGraphResponse) ProtoMessage() {}

func (x *SnapshotGraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotGraphResponse.ProtoReflect.Descriptor instead.
func (*SnapshotGraphResponse) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{27}
}

type FinalizeRunRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RunId          string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TerminalStatus string                 `protobuf:"bytes,2,opt,name=terminal_status,json=terminalStatus,proto3" json:"terminal_status,omitempty"` // "SUCCEEDED" | "FAILED"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FinalizeRunRequest) Reset() {
	*x = FinalizeRunRequest{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeRunRequest) ProtoMessage() {}

func (x *FinalizeRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeRunRequest.ProtoReflect.Descriptor instead.
func (*FinalizeRunRequest) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{28}
}

func (x *FinalizeRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *FinalizeRunRequest) GetTerminalStatus() string {
	if x != nil {
		return x.TerminalStatus
	}
	return ""
}

type FinalizeRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeRunResponse) Reset() {
	*x = FinalizeRunResponse{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeRunResponse) ProtoMessage() {}

func (x *FinalizeRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeRunResponse.ProtoReflect.Descriptor instead.
func (*FinalizeRunResponse) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{29}
}

type ListRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleName  string                 `protobuf:"bytes,1,opt,name=schedule_name,json=scheduleName,proto3" json:"schedule_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsRequest) Reset() {
	*x = ListRunsRequest{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsRequest) ProtoMessage() {}

func (x *ListRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsRequest.ProtoReflect.Descriptor instead.
func (*ListRunsRequest) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{30}
}

func (x *ListRunsRequest) GetScheduleName() string {
	if x != nil {
		return x.ScheduleName
	}
	return ""
}

type RunSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RunId          string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ScheduleName   string                 `protobuf:"bytes,2,opt,name=schedule_name,json=scheduleName,proto3" json:"schedule_name,omitempty"`
	TerminalStatus string                 `protobuf:"bytes,3,opt,name=terminal_status,json=terminalStatus,proto3" json:"terminal_status,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt    string                 `protobuf:"bytes,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RunSummary) Reset() {
	*x = RunSummary{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSummary) ProtoMessage() {}

func (x *RunSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSummary.ProtoReflect.Descriptor instead.
func (*RunSummary) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{31}
}

func (x *RunSummary) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunSummary) GetScheduleName() string {
	if x != nil {
		return x.ScheduleName
	}
	return ""
}

func (x *RunSummary) GetTerminalStatus() string {
	if x != nil {
		return x.TerminalStatus
	}
	return ""
}

func (x *RunSummary) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RunSummary) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

type ListRunsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runs          []*RunSummary          `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsResponse) Reset() {
	*x = ListRunsResponse{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsResponse) ProtoMessage() {}

func (x *ListRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsResponse.ProtoReflect.Descriptor instead.
func (*ListRunsResponse) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{32}
}

func (x *ListRunsResponse) GetRuns() []*RunSummary {
	if x != nil {
		return x.Runs
	}
	return nil
}

type GetRunGraphRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunGraphRequest) Reset() {
	*x = GetRunGraphRequest{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunGraphRequest) ProtoMessage() {}

func (x *GetRunGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunGraphRequest.ProtoReflect.Descriptor instead.
func (*GetRunGraphRequest) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{33}
}

func (x *GetRunGraphRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type GetRunGraphResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*TableNode           `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*GraphEdge           `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunGraphResponse) Reset() {
	*x = GetRunGraphResponse{}
	mi := &file_proto_graph_v1_graph_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunGraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunGraphResponse) ProtoMessage() {}

func (x *GetRunGraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_v1_graph_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunGraphResponse.ProtoReflect.Descriptor instead.
func (*GetRunGraphResponse) Descriptor() ([]byte, []int) {
	return file_proto_graph_v1_graph_proto_rawDescGZIP(), []int{34}
}

func (x *GetRunGraphResponse) GetNodes() []*TableNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GetRunGraphResponse) GetEdges() []*GraphEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

var File_proto_graph_v1_graph_proto protoreflect.FileDescriptor

const file_proto_graph_v1_graph_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/graph/v1/graph.proto\x12\bgraph.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x96\x03\n" +
	"\tTableNode\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x1f\n" +
	"\vschema_name\x18\x02 \x01(\tR\n" +
	"schemaName\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12#\n" +
	"\rschedule_name\x18\x05 \x01(\tR\fscheduleName\x127\n" +
	"\vcriticality\x18\x06 \x01(\x0e2\x15.graph.v1.CriticalityR\vcriticality\x12B\n" +
	"\x0flast_updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\rlastUpdatedAt\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1b\n" +
	"\tnode_type\x18\t \x01(\tR\bnodeType\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\"K\n" +
	"\n" +
	"Dependency\x12'\n" +
	"\x04node\x18\x01 \x01(\v2\x13.graph.v1.TableNodeR\x04node\x12\x14\n" +
	"\x05depth\x18\x02 \x01(\x05R\x05depth\"\x85\x03\n" +
	"\x11CreateNodeRequest\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x1f\n" +
	"\vschema_name\x18\x02 \x01(\tR\n" +
	"schemaName\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12#\n" +
	"\rschedule_name\x18\x05 \x01(\tR\fscheduleName\x127\n" +
	"\vcriticality\x18\x06 \x01(\x0e2\x15.graph.v1.CriticalityR\vcriticality\x12Q\n" +
	"\x15upstream_dependencies\x18\a \x03(\v2\x1c.graph.v1.UpstreamDependencyR\x14upstreamDependencies\x12\x1b\n" +
	"\tnode_type\x18\b \x01(\tR\bnodeType\x12)\n" +
	"\x10manifest_version\x18\t \x01(\tR\x0fmanifestVersion\"w\n" +
	"\x12UpstreamDependency\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x1f\n" +
	"\vschema_name\x18\x02 \x01(\tR\n" +
	"schemaName\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\"7\n" +
	"\fNodeResponse\x12'\n" +
	"\x04node\x18\x01 \x01(\v2\x13.graph.v1.TableNodeR\x04node\"\\\n" +
	"\x1aUpdateNodeTimestampRequest\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x1f\n" +
	"\vschema_name\x18\x02 \x01(\tR\n" +
	"schemaName\"C\n" +
	"\x18GetStaleRootNodesRequest\x12'\n" +
	"\x0fhours_threshold\x18\x01 \x01(\x05R\x0ehoursThreshold\"F\n" +
	"\x19GetStaleRootNodesResponse\x12)\n" +
	"\x05nodes\x18\x01 \x03(\v2\x13.graph.v1.TableNodeR\x05nodes\"\xa4\x01\n" +
	" GetDownstreamDependenciesRequest\x12#\n" +
	"\rschedule_name\x18\x01 \x01(\tR\fscheduleName\x12\x1d\n" +
	"\n" +
	"table_name\x18\x02 \x01(\tR\ttableName\x12\x1f\n" +
	"\vschema_name\x18\x03 \x01(\tR\n" +
	"schemaName\x12\x1b\n" +
	"\tmax_depth\x18\x04 \x01(\x05R\bmaxDepth\"~\n" +
	"!GetDownstreamDependenciesResponse\x128\n" +
	"\fdependencies\x18\x01 \x03(\v2\x14.graph.v1.DependencyR\fdependencies\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x8c\x01\n" +
	"\x1dCheckUpstreamFreshnessRequest\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x1f\n" +
	"\vschema_name\x18\x02 \x01(\tR\n" +
	"schemaName\x12+\n" +
	"\x11freshness_minutes\x18\x03 \x01(\x05R\x10freshnessMinutes\"\xc1\x01\n" +
	"\x1eCheckUpstreamFreshnessResponse\x12\x1b\n" +
	"\tall_fresh\x18\x01 \x01(\bR\ballFresh\x12\x1f\n" +
	"\vfresh_count\x18\x02 \x01(\x05R\n" +
	"freshCount\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x12@\n" +
	"\x0fstale_upstreams\x18\x04 \x03(\v2\x17.graph.v1.StaleUpstreamR\x0estaleUpstreams\"j\n" +
	"\rStaleUpstream\x12'\n" +
	"\x04node\x18\x01 \x01(\v2\x13.graph.v1.TableNodeR\x04node\x120\n" +
	"\x14minutes_since_update\x18\x02 \x01(\x05R\x12minutesSinceUpdate\">\n" +
	"\x17GetScheduleGraphRequest\x12#\n" +
	"\rschedule_name\x18\x01 \x01(\tR\fscheduleName\"K\n" +
	"\tGraphEdge\x12 \n" +
	"\ffrom_node_id\x18\x01 \x01(\tR\n" +
	"fromNodeId\x12\x1c\n" +
	"\n" +
	"to_node_id\x18\x02 \x01(\tR\btoNodeId\"p\n" +
	"\x18GetScheduleGraphResponse\x12)\n" +
	"\x05nodes\x18\x01 \x03(\v2\x13.graph.v1.TableNodeR\x05nodes\x12)\n" +
	"\x05edges\x18\x02 \x03(\v2\x13.graph.v1.GraphEdgeR\x05edges\"Y\n" +
	"\x1bGetScheduleInitNodesRequest\x12#\n" +
	"\rschedule_name\x18\x01 \x01(\tR\fscheduleName\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\"\xb8\x01\n" +
	"\x1cGetScheduleInitNodesResponse\x120\n" +
	"\tall_nodes\x18\x01 \x03(\v2\x13.graph.v1.TableNodeR\ballNodes\x122\n" +
	"\n" +
	"root_nodes\x18\x02 \x03(\v2\x13.graph.v1.TableNodeR\trootNodes\x122\n" +
	"\n" +
	"seed_nodes\x18\x03 \x03(\v2\x13.graph.v1.TableNodeR\tseedNodes\"\xad\x01\n" +
	"\x17UpdateNodeStatusRequest\x12#\n" +
	"\rschedule_name\x18\x01 \x01(\tR\fscheduleName\x12\x1f\n" +
	"\vschema_name\x18\x02 \x01(\tR\n" +
	"schemaName\x12\x1d\n" +
	"\n" +
	"table_name\x18\x03 \x01(\tR\ttableName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x15\n" +
	"\x06run_id\x18\x05 \x01(\tR\x05runId\"\x1a\n" +
	"\x18UpdateNodeStatusResponse\"\x97\x01\n" +
	"\x19GetReadyDownstreamRequest\x12#\n" +
	"\rschedule_name\x18\x01 \x01(\tR\fscheduleName\x12\x1f\n" +
	"\vschema_name\x18\x02 \x01(\tR\n" +
	"schemaName\x12\x1d\n" +
	"\n" +
	"table_name\x18\x03 \x01(\tR\ttableName\x12\x15\n" +
	"\x06run_id\x18\x04 \x01(\tR\x05runId\"G\n" +
	"\x1aGetReadyDownstreamResponse\x12)\n" +
	"\x05nodes\x18\x01 \x03(\v2\x13.graph.v1.TableNodeR\x05nodes\"\\\n" +
	"\x1eCheckScheduleCompletionRequest\x12#\n" +
	"\rschedule_name\x18\x01 \x01(\tR\fscheduleName\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\"a\n" +
	"\x1fCheckScheduleCompletionResponse\x12\x1f\n" +
	"\vis_complete\x18\x01 \x01(\bR\n" +
	"isComplete\x12\x1d\n" +
	"\n" +
	"has_failed\x18\x02 \x01(\bR\thasFailed\"\x85\x01\n" +
	"\x1eGetTransitiveDownstreamRequest\x12#\n" +
	"\rschedule_name\x18\x01 \x01(\tR\fscheduleName\x12\x1f\n" +
	"\vschema_name\x18\x02 \x01(\tR\n" +
	"schemaName\x12\x1d\n" +
	"\n" +
	"table_name\x18\x03 \x01(\tR\ttableName\"L\n" +
	"\x1fGetTransitiveDownstreamResponse\x12)\n" +
	"\x05nodes\x18\x01 \x03(\v2\x13.graph.v1.TableNodeR\x05nodes\"R\n" +
	"\x14SnapshotGraphRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12#\n" +
	"\rschedule_name\x18\x02 \x01(\tR\fscheduleName\"\x17\n" +
	"\x15SnapshotGraphResponse\"T\n" +
	"\x12FinalizeRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12'\n" +
	"\x0fterminal_status\x18\x02 \x01(\tR\x0eterminalStatus\"\x15\n" +
	"\x13FinalizeRunResponse\"6\n" +
	"\x0fListRunsRequest\x12#\n" +
	"\rschedule_name\x18\x01 \x01(\tR\fscheduleName\"\xb3\x01\n" +
	"\n" +
	"RunSummary\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12#\n" +
	"\rschedule_name\x18\x02 \x01(\tR\fscheduleName\x12'\n" +
	"\x0fterminal_status\x18\x03 \x01(\tR\x0eterminalStatus\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12!\n" +
	"\fcompleted_at\x18\x05 \x01(\tR\vcompletedAt\"<\n" +
	"\x10ListRunsResponse\x12(\n" +
	"\x04runs\x18\x01 \x03(\v2\x14.graph.v1.RunSummaryR\x04runs\"+\n" +
	"\x12GetRunGraphRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"k\n" +
	"\x13GetRunGraphResponse\x12)\n" +
	"\x05nodes\x18\x01 \x03(\v2\x13.graph.v1.TableNodeR\x05nodes\x12)\n" +
	"\x05edges\x18\x02 \x03(\v2\x13.graph.v1.GraphEdgeR\x05edges*w\n" +
	"\vCriticality\x12\x1b\n" +
	"\x17CRITICALITY_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CRITICALITY_REGULATORY\x10\x01\x12\x14\n" +
	"\x10CRITICALITY_CORE\x10\x02\x12\x19\n" +
	"\x15CRITICALITY_SECONDARY\x10\x032\xf2\n" +
	"\n" +
	"\fGraphService\x12A\n" +
	"\n" +
	"CreateNode\x12\x1b.graph.v1.CreateNodeRequest\x1a\x16.graph.v1.NodeResponse\x12S\n" +
	"\x13UpdateNodeTimestamp\x12$.graph.v1.UpdateNodeTimestampRequest\x1a\x16.graph.v1.NodeResponse\x12\\\n" +
	"\x11GetStaleRootNodes\x12\".graph.v1.GetStaleRootNodesRequest\x1a#.graph.v1.GetStaleRootNodesResponse\x12t\n" +
	"\x19GetDownstreamDependencies\x12*.graph.v1.GetDownstreamDependenciesRequest\x1a+.graph.v1.GetDownstreamDependenciesResponse\x12k\n" +
	"\x16CheckUpstreamFreshness\x12'.graph.v1.CheckUpstreamFreshnessRequest\x1a(.graph.v1.CheckUpstreamFreshnessResponse\x12Y\n" +
	"\x10GetScheduleGraph\x12!.graph.v1.GetScheduleGraphRequest\x1a\".graph.v1.GetScheduleGraphResponse\x12e\n" +
	"\x14GetScheduleInitNodes\x12%.graph.v1.GetScheduleInitNodesRequest\x1a&.graph.v1.GetScheduleInitNodesResponse\x12Y\n" +
	"\x10UpdateNodeStatus\x12!.graph.v1.UpdateNodeStatusRequest\x1a\".graph.v1.UpdateNodeStatusResponse\x12_\n" +
	"\x12GetReadyDownstream\x12#.graph.v1.GetReadyDownstreamRequest\x1a$.graph.v1.GetReadyDownstreamResponse\x12n\n" +
	"\x17CheckScheduleCompletion\x12(.graph.v1.CheckScheduleCompletionRequest\x1a).graph.v1.CheckScheduleCompletionResponse\x12P\n" +
	"\rSnapshotGraph\x12\x1e.graph.v1.SnapshotGraphRequest\x1a\x1f.graph.v1.SnapshotGraphResponse\x12J\n" +
	"\vFinalizeRun\x12\x1c.graph.v1.FinalizeRunRequest\x1a\x1d.graph.v1.FinalizeRunResponse\x12A\n" +
	"\bListRuns\x12\x19.graph.v1.ListRunsRequest\x1a\x1a.graph.v1.ListRunsResponse\x12J\n" +
	"\vGetRunGraph\x12\x1c.graph.v1.GetRunGraphRequest\x1a\x1d.graph.v1.GetRunGraphResponse\x12n\n" +
	"\x17GetTransitiveDownstream\x12(.graph.v1.GetTransitiveDownstreamRequest\x1a).graph.v1.GetTransitiveDownstreamResponseB=Z;github.com/carolsimone/continuo/graph/api/graph/v1;graphv1b\x06proto3"

var (
	file_proto_graph_v1_graph_proto_rawDescOnce sync.Once
	file_proto_graph_v1_graph_proto_rawDescData []byte
)

func file_proto_graph_v1_graph_proto_rawDescGZIP() []byte {
	file_proto_graph_v1_graph_proto_rawDescOnce.Do(func() {
		file_proto_graph_v1_graph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_graph_v1_graph_proto_rawDesc), len(file_proto_graph_v1_graph_proto_rawDesc)))
	})
	return file_proto_graph_v1_graph_proto_rawDescData
}

var file_proto_graph_v1_graph_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_graph_v1_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_proto_graph_v1_graph_proto_goTypes = []any{
	(Criticality)(0),                          // 0: graph.v1.Criticality
	(*TableNode)(nil),                         // 1: graph.v1.TableNode
	(*Dependency)(nil),                        // 2: graph.v1.Dependency
	(*CreateNodeRequest)(nil),                 // 3: graph.v1.CreateNodeRequest
	(*UpstreamDependency)(nil),                // 4: graph.v1.UpstreamDependency
	(*NodeResponse)(nil),                      // 5: graph.v1.NodeResponse
	(*UpdateNodeTimestampRequest)(nil),        // 6: graph.v1.UpdateNodeTimestampRequest
	(*GetStaleRootNodesRequest)(nil),          // 7: graph.v1.GetStaleRootNodesRequest
	(*GetStaleRootNodesResponse)(nil),         // 8: graph.v1.GetStaleRootNodesResponse
	(*GetDownstreamDependenciesRequest)(nil),  // 9: graph.v1.GetDownstreamDependenciesRequest
	(*GetDownstreamDependenciesResponse)(nil), // 10: graph.v1.GetDownstreamDependenciesResponse
	(*CheckUpstreamFreshnessRequest)(nil),     // 11: graph.v1.CheckUpstreamFreshnessRequest
	(*CheckUpstreamFreshnessResponse)(nil),    // 12: graph.v1.CheckUpstreamFreshnessResponse
	(*StaleUpstream)(nil),                     // 13: graph.v1.StaleUpstream
	(*GetScheduleGraphRequest)(nil),           // 14: graph.v1.GetScheduleGraphRequest
	(*GraphEdge)(nil),                         // 15: graph.v1.GraphEdge
	(*GetScheduleGraphResponse)(nil),          // 16: graph.v1.GetScheduleGraphResponse
	(*GetScheduleInitNodesRequest)(nil),       // 17: graph.v1.GetScheduleInitNodesRequest
	(*GetScheduleInitNodesResponse)(nil),      // 18: graph.v1.GetScheduleInitNodesResponse
	(*UpdateNodeStatusRequest)(nil),           // 19: graph.v1.UpdateNodeStatusRequest
	(*UpdateNodeStatusResponse)(nil),          // 20: graph.v1.UpdateNodeStatusResponse
	(*GetReadyDownstreamRequest)(nil),         // 21: graph.v1.GetReadyDownstreamRequest
	(*GetReadyDownstreamResponse)(nil),        // 22: graph.v1.GetReadyDownstreamResponse
	(*CheckScheduleCompletionRequest)(nil),    // 23: graph.v1.CheckScheduleCompletionRequest
	(*CheckScheduleCompletionResponse)(nil),   // 24: graph.v1.CheckScheduleCompletionResponse
	(*GetTransitiveDownstreamRequest)(nil),    // 25: graph.v1.GetTransitiveDownstreamRequest
	(*GetTransitiveDownstreamResponse)(nil),   // 26: graph.v1.GetTransitiveDownstreamResponse
	(*SnapshotGraphRequest)(nil),              // 27: graph.v1.SnapshotGraphRequest
	(*SnapshotGraphResponse)(nil),             // 28: graph.v1.SnapshotGraphResponse
	(*FinalizeRunRequest)(nil),                // 29: graph.v1.FinalizeRunRequest
	(*FinalizeRunResponse)(nil),               // 30: graph.v1.FinalizeRunResponse
	(*ListRunsRequest)(nil),                   // 31: graph.v1.ListRunsRequest
	(*RunSummary)(nil),                        // 32: graph.v1.RunSummary
	(*ListRunsResponse)(nil),                  // 33: graph.v1.ListRunsResponse
	(*GetRunGraphRequest)(nil),                // 34: graph.v1.GetRunGraphRequest
	(*GetRunGraphResponse)(nil),               // 35: graph.v1.GetRunGraphResponse
	(*timestamppb.Timestamp)(nil),             // 36: google.protobuf.Timestamp
}
var file_proto_graph_v1_graph_proto_depIdxs = []int32{
	0,  // 0: graph.v1.TableNode.criticality:type_name -> graph.v1.Criticality
	36, // 1: graph.v1.TableNode.last_updated_at:type_name -> google.protobuf.Timestamp
	36, // 2: graph.v1.TableNode.created_at:type_name -> google.protobuf.Timestamp
	1,  // 3: graph.v1.Dependency.node:type_name -> graph.v1.TableNode
	0,  // 4: graph.v1.CreateNodeRequest.criticality:type_name -> graph.v1.Criticality
	4,  // 5: graph.v1.CreateNodeRequest.upstream_dependencies:type_name -> graph.v1.UpstreamDependency
	1,  // 6: graph.v1.NodeResponse.node:type_name -> graph.v1.TableNode
	1,  // 7: graph.v1.GetStaleRootNodesResponse.nodes:type_name -> graph.v1.TableNode
	2,  // 8: graph.v1.GetDownstreamDependenciesResponse.dependencies:type_name -> graph.v1.Dependency
	13, // 9: graph.v1.CheckUpstreamFreshnessResponse.stale_upstreams:type_name -> graph.v1.StaleUpstream
	1,  // 10: graph.v1.StaleUpstream.node:type_name -> graph.v1.TableNode
	1,  // 11: graph.v1.GetScheduleGraphResponse.nodes:type_name -> graph.v1.TableNode
	15, // 12: graph.v1.GetScheduleGraphResponse.edges:type_name -> graph.v1.GraphEdge
	1,  // 13: graph.v1.GetScheduleInitNodesResponse.all_nodes:type_name -> graph.v1.TableNode
	1,  // 14: graph.v1.GetScheduleInitNodesResponse.root_nodes:type_name -> graph.v1.TableNode
	1,  // 15: graph.v1.GetScheduleInitNodesResponse.seed_nodes:type_name -> graph.v1.TableNode
	1,  // 16: graph.v1.GetReadyDownstreamResponse.nodes:type_name -> graph.v1.TableNode
	1,  // 17: graph.v1.GetTransitiveDownstreamResponse.nodes:type_name -> graph.v1.TableNode
	32, // 18: graph.v1.ListRunsResponse.runs:type_name -> graph.v1.RunSummary
	1,  // 19: graph.v1.GetRunGraphResponse.nodes:type_name -> graph.v1.TableNode
	15, // 20: graph.v1.GetRunGraphResponse.edges:type_name -> graph.v1.GraphEdge
	3,  // 21: graph.v1.GraphService.CreateNode:input_type -> graph.v1.CreateNodeRequest
	6,  // 22: graph.v1.GraphService.UpdateNodeTimestamp:input_type -> graph.v1.UpdateNodeTimestampRequest
	7,  // 23: graph.v1.GraphService.GetStaleRootNodes:input_type -> graph.v1.GetStaleRootNodesRequest
	9,  // 24: graph.v1.GraphService.GetDownstreamDependencies:input_type -> graph.v1.GetDownstreamDependenciesRequest
	11, // 25: graph.v1.GraphService.CheckUpstreamFreshness:input_type -> graph.v1.CheckUpstreamFreshnessRequest
	14, // 26: graph.v1.GraphService.GetScheduleGraph:input_type -> graph.v1.GetScheduleGraphRequest
	17, // 27: graph.v1.GraphService.GetScheduleInitNodes:input_type -> graph.v1.GetScheduleInitNodesRequest
	19, // 28: graph.v1.GraphService.UpdateNodeStatus:input_type -> graph.v1.UpdateNodeStatusRequest
	21, // 29: graph.v1.GraphService.GetReadyDownstream:input_type -> graph.v1.GetReadyDownstreamRequest
	23, // 30: graph.v1.GraphService.CheckScheduleCompletion:input_type -> graph.v1.CheckScheduleCompletionRequest
	27, // 31: graph.v1.GraphService.SnapshotGraph:input_type -> graph.v1.SnapshotGraphRequest
	29, // 32: graph.v1.GraphService.FinalizeRun:input_type -> graph.v1.FinalizeRunRequest
	31, // 33: graph.v1.GraphService.ListRuns:input_type -> graph.v1.ListRunsRequest
	34, // 34: graph.v1.GraphService.GetRunGraph:input_type -> graph.v1.GetRunGraphRequest
	25, // 35: graph.v1.GraphService.GetTransitiveDownstream:input_type -> graph.v1.GetTransitiveDownstreamRequest
	5,  // 36: graph.v1.GraphService.CreateNode:output_type -> graph.v1.NodeResponse
	5,  // 37: graph.v1.GraphService.UpdateNodeTimestamp:output_type -> graph.v1.NodeResponse
	8,  // 38: graph.v1.GraphService.GetStaleRootNodes:output_type -> graph.v1.GetStaleRootNodesResponse
	10, // 39: graph.v1.GraphService.GetDownstreamDependencies:output_type -> graph.v1.GetDownstreamDependenciesResponse
	12, // 40: graph.v1.GraphService.CheckUpstreamFreshness:output_type -> graph.v1.CheckUpstreamFreshnessResponse
	16, // 41: graph.v1.GraphService.GetScheduleGraph:output_type -> graph.v1.GetScheduleGraphResponse
	18, // 42: graph.v1.GraphService.GetScheduleInitNodes:output_type -> graph.v1.GetScheduleInitNodesResponse
	20, // 43: graph.v1.GraphService.UpdateNodeStatus:output_type -> graph.v1.UpdateNodeStatusResponse
	22, // 44: graph.v1.GraphService.GetReadyDownstream:output_type -> graph.v1.GetReadyDownstreamResponse
	24, // 45: graph.v1.GraphService.CheckScheduleCompletion:output_type -> graph.v1.CheckScheduleCompletionResponse
	28, // 46: graph.v1.GraphService.SnapshotGraph:output_type -> graph.v1.SnapshotGraphResponse
	30, // 47: graph.v1.GraphService.FinalizeRun:output_type -> graph.v1.FinalizeRunResponse
	33, // 48: graph.v1.GraphService.ListRuns:output_type -> graph.v1.ListRunsResponse
	35, // 49: graph.v1.GraphService.GetRunGraph:output_type -> graph.v1.GetRunGraphResponse
	26, // 50: graph.v1.GraphService.GetTransitiveDownstream:output_type -> graph.v1.GetTransitiveDownstreamResponse
	36, // [36:51] is the sub-list for method output_type
	21, // [21:36] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_proto_graph_v1_graph_proto_init() }
func file_proto_graph_v1_graph_proto_init() {
	if File_proto_graph_v1_graph_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_graph_v1_graph_proto_rawDesc), len(file_proto_graph_v1_graph_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_graph_v1_graph_proto_goTypes,
		DependencyIndexes: file_proto_graph_v1_graph_proto_depIdxs,
		EnumInfos:         file_proto_graph_v1_graph_proto_enumTypes,
		MessageInfos:      file_proto_graph_v1_graph_proto_msgTypes,
	}.Build()
	File_proto_graph_v1_graph_proto = out.File
	file_proto_graph_v1_graph_proto_goTypes = nil
	file_proto_graph_v1_graph_proto_depIdxs = nil
}
