package e2e

import (
	"encoding/json"
	"math"
	"testing"

	"github.com/stretchr/testify/require"
)

// TestContentHash_MatchesKnownVectors pins computeContentHash (and its
// canonicalJSON/nodeSourceHash/sharedCodeHash helpers) against vectors
// generated by running the REAL Python implementation
// (manifest-controller/service/parser.py) against a synthetic manifest.json,
// plus two vectors captured from a real e2e-baseline manifest. This is the
// harness's only defense against silent drift between this Go
// reimplementation and its single source of truth: if parser.py's formula
// ever changes, this test must be regenerated the same way (see the command
// below) or it will fail loudly instead of silently mis-seeding
// current_prod.
//
// Vectors were generated with:
//
//	docker exec -w /app manifest-controller uv run python -c "
//	import json
//	from service.parser import _node_source_hash, _shared_code_hash, _config_hash, _content_hash, _transitive_macro_ids
//	manifest = json.load(open('/tmp/synthetic_manifest.json'))
//	macros = manifest['macros']
//	for node_id, node in manifest['nodes'].items():
//	    direct = node.get('depends_on', {}).get('macros', [])
//	    trans = _transitive_macro_ids(direct, macros)
//	    print(node_id, _content_hash(_node_source_hash(node), _shared_code_hash(trans, macros), _config_hash(node)))
//	"
func TestContentHash_MatchesKnownVectors(t *testing.T) {
	macros := map[string]interface{}{
		"macro.pkg.macro_a": map[string]interface{}{
			"macro_sql": "{% macro macro_a() %}{{ macro_b() }}{% endmacro %}",
			"depends_on": map[string]interface{}{
				"macros": []interface{}{"macro.pkg.macro_b"},
			},
		},
		"macro.pkg.macro_b": map[string]interface{}{
			"macro_sql": "{% macro macro_b() %}select 1{% endmacro %}",
			"depends_on": map[string]interface{}{
				"macros": []interface{}{},
			},
		},
		"macro.pkg.unused": map[string]interface{}{
			"macro_sql":  "{% macro unused() %}noop{% endmacro %}",
			"depends_on": map[string]interface{}{"macros": []interface{}{}},
		},
	}

	t.Run("node with a transitive macro closure and denylisted+unicode config", func(t *testing.T) {
		// Mirrors synthetic_manifest.json's "model.pkg.with_macro": a node
		// whose single direct macro dependency (macro_a) transitively pulls
		// in macro_b, and whose config carries denylisted keys (meta, tags,
		// docs, grants, description) alongside a unicode string that must be
		// \u-escaped exactly as Python's ensure_ascii=True does.
		n := map[string]interface{}{
			"resource_type": "model",
			"schema":        "e2e_schema",
			"name":          "with_macro",
			"checksum": map[string]interface{}{
				"name": "sha256", "checksum": "aaaa111122223333",
			},
			"depends_on": map[string]interface{}{
				"macros": []interface{}{"macro.pkg.macro_a"},
			},
			"config": map[string]interface{}{
				"materialized":  "table",
				"meta":          map[string]interface{}{"owner": "test"},
				"tags":          []interface{}{"x"},
				"docs":          map[string]interface{}{"show": true},
				"grants":        map[string]interface{}{},
				"description":   "should be dropped",
				"unicode_field": "café ☃ 😀",
			},
			"raw_code":      "select 1",
			"compiled_code": "select 1",
		}

		require.Equal(t, "aaaa111122223333", nodeSourceHash(n), "source_hash: dbt checksum passes through verbatim")

		direct := macroIDs(n["depends_on"])
		transitive := transitiveMacroIDs(direct, macros)
		require.Equal(t, map[string]bool{"macro.pkg.macro_a": true, "macro.pkg.macro_b": true}, transitive,
			"transitive closure must include macro_a's own dependency macro_b, but not the unreferenced 'unused' macro")

		require.Equal(t, "11e2962a1aec197a5f134aebd6a00d1152ef81e4b73d96ef85787fd250961d37",
			sharedCodeHash(transitive, macros))

		cfg := configForHash(n["config"])
		wantCfgJSON := "{\"materialized\": \"table\", \"unicode_field\": \"caf\\u00e9 \\u2603 \\ud83d\\ude00\"}"
		require.Equal(t, wantCfgJSON,
			canonicalJSON(cfg), "denylisted keys dropped, unicode \\u-escaped exactly like Python's ensure_ascii=True")
		require.Equal(t, "859169e7be47e9f382be31b675aaf3b1c36ffb38965475642c268cc2dff8e9d8", sha256Hex(canonicalJSON(cfg)))

		require.Equal(t, "sha256:01e09f285ff9cb3defa7962be89967b8f10fdeaf2a30175611ec54523d161e7c",
			computeContentHash(n, macros))
	})

	t.Run("node with no checksum, no raw/compiled code — full node-dump fallback", func(t *testing.T) {
		// Mirrors synthetic_manifest.json's "model.pkg.no_macro": exercises
		// _node_source_hash's deepest fallback (a canonical JSON dump of the
		// whole node) when dbt recorded no checksum and the node has neither
		// raw_code nor compiled_code.
		n := map[string]interface{}{
			"resource_type": "model",
			"schema":        "e2e_schema",
			"name":          "no_macro",
			"checksum": map[string]interface{}{
				"name": "sha256", "checksum": "",
			},
			"depends_on":    map[string]interface{}{"macros": []interface{}{}},
			"config":        map[string]interface{}{"materialized": "view"},
			"raw_code":      "",
			"compiled_code": "",
		}

		require.Equal(t, "sha256:1817b48235e2418ab7d323e380dd77b59a655ea21f10b063961906ddbb71b177",
			nodeSourceHash(n), "empty checksum + empty raw/compiled code must fall back to a whole-node JSON dump")

		require.Equal(t, "sha256:b7412be4d2e0216b8e27310f1b9fbcd69ec5cd018ff48a354011cc9a38fd740d",
			computeContentHash(n, macros))
	})

	t.Run("real e2e-baseline vectors (model and seed)", func(t *testing.T) {
		// Captured from s3://continuo/service-1/e2e-baseline/manifest.json by
		// running the real parser.py against it (see
		// tests/e2e/README.md-adjacent task report for the exact command).
		// rel_probe/ftable_a/ftable_b/rel_probe_up share identical raw_code
		// ("SELECT 1") and config, so they share one content_hash — a useful
		// cross-check that the formula is content-addressed, not identity-addressed.
		modelNode := map[string]interface{}{
			"resource_type": "model",
			"schema":        "e2e_schema",
			"name":          "rel_probe",
			"checksum": map[string]interface{}{
				"name": "sha256", "checksum": "c357bf3fb2b0e43719d3b6ff468d4086af606a1ab1160359e030a10135d91253",
			},
			"depends_on": map[string]interface{}{"macros": []interface{}{}},
			"config": map[string]interface{}{
				"enabled": true, "alias": nil, "schema": nil, "database": nil,
				"tags":                    []interface{}{"rel-probe"},
				"meta":                    map[string]interface{}{"owner": "test", "criticality": "CORE"},
				"group":                   nil,
				"static_analysis":         nil,
				"materialized":            "table",
				"incremental_strategy":    nil,
				"batch_size":              nil,
				"lookback":                json.Number("1"),
				"begin":                   nil,
				"persist_docs":            map[string]interface{}{},
				"post-hook":               []interface{}{},
				"pre-hook":                []interface{}{},
				"quoting":                 map[string]interface{}{},
				"column_types":            map[string]interface{}{},
				"full_refresh":            nil,
				"unique_key":              nil,
				"on_schema_change":        "ignore",
				"on_configuration_change": "apply",
				"grants":                  map[string]interface{}{},
				"packages":                []interface{}{},
				"docs":                    map[string]interface{}{"show": true, "node_color": nil},
				"contract":                map[string]interface{}{"enforced": false, "alias_types": true},
				"event_time":              nil,
				"concurrent_batches":      nil,
				"access":                  "protected",
				"freshness":               nil,
				"on_error":                nil,
			},
		}
		require.Equal(t, "sha256:7af21c943e5df1fc35499ce2b35ec63d294bc265dfca902821d21400414c7c0d",
			computeContentHash(modelNode, map[string]interface{}{}))

		seedNode := map[string]interface{}{
			"resource_type": "seed",
			"schema":        "e2e_schema",
			"name":          "seed_table_1",
			"checksum": map[string]interface{}{
				"name": "sha256", "checksum": "605096a310e4908def91488e2d873d6bd9f4a9930bcb42eeac08d6f0ccf3ba0e",
			},
			"depends_on": map[string]interface{}{"macros": []interface{}{}},
			"config": map[string]interface{}{
				"alias": nil, "batch_size": nil, "begin": nil,
				"column_types":            map[string]interface{}{},
				"concurrent_batches":      nil,
				"contract":                map[string]interface{}{"enforced": false, "alias_types": true},
				"database":                nil,
				"delimiter":               ",",
				"enabled":                 true,
				"event_time":              nil,
				"full_refresh":            false,
				"group":                   nil,
				"incremental_strategy":    nil,
				"lookback":                json.Number("1"),
				"materialized":            "seed",
				"on_configuration_change": "apply",
				"on_schema_change":        "ignore",
				"packages":                []interface{}{},
				"persist_docs":            map[string]interface{}{},
				"post-hook":               []interface{}{},
				"pre-hook":                []interface{}{},
				"quote_columns":           nil,
				"quoting":                 map[string]interface{}{},
				"schema":                  nil,
				"static_analysis":         nil,
				"unique_key":              nil,
			},
		}
		require.Equal(t, "sha256:f42ea5fccab40f3245fe21bbbaa0f306d382c493cb2129574bda6a4121046a2a",
			computeContentHash(seedNode, map[string]interface{}{}))
	})

	t.Run("middle source_hash fallback tier: empty checksum, non-empty raw_code", func(t *testing.T) {
		// Mirrors a node dbt did not checksum but that DOES have raw_code —
		// the middle tier of _node_source_hash's fallback chain, between "use
		// dbt's checksum verbatim" and "dump the whole node as JSON".
		// compiled_code is populated too, to prove raw_code wins when both
		// are present (matching `node.get("raw_code") or node.get("compiled_code")`).
		//
		// Generated with:
		//	docker exec -w /app manifest-controller uv run python -c "
		//	import json
		//	from service.parser import _node_source_hash, _shared_code_hash, _config_hash, _content_hash, _transitive_macro_ids
		//	manifest = json.load(open('/tmp/synthetic_manifest2.json'))
		//	for node_id, node in manifest['nodes'].items():
		//	    trans = _transitive_macro_ids(node.get('depends_on', {}).get('macros', []), manifest['macros'])
		//	    print(_content_hash(_node_source_hash(node), _shared_code_hash(trans, manifest['macros']), _config_hash(node)))
		//	"
		// where synthetic_manifest2.json's node config is {"materialized": "view"}.
		n := map[string]interface{}{
			"resource_type": "model",
			"schema":        "e2e_schema",
			"name":          "raw_code_fallback",
			"checksum": map[string]interface{}{
				"name": "sha256", "checksum": "",
			},
			"depends_on":    map[string]interface{}{"macros": []interface{}{}},
			"config":        map[string]interface{}{"materialized": "view"},
			"raw_code":      "select 1 as id",
			"compiled_code": "select 1 as id -- compiled, should not be used",
		}

		require.Equal(t, "sha256:3ea0f972fa1b56aa2dc2f56ee784b6a5796312f9a813d59ae70fd8855f10d16d",
			nodeSourceHash(n), "empty checksum + non-empty raw_code must hash raw_code, not compiled_code")

		require.Equal(t, "sha256:67975814a3fa3704d6c624e5deaaa0f9a2149f1b88210cded975891da64e6132",
			computeContentHash(n, map[string]interface{}{}))
	})

	t.Run("config_hash: DEL escaping and float re-serialization", func(t *testing.T) {
		// Generated with:
		//	docker exec -w /app manifest-controller uv run python -c "
		//	import json, hashlib
		//	CONFIG_HASH_DENYLIST = {'meta', 'docs', 'description', 'grants', 'tags'}
		//	node = {'config': {'materialized': 'table', 'del_field': '\x7f', 'lookback': 2.5, 'batch_size': 25000000000.0}}
		//	cfg = {k: v for k, v in (node.get('config') or {}).items() if k not in CONFIG_HASH_DENYLIST}
		//	s = json.dumps(cfg, sort_keys=True, default=str)
		//	print(repr(s)); print(hashlib.sha256(s.encode()).hexdigest())
		//	"
		// del_field exercises the DEL (0x7F) escape; lookback and batch_size
		// exercise float re-serialization — 2.5 needs no reformatting, but
		// 25000000000.0 is exactly the case where Go's strconv 'g' format
		// diverges from Python's repr (Go: "2.5e+10", Python: "25000000000.0").
		cfg := map[string]interface{}{
			"materialized": "table",
			"del_field":    "\x7f",
			"lookback":     json.Number("2.5"),
			"batch_size":   json.Number("25000000000.0"),
		}
		wantCfgJSON := "{\"batch_size\": 25000000000.0, \"del_field\": \"\\u007f\", \"lookback\": 2.5, \"materialized\": \"table\"}"
		require.Equal(t, wantCfgJSON, canonicalJSON(cfg))
		require.Equal(t, "e8fa4f53da1b542df95f0a8d79073549efabb1db33b17b0dc4f1ce06f0b6dce8", sha256Hex(canonicalJSON(cfg)))
	})
}

// TestFormatPythonFloatRepr pins formatPythonFloatRepr against CPython's
// float repr / json.dumps output (the same underlying dtoa the two share —
// verified with `python3 -c "import json; print(json.dumps(v))"` for every
// value below). Covers both sides of CPython's fixed-vs-exponential
// threshold (decpt <= -4 and decpt > 16), negative numbers, negative zero,
// and values where Go's default strconv 'g' formatting would diverge from
// Python (e.g. 25000000000.0, 1.0, 123456789.123456).
func TestFormatPythonFloatRepr(t *testing.T) {
	cases := []struct {
		f    float64
		want string
	}{
		{1.5, "1.5"},
		{1.0, "1.0"},
		{0.1, "0.1"},
		{100.0, "100.0"},
		{1e17, "1e+17"},
		{1e16, "1e+16"},
		{1e-5, "1e-05"},
		{1e-4, "0.0001"},
		{123456789.123456, "123456789.123456"},
		{-1.5, "-1.5"},
		{0.0, "0.0"},
		{3.14159, "3.14159"},
		{2.5e10, "25000000000.0"},
		{1e21, "1e+21"},
		{1e-10, "1e-10"},
		{9999999999999998.0, "9999999999999998.0"},
		{1234567890123456.0, "1234567890123456.0"},
		{math.Copysign(0, -1), "-0.0"},
	}
	for _, c := range cases {
		require.Equal(t, c.want, formatPythonFloatRepr(c.f), "f=%v", c.f)
	}
}
