package e2e

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

// decodeJSONDoc decodes a JSON document (e.g. a full dbt manifest.json) into
// generic Go values, using json.Number for numbers so integer/float literals
// round-trip exactly instead of collapsing through float64 — required for
// canonicalJSON to reproduce Python's json.dumps output byte-for-byte.
func decodeJSONDoc(body []byte) (map[string]interface{}, error) {
	dec := json.NewDecoder(bytes.NewReader(body))
	dec.UseNumber()
	var doc map[string]interface{}
	if err := dec.Decode(&doc); err != nil {
		return nil, err
	}
	return doc, nil
}

// asObjectMap returns v as map[string]interface{}, or an empty map if v is
// not an object (nil, wrong type, or absent key) — matching how a missing
// dbt manifest section (e.g. no "macros" key) behaves like {}.
func asObjectMap(v interface{}) map[string]interface{} {
	if m, ok := v.(map[string]interface{}); ok {
		return m
	}
	return map[string]interface{}{}
}

// This file reimplements manifest-controller's three-part content_hash
// formula in Go so the e2e harness can seed release-controller's
// current_prod with hashes that match what the LIVE manifest-controller
// computes for the exact same dbt manifest.json content. Without this, a
// content_hash seeded from dbt's raw per-node checksum alone would never
// match the live formula's output, and every candidate node would look
// "changed" against current_prod regardless of whether it actually changed.
//
// Single source of truth: manifest-controller/service/parser.py
// (_node_source_hash, _transitive_macro_ids, _shared_code_hash,
// _config_hash, _content_hash). Any change to that formula must be mirrored
// here, and TestContentHash_MatchesKnownVectors pins known-good vectors
// generated by running the real Python parser so drift is caught.

// contentHashDenylist mirrors parser.py's CONFIG_HASH_DENYLIST: config keys
// that never participate in the config-hash component because they carry no
// change-detection signal (free-text/meta fields).
var contentHashDenylist = map[string]bool{
	"meta": true, "docs": true, "description": true, "grants": true, "tags": true,
}

// computeContentHash recomputes a dbt manifest node's content_hash exactly
// as manifest-controller's parser does: "sha256:" + sha256(source_hash +
// "|" + shared_code_hash + "|" + config_hash). n and macros are the node and
// the manifest's top-level "macros" map, both decoded as generic JSON
// (map[string]interface{}/[]interface{}/json.Number/string/bool/nil — see
// decodeJSONDoc) so nested structure is preserved verbatim for canonical
// re-serialization.
func computeContentHash(n map[string]interface{}, macros map[string]interface{}) string {
	sourceHash := nodeSourceHash(n)
	direct := macroIDs(n["depends_on"])
	transitive := transitiveMacroIDs(direct, macros)
	sharedHash := sharedCodeHash(transitive, macros)
	cfg := configForHash(n["config"])
	configHash := sha256Hex(canonicalJSON(cfg))
	return "sha256:" + sha256Hex(sourceHash+"|"+sharedHash+"|"+configHash)
}

// nodeSourceHash mirrors parser.py's _node_source_hash: prefer dbt's own
// checksum.checksum; if absent, fall back to a deterministic sha256 over the
// node's raw_code/compiled_code, or, failing that, a stable canonical JSON
// dump of the whole node — so the fingerprint is never empty.
func nodeSourceHash(n map[string]interface{}) string {
	if cs, ok := n["checksum"].(map[string]interface{}); ok {
		if v, ok := cs["checksum"].(string); ok && v != "" {
			return v
		}
	}
	basis, _ := n["raw_code"].(string)
	if basis == "" {
		basis, _ = n["compiled_code"].(string)
	}
	if basis == "" {
		basis = canonicalJSON(n)
	}
	return "sha256:" + sha256Hex(basis)
}

// macroIDs extracts a node's (or macro's) direct depends_on.macros list.
func macroIDs(dependsOn interface{}) []string {
	m, ok := dependsOn.(map[string]interface{})
	if !ok {
		return nil
	}
	arr, ok := m["macros"].([]interface{})
	if !ok {
		return nil
	}
	ids := make([]string, 0, len(arr))
	for _, v := range arr {
		if s, ok := v.(string); ok {
			ids = append(ids, s)
		}
	}
	return ids
}

// transitiveMacroIDs mirrors parser.py's _transitive_macro_ids: walks
// macro->macro depends_on edges so a change to a macro reached only through
// another macro still affects the dependent node. IDs absent from the
// manifest's macro map (e.g. unresolved built-ins) stay in the closure but
// contribute no checksum in sharedCodeHash.
func transitiveMacroIDs(direct []string, macros map[string]interface{}) map[string]bool {
	seen := map[string]bool{}
	stack := append([]string{}, direct...)
	for len(stack) > 0 {
		id := stack[len(stack)-1]
		stack = stack[:len(stack)-1]
		if seen[id] {
			continue
		}
		seen[id] = true
		if macro, ok := macros[id].(map[string]interface{}); ok {
			stack = append(stack, macroIDs(macro["depends_on"])...)
		}
	}
	return seen
}

// sharedCodeHash mirrors parser.py's _shared_code_hash: a fold of the sorted
// sha256(macro_sql) hex digests of the given macro-id set; "" if none
// resolve to a known macro (matching Python's empty-string sentinel for "no
// shared code").
func sharedCodeHash(ids map[string]bool, macros map[string]interface{}) string {
	var hashes []string
	for id := range ids {
		macro, ok := macros[id].(map[string]interface{})
		if !ok {
			continue
		}
		sql, _ := macro["macro_sql"].(string)
		hashes = append(hashes, sha256Hex(sql))
	}
	if len(hashes) == 0 {
		return ""
	}
	sort.Strings(hashes)
	return sha256Hex(strings.Join(hashes, ""))
}

// configForHash mirrors parser.py's _config_hash input: the node's resolved
// config with CONFIG_HASH_DENYLIST keys removed. A missing/non-object config
// becomes an empty map, matching Python's `node.get("config") or {}`.
func configForHash(config interface{}) map[string]interface{} {
	cfg, _ := config.(map[string]interface{})
	out := make(map[string]interface{}, len(cfg))
	for k, v := range cfg {
		if contentHashDenylist[k] {
			continue
		}
		out[k] = v
	}
	return out
}

// sha256Hex returns the lowercase hex sha256 digest of s (no prefix),
// matching hashlib.sha256(...).hexdigest().
func sha256Hex(s string) string {
	sum := sha256.Sum256([]byte(s))
	return hex.EncodeToString(sum[:])
}

// canonicalJSON serializes a decoded JSON value the way Python's
// json.dumps(v, sort_keys=True, default=str) does: object keys sorted,
// ", " between elements, ": " between key and value, and non-ASCII
// characters escaped as \uXXXX (ensure_ascii=True, the Python default).
// Go's encoding/json.Marshal matches NONE of this (no key sorting for
// map[string]interface{} beyond Go's own — actually equal for maps, but
// different separators and it emits raw UTF-8 instead of \u-escaping), so a
// byte-identical reimplementation is required to hash-match parser.py.
func canonicalJSON(v interface{}) string {
	var b strings.Builder
	writeCanonicalJSON(&b, v)
	return b.String()
}

func writeCanonicalJSON(b *strings.Builder, v interface{}) {
	switch t := v.(type) {
	case nil:
		b.WriteString("null")
	case bool:
		if t {
			b.WriteString("true")
		} else {
			b.WriteString("false")
		}
	case json.Number:
		b.WriteString(t.String())
	case string:
		writeCanonicalJSONString(b, t)
	case []interface{}:
		b.WriteByte('[')
		for i, e := range t {
			if i > 0 {
				b.WriteString(", ")
			}
			writeCanonicalJSON(b, e)
		}
		b.WriteByte(']')
	case map[string]interface{}:
		keys := make([]string, 0, len(t))
		for k := range t {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		b.WriteByte('{')
		for i, k := range keys {
			if i > 0 {
				b.WriteString(", ")
			}
			writeCanonicalJSONString(b, k)
			b.WriteString(": ")
			writeCanonicalJSON(b, t[k])
		}
		b.WriteByte('}')
	default:
		panic(fmt.Sprintf("canonicalJSON: unsupported type %T (%v)", v, v))
	}
}

// writeCanonicalJSONString escapes a string exactly as Python's
// json.dumps(..., ensure_ascii=True) does: standard JSON short escapes for
// the usual control characters, \u00XX for other control characters, and
// EVERY non-ASCII code point as \uXXXX (surrogate pairs above the BMP)
// rather than raw UTF-8.
func writeCanonicalJSONString(b *strings.Builder, s string) {
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString(`\"`)
		case '\\':
			b.WriteString(`\\`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		case '\b':
			b.WriteString(`\b`)
		case '\f':
			b.WriteString(`\f`)
		default:
			switch {
			case r < 0x20:
				fmt.Fprintf(b, `\u%04x`, r)
			case r < 0x80:
				b.WriteRune(r)
			case r <= 0xFFFF:
				fmt.Fprintf(b, `\u%04x`, r)
			default:
				r -= 0x10000
				hi := 0xD800 + (r >> 10)
				lo := 0xDC00 + (r & 0x3FF)
				fmt.Fprintf(b, `\u%04x\u%04x`, hi, lo)
			}
		}
	}
	b.WriteByte('"')
}
