# Code generated by gen-streams. DO NOT EDIT.
# Source: pkg/streams/contract.yaml

CONSUMER_DEAD_LETTER_V1 = "consumer.dead_letter:v1"
"""Messages a stream consumer gave up on (a permanent error, or a transient error on its fifth delivery), written before the original is acknowledged. dead-letter-controller stores them for listing and redrive."""

RELEASE_REQUESTED_V1 = "release.requested:v1"
"""Candidate release accepted by release-controller; triggers manifest load for validation."""

MANIFEST_LOADED_CANDIDATE_V1 = "manifest.loaded.candidate:v1"
"""Resolved candidate topology from topology-controller back to release-controller."""

TOPOLOGY_CONTROLLER_RELEASE_REQUESTED = "topology-controller-release-requested"
"""topology-controller consumer group on release.requested:v1."""
