// Code generated by gen-streams. DO NOT EDIT.
// Source: pkg/streams/contract.yaml
package model

// VocabularyValuesForTest returns every vocabulary's values from contract.yaml
// in declaration order, keyed by the vocabulary's Go type name. Test-only
// accessor used by vocabulary_contract_test.go to verify YAML ↔ generated-Go
// parity.
func VocabularyValuesForTest() map[string][]string {
	return map[string][]string{
		"ParseFailureKind": {"invalid_sql", "unqualified_reference", "invalid_artifact", "internal"},
		"RejectReason": {"compile_failed", "parse_rehearsal_failed", "artifact_upload_failed", "invalid_sql", "unqualified_reference", "invalid_artifact", "internal_error", "duplicate_table", "unbuildable_cross_service_upstream", "nothing_to_validate", "seed_build_failed", "validation_failed"},
	}
}
