// Code generated by gen-streams. DO NOT EDIT.
// Source: pkg/streams/contract.yaml
//
// Each type here is a closed value set two or more services agree on. They are
// domain vocabulary, not transport: stream and consumer-group names live in
// pkg/streams, which no domain package imports.
package model

// ParseFailureKind — Why topology-controller could not resolve a candidate release. Declaration order is precedence.
// Values come from the vocabulary "parse_failure_kind" in contract.yaml, in
// declaration order.
type ParseFailureKind string

const (
	// ParseFailureKindInvalidSQL — sqlglot cannot parse a node's compiled SQL under the configured dialect.
	ParseFailureKindInvalidSQL ParseFailureKind = "invalid_sql"
	// ParseFailureKindUnqualifiedReference — a node references a relation without a schema qualifier.
	ParseFailureKindUnqualifiedReference ParseFailureKind = "unqualified_reference"
	// ParseFailureKindInvalidArtifact — the uploaded manifest or contract is unreadable, empty, of unknown kind, or names another service.
	ParseFailureKindInvalidArtifact ParseFailureKind = "invalid_artifact"
	// ParseFailureKindInternal — continuo's own wiring or an S3 write failed; no change to the user's source will fix it.
	ParseFailureKindInternal ParseFailureKind = "internal"
)

// ParseFailureKinds returns every value in contract.yaml declaration order.
func ParseFailureKinds() []ParseFailureKind {
	return []ParseFailureKind{
		ParseFailureKindInvalidSQL,
		ParseFailureKindUnqualifiedReference,
		ParseFailureKindInvalidArtifact,
		ParseFailureKindInternal,
	}
}

// IsValid reports whether v is a value declared in contract.yaml.
func (v ParseFailureKind) IsValid() bool {
	switch v {
	case ParseFailureKindInvalidSQL:
		return true
	case ParseFailureKindUnqualifiedReference:
		return true
	case ParseFailureKindInvalidArtifact:
		return true
	case ParseFailureKindInternal:
		return true
	}
	return false
}

// Healable reports whether the contract marks v as fixable by a change to the
// user's source, and therefore worth a remediation attempt.
func (v ParseFailureKind) Healable() bool {
	switch v {
	case ParseFailureKindInvalidSQL:
		return true
	case ParseFailureKindUnqualifiedReference:
		return true
	}
	return false
}
