package model_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"

	"github.com/carolsimone/continuo/pkg/domain/model"
)

// contractPath locates the single source of truth for every vocabulary. The
// YAML lives next to the stream contract because one generator run emits both
// surfaces; the generated vocabulary types land here, in the shared domain
// package, so domain code never imports the transport package.
func contractPath() string {
	return filepath.Join("..", "..", "streams", "contract.yaml")
}

type yamlVocabularies struct {
	Vocabularies []struct {
		Const  string `yaml:"const"`
		Values []struct {
			Value    string `yaml:"value"`
			Healable bool   `yaml:"healable"`
		} `yaml:"values"`
	} `yaml:"vocabularies"`
}

func loadVocabularies(t *testing.T) yamlVocabularies {
	t.Helper()
	data, err := os.ReadFile(contractPath())
	if err != nil {
		t.Fatalf("read contract.yaml: %v", err)
	}
	var c yamlVocabularies
	if err := yaml.Unmarshal(data, &c); err != nil {
		t.Fatalf("parse contract.yaml: %v", err)
	}
	if len(c.Vocabularies) == 0 {
		t.Fatal("contract.yaml declares no vocabularies")
	}
	return c
}

func TestGeneratedVocabulariesMatchContract(t *testing.T) {
	c := loadVocabularies(t)
	gen := model.VocabularyValuesForTest()
	if len(gen) != len(c.Vocabularies) {
		t.Errorf("yaml declares %d vocabularies, generated package has %d", len(c.Vocabularies), len(gen))
	}
	for _, v := range c.Vocabularies {
		got, ok := gen[v.Const]
		if !ok {
			t.Errorf("vocabulary %s missing from generated package", v.Const)
			continue
		}
		if len(got) != len(v.Values) {
			t.Errorf("vocabulary %s: yaml has %d values, generated has %d", v.Const, len(v.Values), len(got))
			continue
		}
		for i, val := range v.Values {
			if got[i] != val.Value {
				t.Errorf("vocabulary %s[%d]: yaml=%q generated=%q", v.Const, i, val.Value, got[i])
			}
		}
	}
}

func TestGeneratedVocabularyFileHeader(t *testing.T) {
	data, err := os.ReadFile("vocabulary.gen.go")
	if err != nil {
		t.Fatalf("read vocabulary.gen.go: %v", err)
	}
	if !strings.Contains(string(data), "// Code generated by gen-streams. DO NOT EDIT.") {
		t.Fatal("vocabulary.gen.go missing generated header")
	}
}

func TestParseFailureKind_ContractOrderAndHealable(t *testing.T) {
	kinds := model.ParseFailureKinds()
	want := []model.ParseFailureKind{
		model.ParseFailureKindInvalidSQL,
		model.ParseFailureKindUnqualifiedReference,
		model.ParseFailureKindInvalidArtifact,
		model.ParseFailureKindInternal,
	}
	if len(kinds) != len(want) {
		t.Fatalf("ParseFailureKinds() = %v, want %v", kinds, want)
	}
	for i := range want {
		if kinds[i] != want[i] {
			t.Errorf("index %d: %q, want %q", i, kinds[i], want[i])
		}
		if !kinds[i].IsValid() {
			t.Errorf("%q must be valid", kinds[i])
		}
	}
	if !model.ParseFailureKindInvalidSQL.Healable() || !model.ParseFailureKindUnqualifiedReference.Healable() {
		t.Error("both SQL kinds must be healable")
	}
	if model.ParseFailureKindInvalidArtifact.Healable() || model.ParseFailureKindInternal.Healable() {
		t.Error("artifact and internal kinds must not be healable")
	}
	if model.ParseFailureKind("nonsense").IsValid() {
		t.Error("an undeclared value must not be valid")
	}
}

// TestVocabularyHealableFlagsMatchContract pins every generated Healable()
// answer to the healable: flag the YAML declares for that value.
func TestVocabularyHealableFlagsMatchContract(t *testing.T) {
	c := loadVocabularies(t)
	healableByType := map[string]func(string) bool{
		"ParseFailureKind": func(v string) bool { return model.ParseFailureKind(v).Healable() },
		"RejectReason":     func(v string) bool { return model.RejectReason(v).Healable() },
	}
	for _, v := range c.Vocabularies {
		healable, ok := healableByType[v.Const]
		if !ok {
			t.Errorf("vocabulary %s has no Healable() probe in this test — add one", v.Const)
			continue
		}
		for _, val := range v.Values {
			if got := healable(val.Value); got != val.Healable {
				t.Errorf("%s(%q).Healable() = %v, yaml says %v", v.Const, val.Value, got, val.Healable)
			}
		}
	}
}

// TestRejectReason_HealableSet pins the reasons release-controller's retry path
// and the remediation classifier act on: the four leg failures plus the two
// parse failures a source change can fix. Every other reason is dropped.
func TestRejectReason_HealableSet(t *testing.T) {
	healable := map[model.RejectReason]bool{}
	for _, r := range model.RejectReasons() {
		if !r.IsValid() {
			t.Errorf("%q is returned by RejectReasons() but is not valid", r)
		}
		if r.Healable() {
			healable[r] = true
		}
	}
	want := map[model.RejectReason]bool{
		model.RejectReasonCompileFailed:        true,
		model.RejectReasonSeedBuildFailed:      true,
		model.RejectReasonValidationFailed:     true,
		model.RejectReasonDuplicateTable:       true,
		model.RejectReasonInvalidSQL:           true,
		model.RejectReasonUnqualifiedReference: true,
	}
	if len(healable) != len(want) {
		t.Fatalf("healable reasons = %v, want %v", healable, want)
	}
	for r := range want {
		if !healable[r] {
			t.Errorf("%q must be healable", r)
		}
	}
	if model.RejectReason("nonsense").IsValid() || model.RejectReason("").Healable() {
		t.Error("an undeclared reason is neither valid nor healable")
	}
}
