apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "continuo-app.cancelConfigMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "continuo-app.labels" . | nindent 4 }}
data:
  cancel-config.json: |
    {{- .Files.Get "files/cancel-config.json" | nindent 4 }}
