apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "continuo-app.serviceReposConfigMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "continuo-app.labels" . | nindent 4 }}
data:
  service_repos.yaml: |
    {{- .Files.Get "files/service_repos.yaml" | nindent 4 }}
