apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "continuo.dbtCommandsConfigMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "continuo.labels" . | nindent 4 }}
data:
  dbt-commands.yaml: |
    {{- .Files.Get "files/dbt-commands.yaml" | nindent 4 }}
