apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "continuo.schedulesConfigMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "continuo.labels" . | nindent 4 }}
data:
  schedules.yaml: |
    {{- .Files.Get "files/schedules.yaml" | nindent 4 }}
