FROM python:3.14-slim AS builder

WORKDIR /app

RUN pip install uv

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev --no-install-project

FROM python:3.14-slim

WORKDIR /app

COPY --from=builder /app/.venv /app/.venv
COPY main.py ./
COPY config/ ./config/
COPY adapters/ ./adapters/
COPY domain/ ./domain/
COPY service/ ./service/
COPY proto/ ./proto/

ENV PATH="/app/.venv/bin:$PATH"

CMD ["python", "main.py"]
