FROM flyway/flyway:10

USER root
COPY migrate-all.sh /migrate-all.sh
RUN chmod +x /migrate-all.sh

COPY migration/state /flyway/sql/state
COPY migration/executor /flyway/sql/executor
COPY migration/orchestrator /flyway/sql/orchestrator
COPY migration/k8s /flyway/sql/k8s
COPY migration/release /flyway/sql/release

ENTRYPOINT ["/bin/sh", "/migrate-all.sh"]
