// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/state/v1/state.proto

package statev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SchedulerStatus int32

const (
	SchedulerStatus_SCHEDULER_STATUS_UNSPECIFIED SchedulerStatus = 0
	SchedulerStatus_SCHEDULER_STATUS_PENDING     SchedulerStatus = 1
	SchedulerStatus_SCHEDULER_STATUS_RUNNING     SchedulerStatus = 2
	SchedulerStatus_SCHEDULER_STATUS_SUCCEEDED   SchedulerStatus = 3
	SchedulerStatus_SCHEDULER_STATUS_FAILED      SchedulerStatus = 4
	SchedulerStatus_SCHEDULER_STATUS_CANCELLED   SchedulerStatus = 5
)

// Enum value maps for SchedulerStatus.
var (
	SchedulerStatus_name = map[int32]string{
		0: "SCHEDULER_STATUS_UNSPECIFIED",
		1: "SCHEDULER_STATUS_PENDING",
		2: "SCHEDULER_STATUS_RUNNING",
		3: "SCHEDULER_STATUS_SUCCEEDED",
		4: "SCHEDULER_STATUS_FAILED",
		5: "SCHEDULER_STATUS_CANCELLED",
	}
	SchedulerStatus_value = map[string]int32{
		"SCHEDULER_STATUS_UNSPECIFIED": 0,
		"SCHEDULER_STATUS_PENDING":     1,
		"SCHEDULER_STATUS_RUNNING":     2,
		"SCHEDULER_STATUS_SUCCEEDED":   3,
		"SCHEDULER_STATUS_FAILED":      4,
		"SCHEDULER_STATUS_CANCELLED":   5,
	}
)

func (x SchedulerStatus) Enum() *SchedulerStatus {
	p := new(SchedulerStatus)
	*p = x
	return p
}

func (x SchedulerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SchedulerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_state_v1_state_proto_enumTypes[0].Descriptor()
}

func (SchedulerStatus) Type() protoreflect.EnumType {
	return &file_proto_state_v1_state_proto_enumTypes[0]
}

func (x SchedulerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SchedulerStatus.Descriptor instead.
func (SchedulerStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{0}
}

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_PENDING     TaskStatus = 1
	TaskStatus_TASK_STATUS_RUNNING     TaskStatus = 2
	TaskStatus_TASK_STATUS_SUCCEEDED   TaskStatus = 3
	TaskStatus_TASK_STATUS_FAILED      TaskStatus = 4
	TaskStatus_TASK_STATUS_CANCELLED   TaskStatus = 5
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_PENDING",
		2: "TASK_STATUS_RUNNING",
		3: "TASK_STATUS_SUCCEEDED",
		4: "TASK_STATUS_FAILED",
		5: "TASK_STATUS_CANCELLED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_PENDING":     1,
		"TASK_STATUS_RUNNING":     2,
		"TASK_STATUS_SUCCEEDED":   3,
		"TASK_STATUS_FAILED":      4,
		"TASK_STATUS_CANCELLED":   5,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_state_v1_state_proto_enumTypes[1].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_proto_state_v1_state_proto_enumTypes[1]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{1}
}

type Scheduler struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId           string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	ScheduleName         string                 `protobuf:"bytes,2,opt,name=schedule_name,json=scheduleName,proto3" json:"schedule_name,omitempty"`
	Status               SchedulerStatus        `protobuf:"varint,3,opt,name=status,proto3,enum=state.v1.SchedulerStatus" json:"status,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	LastHeartbeatAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_heartbeat_at,json=lastHeartbeatAt,proto3" json:"last_heartbeat_at,omitempty"`
	CancelledAt          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
	CancelledBy          string                 `protobuf:"bytes,9,opt,name=cancelled_by,json=cancelledBy,proto3" json:"cancelled_by,omitempty"`
	CancellationReason   string                 `protobuf:"bytes,10,opt,name=cancellation_reason,json=cancellationReason,proto3" json:"cancellation_reason,omitempty"`
	InitializationStatus string                 `protobuf:"bytes,11,opt,name=initialization_status,json=initializationStatus,proto3" json:"initialization_status,omitempty"` // 'pending', 'in_progress', 'completed', 'failed'
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Scheduler) Reset() {
	*x = Scheduler{}
	mi := &file_proto_state_v1_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scheduler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scheduler) ProtoMessage() {}

func (x *Scheduler) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scheduler.ProtoReflect.Descriptor instead.
func (*Scheduler) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{0}
}

func (x *Scheduler) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *Scheduler) GetScheduleName() string {
	if x != nil {
		return x.ScheduleName
	}
	return ""
}

func (x *Scheduler) GetStatus() SchedulerStatus {
	if x != nil {
		return x.Status
	}
	return SchedulerStatus_SCHEDULER_STATUS_UNSPECIFIED
}

func (x *Scheduler) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Scheduler) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Scheduler) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Scheduler) GetLastHeartbeatAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeatAt
	}
	return nil
}

func (x *Scheduler) GetCancelledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CancelledAt
	}
	return nil
}

func (x *Scheduler) GetCancelledBy() string {
	if x != nil {
		return x.CancelledBy
	}
	return ""
}

func (x *Scheduler) GetCancellationReason() string {
	if x != nil {
		return x.CancellationReason
	}
	return ""
}

func (x *Scheduler) GetInitializationStatus() string {
	if x != nil {
		return x.InitializationStatus
	}
	return ""
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ScheduleId    string                 `protobuf:"bytes,2,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ServiceName   string                 `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	SchemaName    string                 `protobuf:"bytes,5,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	TableName     string                 `protobuf:"bytes,6,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	JobName       string                 `protobuf:"bytes,7,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"` // K8s job identifier (computed from service-schema-table)
	Status        TaskStatus             `protobuf:"varint,8,opt,name=status,proto3,enum=state.v1.TaskStatus" json:"status,omitempty"`
	RetryCount    int32                  `protobuf:"varint,9,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	MaxRetries    int32                  `protobuf:"varint,10,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	CancelledAt   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
	CancelledBy   string                 `protobuf:"bytes,12,opt,name=cancelled_by,json=cancelledBy,proto3" json:"cancelled_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_state_v1_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Task) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *Task) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *Task) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *Task) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Task) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *Task) GetCancelledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CancelledAt
	}
	return nil
}

func (x *Task) GetCancelledBy() string {
	if x != nil {
		return x.CancelledBy
	}
	return ""
}

type TaskExecution struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId               string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	ExecutionTimeSeconds float64                `protobuf:"fixed64,6,opt,name=execution_time_seconds,json=executionTimeSeconds,proto3" json:"execution_time_seconds,omitempty"`
	ExecutorId           string                 `protobuf:"bytes,7,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	K8SJobName           string                 `protobuf:"bytes,8,opt,name=k8s_job_name,json=k8sJobName,proto3" json:"k8s_job_name,omitempty"`
	ErrorMessage         string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CancelledAt          *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
	CancelledBy          string                 `protobuf:"bytes,11,opt,name=cancelled_by,json=cancelledBy,proto3" json:"cancelled_by,omitempty"`
	CancellationReason   string                 `protobuf:"bytes,12,opt,name=cancellation_reason,json=cancellationReason,proto3" json:"cancellation_reason,omitempty"`
	LogS3Key             string                 `protobuf:"bytes,13,opt,name=log_s3_key,json=logS3Key,proto3" json:"log_s3_key,omitempty"` // S3 object key for full pod log; empty if upload failed
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TaskExecution) Reset() {
	*x = TaskExecution{}
	mi := &file_proto_state_v1_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecution) ProtoMessage() {}

func (x *TaskExecution) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExecution.ProtoReflect.Descriptor instead.
func (*TaskExecution) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{2}
}

func (x *TaskExecution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskExecution) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskExecution) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TaskExecution) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *TaskExecution) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *TaskExecution) GetExecutionTimeSeconds() float64 {
	if x != nil {
		return x.ExecutionTimeSeconds
	}
	return 0
}

func (x *TaskExecution) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *TaskExecution) GetK8SJobName() string {
	if x != nil {
		return x.K8SJobName
	}
	return ""
}

func (x *TaskExecution) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskExecution) GetCancelledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CancelledAt
	}
	return nil
}

func (x *TaskExecution) GetCancelledBy() string {
	if x != nil {
		return x.CancelledBy
	}
	return ""
}

func (x *TaskExecution) GetCancellationReason() string {
	if x != nil {
		return x.CancellationReason
	}
	return ""
}

func (x *TaskExecution) GetLogS3Key() string {
	if x != nil {
		return x.LogS3Key
	}
	return ""
}

type CreateSchedulerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId    string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`       // Optional: client can provide UUID
	ScheduleName  string                 `protobuf:"bytes,2,opt,name=schedule_name,json=scheduleName,proto3" json:"schedule_name,omitempty"` // Required
	Status        SchedulerStatus        `protobuf:"varint,3,opt,name=status,proto3,enum=state.v1.SchedulerStatus" json:"status,omitempty"`  // Optional: defaults to PENDING
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSchedulerRequest) Reset() {
	*x = CreateSchedulerRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSchedulerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSchedulerRequest) ProtoMessage() {}

func (x *CreateSchedulerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSchedulerRequest.ProtoReflect.Descriptor instead.
func (*CreateSchedulerRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSchedulerRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *CreateSchedulerRequest) GetScheduleName() string {
	if x != nil {
		return x.ScheduleName
	}
	return ""
}

func (x *CreateSchedulerRequest) GetStatus() SchedulerStatus {
	if x != nil {
		return x.Status
	}
	return SchedulerStatus_SCHEDULER_STATUS_UNSPECIFIED
}

type GetSchedulerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId    string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"` // Required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchedulerRequest) Reset() {
	*x = GetSchedulerRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchedulerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchedulerRequest) ProtoMessage() {}

func (x *GetSchedulerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchedulerRequest.ProtoReflect.Descriptor instead.
func (*GetSchedulerRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{4}
}

func (x *GetSchedulerRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

type CancelSchedulerRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId         string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`                         // Required
	CancelledBy        string                 `protobuf:"bytes,2,opt,name=cancelled_by,json=cancelledBy,proto3" json:"cancelled_by,omitempty"`                      // Optional
	CancellationReason string                 `protobuf:"bytes,3,opt,name=cancellation_reason,json=cancellationReason,proto3" json:"cancellation_reason,omitempty"` // Optional
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CancelSchedulerRequest) Reset() {
	*x = CancelSchedulerRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSchedulerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSchedulerRequest) ProtoMessage() {}

func (x *CancelSchedulerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSchedulerRequest.ProtoReflect.Descriptor instead.
func (*CancelSchedulerRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{5}
}

func (x *CancelSchedulerRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *CancelSchedulerRequest) GetCancelledBy() string {
	if x != nil {
		return x.CancelledBy
	}
	return ""
}

func (x *CancelSchedulerRequest) GetCancellationReason() string {
	if x != nil {
		return x.CancellationReason
	}
	return ""
}

type SchedulerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scheduler     *Scheduler             `protobuf:"bytes,1,opt,name=scheduler,proto3" json:"scheduler,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedulerResponse) Reset() {
	*x = SchedulerResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulerResponse) ProtoMessage() {}

func (x *SchedulerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulerResponse.ProtoReflect.Descriptor instead.
func (*SchedulerResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{6}
}

func (x *SchedulerResponse) GetScheduler() *Scheduler {
	if x != nil {
		return x.Scheduler
	}
	return nil
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                // Required: application-generated UUID
	ScheduleId    string                 `protobuf:"bytes,2,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`    // Required
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // Required
	SchemaName    string                 `protobuf:"bytes,4,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`    // Required
	TableName     string                 `protobuf:"bytes,5,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`       // Required
	MaxRetries    int32                  `protobuf:"varint,6,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`   // Required
	Status        TaskStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=state.v1.TaskStatus" json:"status,omitempty"`    // Optional: defaults to PENDING
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CreateTaskRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *CreateTaskRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *CreateTaskRequest) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *CreateTaskRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *CreateTaskRequest) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *CreateTaskRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // Required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{8}
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskByScheduleAndNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId    string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`    // Required
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // Required
	SchemaName    string                 `protobuf:"bytes,3,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`    // Required
	TableName     string                 `protobuf:"bytes,4,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`       // Required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskByScheduleAndNodeRequest) Reset() {
	*x = GetTaskByScheduleAndNodeRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskByScheduleAndNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskByScheduleAndNodeRequest) ProtoMessage() {}

func (x *GetTaskByScheduleAndNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskByScheduleAndNodeRequest.ProtoReflect.Descriptor instead.
func (*GetTaskByScheduleAndNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{9}
}

func (x *GetTaskByScheduleAndNodeRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *GetTaskByScheduleAndNodeRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetTaskByScheduleAndNodeRequest) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *GetTaskByScheduleAndNodeRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // Required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type DeleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskResponse) Reset() {
	*x = DeleteTaskResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskResponse) ProtoMessage() {}

func (x *DeleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskResponse.ProtoReflect.Descriptor instead.
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId    string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`  // Required
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=state.v1.TaskStatus" json:"status,omitempty"`  // Optional filter
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`       // Pagination (default 50)
	PageOffset    int32                  `protobuf:"varint,4,opt,name=page_offset,json=pageOffset,proto3" json:"page_offset,omitempty"` // Pagination offset
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{12}
}

func (x *ListTasksRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *ListTasksRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *ListTasksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTasksRequest) GetPageOffset() int32 {
	if x != nil {
		return x.PageOffset
	}
	return 0
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{13}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{14}
}

func (x *TaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type GetTaskExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Required: execution ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskExecutionRequest) Reset() {
	*x = GetTaskExecutionRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskExecutionRequest) ProtoMessage() {}

func (x *GetTaskExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskExecutionRequest.ProtoReflect.Descriptor instead.
func (*GetTaskExecutionRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{15}
}

func (x *GetTaskExecutionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TaskExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskExecution *TaskExecution         `protobuf:"bytes,1,opt,name=task_execution,json=taskExecution,proto3" json:"task_execution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskExecutionResponse) Reset() {
	*x = TaskExecutionResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecutionResponse) ProtoMessage() {}

func (x *TaskExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExecutionResponse.ProtoReflect.Descriptor instead.
func (*TaskExecutionResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{16}
}

func (x *TaskExecutionResponse) GetTaskExecution() *TaskExecution {
	if x != nil {
		return x.TaskExecution
	}
	return nil
}

type ListTaskExecutionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId    string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"` // Required
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`      // UI hardcodes 500
	PageOffset    int32                  `protobuf:"varint,3,opt,name=page_offset,json=pageOffset,proto3" json:"page_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTaskExecutionsRequest) Reset() {
	*x = ListTaskExecutionsRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTaskExecutionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaskExecutionsRequest) ProtoMessage() {}

func (x *ListTaskExecutionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaskExecutionsRequest.ProtoReflect.Descriptor instead.
func (*ListTaskExecutionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{17}
}

func (x *ListTaskExecutionsRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *ListTaskExecutionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTaskExecutionsRequest) GetPageOffset() int32 {
	if x != nil {
		return x.PageOffset
	}
	return 0
}

type ListTaskExecutionsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskExecutions []*TaskExecution       `protobuf:"bytes,1,rep,name=task_executions,json=taskExecutions,proto3" json:"task_executions,omitempty"`
	TotalCount     int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListTaskExecutionsResponse) Reset() {
	*x = ListTaskExecutionsResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTaskExecutionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaskExecutionsResponse) ProtoMessage() {}

func (x *ListTaskExecutionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaskExecutionsResponse.ProtoReflect.Descriptor instead.
func (*ListTaskExecutionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{18}
}

func (x *ListTaskExecutionsResponse) GetTaskExecutions() []*TaskExecution {
	if x != nil {
		return x.TaskExecutions
	}
	return nil
}

func (x *ListTaskExecutionsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ActivateScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleName  string                 `protobuf:"bytes,1,opt,name=schedule_name,json=scheduleName,proto3" json:"schedule_name,omitempty"` // Required: name of the schedule to activate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateScheduleRequest) Reset() {
	*x = ActivateScheduleRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateScheduleRequest) ProtoMessage() {}

func (x *ActivateScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateScheduleRequest.ProtoReflect.Descriptor instead.
func (*ActivateScheduleRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{19}
}

func (x *ActivateScheduleRequest) GetScheduleName() string {
	if x != nil {
		return x.ScheduleName
	}
	return ""
}

type ActivateScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId    string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"` // UUID of the created scheduler_tracker record
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateScheduleResponse) Reset() {
	*x = ActivateScheduleResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateScheduleResponse) ProtoMessage() {}

func (x *ActivateScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateScheduleResponse.ProtoReflect.Descriptor instead.
func (*ActivateScheduleResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{20}
}

func (x *ActivateScheduleResponse) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

type ListAllSchedulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllSchedulesRequest) Reset() {
	*x = ListAllSchedulesRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllSchedulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllSchedulesRequest) ProtoMessage() {}

func (x *ListAllSchedulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllSchedulesRequest.ProtoReflect.Descriptor instead.
func (*ListAllSchedulesRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{21}
}

// ScheduleSummary merges catalog data, last-run data, and cron config.
// last_run_status uses lowercase strings ("succeeded", "failed", "cancelled")
// matching the domain model — intentionally not the SchedulerStatus enum
// to decouple this message from scheduler_tracker internals.
type ScheduleSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ScheduleName   string                 `protobuf:"bytes,1,opt,name=schedule_name,json=scheduleName,proto3" json:"schedule_name,omitempty"`
	CronExpression string                 `protobuf:"bytes,2,opt,name=cron_expression,json=cronExpression,proto3" json:"cron_expression,omitempty"` // empty if not in schedules.yaml
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                             // from schedules.yaml; empty if not found
	Timezone       string                 `protobuf:"bytes,4,opt,name=timezone,proto3" json:"timezone,omitempty"`                                   // top-level timezone from schedules.yaml
	IsRunning      bool                   `protobuf:"varint,5,opt,name=is_running,json=isRunning,proto3" json:"is_running,omitempty"`
	LastRunAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_run_at,json=lastRunAt,proto3" json:"last_run_at,omitempty"`             // null if never run
	LastRunStatus  string                 `protobuf:"bytes,7,opt,name=last_run_status,json=lastRunStatus,proto3" json:"last_run_status,omitempty"` // "succeeded"/"failed"/"cancelled"; empty if never run
	LastRunId      string                 `protobuf:"bytes,8,opt,name=last_run_id,json=lastRunId,proto3" json:"last_run_id,omitempty"`             // schedule_id of most recent run; empty string if never run
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScheduleSummary) Reset() {
	*x = ScheduleSummary{}
	mi := &file_proto_state_v1_state_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleSummary) ProtoMessage() {}

func (x *ScheduleSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleSummary.ProtoReflect.Descriptor instead.
func (*ScheduleSummary) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{22}
}

func (x *ScheduleSummary) GetScheduleName() string {
	if x != nil {
		return x.ScheduleName
	}
	return ""
}

func (x *ScheduleSummary) GetCronExpression() string {
	if x != nil {
		return x.CronExpression
	}
	return ""
}

func (x *ScheduleSummary) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ScheduleSummary) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *ScheduleSummary) GetIsRunning() bool {
	if x != nil {
		return x.IsRunning
	}
	return false
}

func (x *ScheduleSummary) GetLastRunAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRunAt
	}
	return nil
}

func (x *ScheduleSummary) GetLastRunStatus() string {
	if x != nil {
		return x.LastRunStatus
	}
	return ""
}

func (x *ScheduleSummary) GetLastRunId() string {
	if x != nil {
		return x.LastRunId
	}
	return ""
}

type ListAllSchedulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedules     []*ScheduleSummary     `protobuf:"bytes,1,rep,name=schedules,proto3" json:"schedules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllSchedulesResponse) Reset() {
	*x = ListAllSchedulesResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllSchedulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllSchedulesResponse) ProtoMessage() {}

func (x *ListAllSchedulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllSchedulesResponse.ProtoReflect.Descriptor instead.
func (*ListAllSchedulesResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{23}
}

func (x *ListAllSchedulesResponse) GetSchedules() []*ScheduleSummary {
	if x != nil {
		return x.Schedules
	}
	return nil
}

type TriggerScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleName  string                 `protobuf:"bytes,1,opt,name=schedule_name,json=scheduleName,proto3" json:"schedule_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerScheduleRequest) Reset() {
	*x = TriggerScheduleRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerScheduleRequest) ProtoMessage() {}

func (x *TriggerScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerScheduleRequest.ProtoReflect.Descriptor instead.
func (*TriggerScheduleRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{24}
}

func (x *TriggerScheduleRequest) GetScheduleName() string {
	if x != nil {
		return x.ScheduleName
	}
	return ""
}

// schedule_id is always non-empty on success.
// Errors: NOT_FOUND (schedule not in catalog), FAILED_PRECONDITION (already running).
type TriggerScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId    string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerScheduleResponse) Reset() {
	*x = TriggerScheduleResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerScheduleResponse) ProtoMessage() {}

func (x *TriggerScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerScheduleResponse.ProtoReflect.Descriptor instead.
func (*TriggerScheduleResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{25}
}

func (x *TriggerScheduleResponse) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

type CancelScheduleRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ScheduleName       string                 `protobuf:"bytes,1,opt,name=schedule_name,json=scheduleName,proto3" json:"schedule_name,omitempty"`                   // Required
	CancelledBy        string                 `protobuf:"bytes,2,opt,name=cancelled_by,json=cancelledBy,proto3" json:"cancelled_by,omitempty"`                      // Optional
	CancellationReason string                 `protobuf:"bytes,3,opt,name=cancellation_reason,json=cancellationReason,proto3" json:"cancellation_reason,omitempty"` // Optional
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CancelScheduleRequest) Reset() {
	*x = CancelScheduleRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelScheduleRequest) ProtoMessage() {}

func (x *CancelScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelScheduleRequest.ProtoReflect.Descriptor instead.
func (*CancelScheduleRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{26}
}

func (x *CancelScheduleRequest) GetScheduleName() string {
	if x != nil {
		return x.ScheduleName
	}
	return ""
}

func (x *CancelScheduleRequest) GetCancelledBy() string {
	if x != nil {
		return x.CancelledBy
	}
	return ""
}

func (x *CancelScheduleRequest) GetCancellationReason() string {
	if x != nil {
		return x.CancellationReason
	}
	return ""
}

type CancelScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId    string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"` // schedule_id of the cancelled run
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelScheduleResponse) Reset() {
	*x = CancelScheduleResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelScheduleResponse) ProtoMessage() {}

func (x *CancelScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelScheduleResponse.ProtoReflect.Descriptor instead.
func (*CancelScheduleResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{27}
}

func (x *CancelScheduleResponse) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

type ResetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetTaskRequest) Reset() {
	*x = ResetTaskRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetTaskRequest) ProtoMessage() {}

func (x *ResetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetTaskRequest.ProtoReflect.Descriptor instead.
func (*ResetTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{28}
}

func (x *ResetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetSchedulerInitStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId    string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchedulerInitStatusRequest) Reset() {
	*x = GetSchedulerInitStatusRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchedulerInitStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchedulerInitStatusRequest) ProtoMessage() {}

func (x *GetSchedulerInitStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchedulerInitStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSchedulerInitStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{29}
}

func (x *GetSchedulerInitStatusRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

type GetSchedulerInitStatusResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	InitializationStatus string                 `protobuf:"bytes,1,opt,name=initialization_status,json=initializationStatus,proto3" json:"initialization_status,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetSchedulerInitStatusResponse) Reset() {
	*x = GetSchedulerInitStatusResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchedulerInitStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchedulerInitStatusResponse) ProtoMessage() {}

func (x *GetSchedulerInitStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchedulerInitStatusResponse.ProtoReflect.Descriptor instead.
func (*GetSchedulerInitStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{30}
}

func (x *GetSchedulerInitStatusResponse) GetInitializationStatus() string {
	if x != nil {
		return x.InitializationStatus
	}
	return ""
}

type TriggerRerunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId    string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	Schema        string                 `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	TableName     string                 `protobuf:"bytes,3,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	ServiceName   string                 `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerRerunRequest) Reset() {
	*x = TriggerRerunRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRerunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRerunRequest) ProtoMessage() {}

func (x *TriggerRerunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRerunRequest.ProtoReflect.Descriptor instead.
func (*TriggerRerunRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{31}
}

func (x *TriggerRerunRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *TriggerRerunRequest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *TriggerRerunRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *TriggerRerunRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type TriggerRerunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerRerunResponse) Reset() {
	*x = TriggerRerunResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRerunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRerunResponse) ProtoMessage() {}

func (x *TriggerRerunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRerunResponse.ProtoReflect.Descriptor instead.
func (*TriggerRerunResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{32}
}

type TriggerSingleNodeRunRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceName    string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`          // Required
	SchemaName     string                 `protobuf:"bytes,2,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`             // Required
	TableName      string                 `protobuf:"bytes,3,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`                // Required
	MetadataSource string                 `protobuf:"bytes,4,opt,name=metadata_source,json=metadataSource,proto3" json:"metadata_source,omitempty"` // Required: "latest" | "snapshot_of_run"
	SourceRunId    string                 `protobuf:"bytes,5,opt,name=source_run_id,json=sourceRunId,proto3" json:"source_run_id,omitempty"`        // Required iff metadata_source == "snapshot_of_run"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TriggerSingleNodeRunRequest) Reset() {
	*x = TriggerSingleNodeRunRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSingleNodeRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSingleNodeRunRequest) ProtoMessage() {}

func (x *TriggerSingleNodeRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSingleNodeRunRequest.ProtoReflect.Descriptor instead.
func (*TriggerSingleNodeRunRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{33}
}

func (x *TriggerSingleNodeRunRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *TriggerSingleNodeRunRequest) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *TriggerSingleNodeRunRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *TriggerSingleNodeRunRequest) GetMetadataSource() string {
	if x != nil {
		return x.MetadataSource
	}
	return ""
}

func (x *TriggerSingleNodeRunRequest) GetSourceRunId() string {
	if x != nil {
		return x.SourceRunId
	}
	return ""
}

type TriggerSingleNodeRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`                      // synthesized scheduler_tracker.schedule_id (uuid)
	ScheduleName  string                 `protobuf:"bytes,2,opt,name=schedule_name,json=scheduleName,proto3" json:"schedule_name,omitempty"` // "single-node-run-<short-uuid>"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSingleNodeRunResponse) Reset() {
	*x = TriggerSingleNodeRunResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSingleNodeRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSingleNodeRunResponse) ProtoMessage() {}

func (x *TriggerSingleNodeRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSingleNodeRunResponse.ProtoReflect.Descriptor instead.
func (*TriggerSingleNodeRunResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{34}
}

func (x *TriggerSingleNodeRunResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *TriggerSingleNodeRunResponse) GetScheduleName() string {
	if x != nil {
		return x.ScheduleName
	}
	return ""
}

type TriggerRebaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceRunId   string                 `protobuf:"bytes,1,opt,name=source_run_id,json=sourceRunId,proto3" json:"source_run_id,omitempty"` // schedule_id of the failed/cancelled run to rebase from
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerRebaseRequest) Reset() {
	*x = TriggerRebaseRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRebaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRebaseRequest) ProtoMessage() {}

func (x *TriggerRebaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRebaseRequest.ProtoReflect.Descriptor instead.
func (*TriggerRebaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{35}
}

func (x *TriggerRebaseRequest) GetSourceRunId() string {
	if x != nil {
		return x.SourceRunId
	}
	return ""
}

type TriggerRebaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`                      // schedule_id of the new rebase run
	ScheduleName  string                 `protobuf:"bytes,2,opt,name=schedule_name,json=scheduleName,proto3" json:"schedule_name,omitempty"` // copied verbatim from source's schedule_name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerRebaseResponse) Reset() {
	*x = TriggerRebaseResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRebaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRebaseResponse) ProtoMessage() {}

func (x *TriggerRebaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRebaseResponse.ProtoReflect.Descriptor instead.
func (*TriggerRebaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{36}
}

func (x *TriggerRebaseResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *TriggerRebaseResponse) GetScheduleName() string {
	if x != nil {
		return x.ScheduleName
	}
	return ""
}

var File_proto_state_v1_state_proto protoreflect.FileDescriptor

const file_proto_state_v1_state_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/state/v1/state.proto\x12\bstate.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc9\x04\n" +
	"\tScheduler\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\x12#\n" +
	"\rschedule_name\x18\x02 \x01(\tR\fscheduleName\x121\n" +
	"\x06status\x18\x03 \x01(\x0e2\x19.state.v1.SchedulerStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12F\n" +
	"\x11last_heartbeat_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0flastHeartbeatAt\x12=\n" +
	"\fcancelled_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vcancelledAt\x12!\n" +
	"\fcancelled_by\x18\t \x01(\tR\vcancelledBy\x12/\n" +
	"\x13cancellation_reason\x18\n" +
	" \x01(\tR\x12cancellationReason\x123\n" +
	"\x15initialization_status\x18\v \x01(\tR\x14initializationStatus\"\xcb\x03\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vschedule_id\x18\x02 \x01(\tR\n" +
	"scheduleId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12!\n" +
	"\fservice_name\x18\x04 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vschema_name\x18\x05 \x01(\tR\n" +
	"schemaName\x12\x1d\n" +
	"\n" +
	"table_name\x18\x06 \x01(\tR\ttableName\x12\x19\n" +
	"\bjob_name\x18\a \x01(\tR\ajobName\x12,\n" +
	"\x06status\x18\b \x01(\x0e2\x14.state.v1.TaskStatusR\x06status\x12\x1f\n" +
	"\vretry_count\x18\t \x01(\x05R\n" +
	"retryCount\x12\x1f\n" +
	"\vmax_retries\x18\n" +
	" \x01(\x05R\n" +
	"maxRetries\x12=\n" +
	"\fcancelled_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vcancelledAt\x12!\n" +
	"\fcancelled_by\x18\f \x01(\tR\vcancelledBy\"\xbc\x04\n" +
	"\rTaskExecution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x124\n" +
	"\x16execution_time_seconds\x18\x06 \x01(\x01R\x14executionTimeSeconds\x12\x1f\n" +
	"\vexecutor_id\x18\a \x01(\tR\n" +
	"executorId\x12 \n" +
	"\fk8s_job_name\x18\b \x01(\tR\n" +
	"k8sJobName\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\x12=\n" +
	"\fcancelled_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vcancelledAt\x12!\n" +
	"\fcancelled_by\x18\v \x01(\tR\vcancelledBy\x12/\n" +
	"\x13cancellation_reason\x18\f \x01(\tR\x12cancellationReason\x12\x1c\n" +
	"\n" +
	"log_s3_key\x18\r \x01(\tR\blogS3Key\"\x91\x01\n" +
	"\x16CreateSchedulerRequest\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\x12#\n" +
	"\rschedule_name\x18\x02 \x01(\tR\fscheduleName\x121\n" +
	"\x06status\x18\x03 \x01(\x0e2\x19.state.v1.SchedulerStatusR\x06status\"6\n" +
	"\x13GetSchedulerRequest\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\"\x8d\x01\n" +
	"\x16CancelSchedulerRequest\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\x12!\n" +
	"\fcancelled_by\x18\x02 \x01(\tR\vcancelledBy\x12/\n" +
	"\x13cancellation_reason\x18\x03 \x01(\tR\x12cancellationReason\"F\n" +
	"\x11SchedulerResponse\x121\n" +
	"\tscheduler\x18\x01 \x01(\v2\x13.state.v1.SchedulerR\tscheduler\"\xff\x01\n" +
	"\x11CreateTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vschedule_id\x18\x02 \x01(\tR\n" +
	"scheduleId\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vschema_name\x18\x04 \x01(\tR\n" +
	"schemaName\x12\x1d\n" +
	"\n" +
	"table_name\x18\x05 \x01(\tR\ttableName\x12\x1f\n" +
	"\vmax_retries\x18\x06 \x01(\x05R\n" +
	"maxRetries\x12,\n" +
	"\x06status\x18\a \x01(\x0e2\x14.state.v1.TaskStatusR\x06status\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xa5\x01\n" +
	"\x1fGetTaskByScheduleAndNodeRequest\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vschema_name\x18\x03 \x01(\tR\n" +
	"schemaName\x12\x1d\n" +
	"\n" +
	"table_name\x18\x04 \x01(\tR\ttableName\",\n" +
	"\x11DeleteTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"H\n" +
	"\x12DeleteTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9f\x01\n" +
	"\x10ListTasksRequest\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.state.v1.TaskStatusR\x06status\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vpage_offset\x18\x04 \x01(\x05R\n" +
	"pageOffset\"Z\n" +
	"\x11ListTasksResponse\x12$\n" +
	"\x05tasks\x18\x01 \x03(\v2\x0e.state.v1.TaskR\x05tasks\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"2\n" +
	"\fTaskResponse\x12\"\n" +
	"\x04task\x18\x01 \x01(\v2\x0e.state.v1.TaskR\x04task\")\n" +
	"\x17GetTaskExecutionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"W\n" +
	"\x15TaskExecutionResponse\x12>\n" +
	"\x0etask_execution\x18\x01 \x01(\v2\x17.state.v1.TaskExecutionR\rtaskExecution\"z\n" +
	"\x19ListTaskExecutionsRequest\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vpage_offset\x18\x03 \x01(\x05R\n" +
	"pageOffset\"\x7f\n" +
	"\x1aListTaskExecutionsResponse\x12@\n" +
	"\x0ftask_executions\x18\x01 \x03(\v2\x17.state.v1.TaskExecutionR\x0etaskExecutions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\">\n" +
	"\x17ActivateScheduleRequest\x12#\n" +
	"\rschedule_name\x18\x01 \x01(\tR\fscheduleName\";\n" +
	"\x18ActivateScheduleResponse\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\"\x19\n" +
	"\x17ListAllSchedulesRequest\"\xc0\x02\n" +
	"\x0fScheduleSummary\x12#\n" +
	"\rschedule_name\x18\x01 \x01(\tR\fscheduleName\x12'\n" +
	"\x0fcron_expression\x18\x02 \x01(\tR\x0ecronExpression\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\btimezone\x18\x04 \x01(\tR\btimezone\x12\x1d\n" +
	"\n" +
	"is_running\x18\x05 \x01(\bR\tisRunning\x12:\n" +
	"\vlast_run_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tlastRunAt\x12&\n" +
	"\x0flast_run_status\x18\a \x01(\tR\rlastRunStatus\x12\x1e\n" +
	"\vlast_run_id\x18\b \x01(\tR\tlastRunId\"S\n" +
	"\x18ListAllSchedulesResponse\x127\n" +
	"\tschedules\x18\x01 \x03(\v2\x19.state.v1.ScheduleSummaryR\tschedules\"=\n" +
	"\x16TriggerScheduleRequest\x12#\n" +
	"\rschedule_name\x18\x01 \x01(\tR\fscheduleName\":\n" +
	"\x17TriggerScheduleResponse\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\"\x90\x01\n" +
	"\x15CancelScheduleRequest\x12#\n" +
	"\rschedule_name\x18\x01 \x01(\tR\fscheduleName\x12!\n" +
	"\fcancelled_by\x18\x02 \x01(\tR\vcancelledBy\x12/\n" +
	"\x13cancellation_reason\x18\x03 \x01(\tR\x12cancellationReason\"9\n" +
	"\x16CancelScheduleResponse\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\"+\n" +
	"\x10ResetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"@\n" +
	"\x1dGetSchedulerInitStatusRequest\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\"U\n" +
	"\x1eGetSchedulerInitStatusResponse\x123\n" +
	"\x15initialization_status\x18\x01 \x01(\tR\x14initializationStatus\"\x90\x01\n" +
	"\x13TriggerRerunRequest\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\x12\x16\n" +
	"\x06schema\x18\x02 \x01(\tR\x06schema\x12\x1d\n" +
	"\n" +
	"table_name\x18\x03 \x01(\tR\ttableName\x12!\n" +
	"\fservice_name\x18\x04 \x01(\tR\vserviceName\"\x16\n" +
	"\x14TriggerRerunResponse\"\xcd\x01\n" +
	"\x1bTriggerSingleNodeRunRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vschema_name\x18\x02 \x01(\tR\n" +
	"schemaName\x12\x1d\n" +
	"\n" +
	"table_name\x18\x03 \x01(\tR\ttableName\x12'\n" +
	"\x0fmetadata_source\x18\x04 \x01(\tR\x0emetadataSource\x12\"\n" +
	"\rsource_run_id\x18\x05 \x01(\tR\vsourceRunId\"Z\n" +
	"\x1cTriggerSingleNodeRunResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12#\n" +
	"\rschedule_name\x18\x02 \x01(\tR\fscheduleName\":\n" +
	"\x14TriggerRebaseRequest\x12\"\n" +
	"\rsource_run_id\x18\x01 \x01(\tR\vsourceRunId\"S\n" +
	"\x15TriggerRebaseResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12#\n" +
	"\rschedule_name\x18\x02 \x01(\tR\fscheduleName*\xcc\x01\n" +
	"\x0fSchedulerStatus\x12 \n" +
	"\x1cSCHEDULER_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18SCHEDULER_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18SCHEDULER_STATUS_RUNNING\x10\x02\x12\x1e\n" +
	"\x1aSCHEDULER_STATUS_SUCCEEDED\x10\x03\x12\x1b\n" +
	"\x17SCHEDULER_STATUS_FAILED\x10\x04\x12\x1e\n" +
	"\x1aSCHEDULER_STATUS_CANCELLED\x10\x05*\xa9\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TASK_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13TASK_STATUS_RUNNING\x10\x02\x12\x19\n" +
	"\x15TASK_STATUS_SUCCEEDED\x10\x03\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x04\x12\x19\n" +
	"\x15TASK_STATUS_CANCELLED\x10\x052\xbe\f\n" +
	"\fStateService\x12P\n" +
	"\x0fCreateScheduler\x12 .state.v1.CreateSchedulerRequest\x1a\x1b.state.v1.SchedulerResponse\x12J\n" +
	"\fGetScheduler\x12\x1d.state.v1.GetSchedulerRequest\x1a\x1b.state.v1.SchedulerResponse\x12P\n" +
	"\x0fCancelScheduler\x12 .state.v1.CancelSchedulerRequest\x1a\x1b.state.v1.SchedulerResponse\x12Y\n" +
	"\x10ActivateSchedule\x12!.state.v1.ActivateScheduleRequest\x1a\".state.v1.ActivateScheduleResponse\x12Y\n" +
	"\x10ListAllSchedules\x12!.state.v1.ListAllSchedulesRequest\x1a\".state.v1.ListAllSchedulesResponse\x12V\n" +
	"\x0fTriggerSchedule\x12 .state.v1.TriggerScheduleRequest\x1a!.state.v1.TriggerScheduleResponse\x12S\n" +
	"\x0eCancelSchedule\x12\x1f.state.v1.CancelScheduleRequest\x1a .state.v1.CancelScheduleResponse\x12A\n" +
	"\n" +
	"CreateTask\x12\x1b.state.v1.CreateTaskRequest\x1a\x16.state.v1.TaskResponse\x12;\n" +
	"\aGetTask\x12\x18.state.v1.GetTaskRequest\x1a\x16.state.v1.TaskResponse\x12]\n" +
	"\x18GetTaskByScheduleAndNode\x12).state.v1.GetTaskByScheduleAndNodeRequest\x1a\x16.state.v1.TaskResponse\x12G\n" +
	"\n" +
	"DeleteTask\x12\x1b.state.v1.DeleteTaskRequest\x1a\x1c.state.v1.DeleteTaskResponse\x12D\n" +
	"\tListTasks\x12\x1a.state.v1.ListTasksRequest\x1a\x1b.state.v1.ListTasksResponse\x12?\n" +
	"\tResetTask\x12\x1a.state.v1.ResetTaskRequest\x1a\x16.state.v1.TaskResponse\x12k\n" +
	"\x16GetSchedulerInitStatus\x12'.state.v1.GetSchedulerInitStatusRequest\x1a(.state.v1.GetSchedulerInitStatusResponse\x12M\n" +
	"\fTriggerRerun\x12\x1d.state.v1.TriggerRerunRequest\x1a\x1e.state.v1.TriggerRerunResponse\x12e\n" +
	"\x14TriggerSingleNodeRun\x12%.state.v1.TriggerSingleNodeRunRequest\x1a&.state.v1.TriggerSingleNodeRunResponse\x12P\n" +
	"\rTriggerRebase\x12\x1e.state.v1.TriggerRebaseRequest\x1a\x1f.state.v1.TriggerRebaseResponse\x12V\n" +
	"\x10GetTaskExecution\x12!.state.v1.GetTaskExecutionRequest\x1a\x1f.state.v1.TaskExecutionResponse\x12_\n" +
	"\x12ListTaskExecutions\x12#.state.v1.ListTaskExecutionsRequest\x1a$.state.v1.ListTaskExecutionsResponseB<Z:github.com/carolsimone/continuo/state/api/state/v1;statev1b\x06proto3"

var (
	file_proto_state_v1_state_proto_rawDescOnce sync.Once
	file_proto_state_v1_state_proto_rawDescData []byte
)

func file_proto_state_v1_state_proto_rawDescGZIP() []byte {
	file_proto_state_v1_state_proto_rawDescOnce.Do(func() {
		file_proto_state_v1_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_state_v1_state_proto_rawDesc), len(file_proto_state_v1_state_proto_rawDesc)))
	})
	return file_proto_state_v1_state_proto_rawDescData
}

var file_proto_state_v1_state_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_state_v1_state_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_proto_state_v1_state_proto_goTypes = []any{
	(SchedulerStatus)(0),                    // 0: state.v1.SchedulerStatus
	(TaskStatus)(0),                         // 1: state.v1.TaskStatus
	(*Scheduler)(nil),                       // 2: state.v1.Scheduler
	(*Task)(nil),                            // 3: state.v1.Task
	(*TaskExecution)(nil),                   // 4: state.v1.TaskExecution
	(*CreateSchedulerRequest)(nil),          // 5: state.v1.CreateSchedulerRequest
	(*GetSchedulerRequest)(nil),             // 6: state.v1.GetSchedulerRequest
	(*CancelSchedulerRequest)(nil),          // 7: state.v1.CancelSchedulerRequest
	(*SchedulerResponse)(nil),               // 8: state.v1.SchedulerResponse
	(*CreateTaskRequest)(nil),               // 9: state.v1.CreateTaskRequest
	(*GetTaskRequest)(nil),                  // 10: state.v1.GetTaskRequest
	(*GetTaskByScheduleAndNodeRequest)(nil), // 11: state.v1.GetTaskByScheduleAndNodeRequest
	(*DeleteTaskRequest)(nil),               // 12: state.v1.DeleteTaskRequest
	(*DeleteTaskResponse)(nil),              // 13: state.v1.DeleteTaskResponse
	(*ListTasksRequest)(nil),                // 14: state.v1.ListTasksRequest
	(*ListTasksResponse)(nil),               // 15: state.v1.ListTasksResponse
	(*TaskResponse)(nil),                    // 16: state.v1.TaskResponse
	(*GetTaskExecutionRequest)(nil),         // 17: state.v1.GetTaskExecutionRequest
	(*TaskExecutionResponse)(nil),           // 18: state.v1.TaskExecutionResponse
	(*ListTaskExecutionsRequest)(nil),       // 19: state.v1.ListTaskExecutionsRequest
	(*ListTaskExecutionsResponse)(nil),      // 20: state.v1.ListTaskExecutionsResponse
	(*ActivateScheduleRequest)(nil),         // 21: state.v1.ActivateScheduleRequest
	(*ActivateScheduleResponse)(nil),        // 22: state.v1.ActivateScheduleResponse
	(*ListAllSchedulesRequest)(nil),         // 23: state.v1.ListAllSchedulesRequest
	(*ScheduleSummary)(nil),                 // 24: state.v1.ScheduleSummary
	(*ListAllSchedulesResponse)(nil),        // 25: state.v1.ListAllSchedulesResponse
	(*TriggerScheduleRequest)(nil),          // 26: state.v1.TriggerScheduleRequest
	(*TriggerScheduleResponse)(nil),         // 27: state.v1.TriggerScheduleResponse
	(*CancelScheduleRequest)(nil),           // 28: state.v1.CancelScheduleRequest
	(*CancelScheduleResponse)(nil),          // 29: state.v1.CancelScheduleResponse
	(*ResetTaskRequest)(nil),                // 30: state.v1.ResetTaskRequest
	(*GetSchedulerInitStatusRequest)(nil),   // 31: state.v1.GetSchedulerInitStatusRequest
	(*GetSchedulerInitStatusResponse)(nil),  // 32: state.v1.GetSchedulerInitStatusResponse
	(*TriggerRerunRequest)(nil),             // 33: state.v1.TriggerRerunRequest
	(*TriggerRerunResponse)(nil),            // 34: state.v1.TriggerRerunResponse
	(*TriggerSingleNodeRunRequest)(nil),     // 35: state.v1.TriggerSingleNodeRunRequest
	(*TriggerSingleNodeRunResponse)(nil),    // 36: state.v1.TriggerSingleNodeRunResponse
	(*TriggerRebaseRequest)(nil),            // 37: state.v1.TriggerRebaseRequest
	(*TriggerRebaseResponse)(nil),           // 38: state.v1.TriggerRebaseResponse
	(*timestamppb.Timestamp)(nil),           // 39: google.protobuf.Timestamp
}
var file_proto_state_v1_state_proto_depIdxs = []int32{
	0,  // 0: state.v1.Scheduler.status:type_name -> state.v1.SchedulerStatus
	39, // 1: state.v1.Scheduler.created_at:type_name -> google.protobuf.Timestamp
	39, // 2: state.v1.Scheduler.started_at:type_name -> google.protobuf.Timestamp
	39, // 3: state.v1.Scheduler.completed_at:type_name -> google.protobuf.Timestamp
	39, // 4: state.v1.Scheduler.last_heartbeat_at:type_name -> google.protobuf.Timestamp
	39, // 5: state.v1.Scheduler.cancelled_at:type_name -> google.protobuf.Timestamp
	39, // 6: state.v1.Task.created_at:type_name -> google.protobuf.Timestamp
	1,  // 7: state.v1.Task.status:type_name -> state.v1.TaskStatus
	39, // 8: state.v1.Task.cancelled_at:type_name -> google.protobuf.Timestamp
	39, // 9: state.v1.TaskExecution.created_at:type_name -> google.protobuf.Timestamp
	39, // 10: state.v1.TaskExecution.started_at:type_name -> google.protobuf.Timestamp
	39, // 11: state.v1.TaskExecution.completed_at:type_name -> google.protobuf.Timestamp
	39, // 12: state.v1.TaskExecution.cancelled_at:type_name -> google.protobuf.Timestamp
	0,  // 13: state.v1.CreateSchedulerRequest.status:type_name -> state.v1.SchedulerStatus
	2,  // 14: state.v1.SchedulerResponse.scheduler:type_name -> state.v1.Scheduler
	1,  // 15: state.v1.CreateTaskRequest.status:type_name -> state.v1.TaskStatus
	1,  // 16: state.v1.ListTasksRequest.status:type_name -> state.v1.TaskStatus
	3,  // 17: state.v1.ListTasksResponse.tasks:type_name -> state.v1.Task
	3,  // 18: state.v1.TaskResponse.task:type_name -> state.v1.Task
	4,  // 19: state.v1.TaskExecutionResponse.task_execution:type_name -> state.v1.TaskExecution
	4,  // 20: state.v1.ListTaskExecutionsResponse.task_executions:type_name -> state.v1.TaskExecution
	39, // 21: state.v1.ScheduleSummary.last_run_at:type_name -> google.protobuf.Timestamp
	24, // 22: state.v1.ListAllSchedulesResponse.schedules:type_name -> state.v1.ScheduleSummary
	5,  // 23: state.v1.StateService.CreateScheduler:input_type -> state.v1.CreateSchedulerRequest
	6,  // 24: state.v1.StateService.GetScheduler:input_type -> state.v1.GetSchedulerRequest
	7,  // 25: state.v1.StateService.CancelScheduler:input_type -> state.v1.CancelSchedulerRequest
	21, // 26: state.v1.StateService.ActivateSchedule:input_type -> state.v1.ActivateScheduleRequest
	23, // 27: state.v1.StateService.ListAllSchedules:input_type -> state.v1.ListAllSchedulesRequest
	26, // 28: state.v1.StateService.TriggerSchedule:input_type -> state.v1.TriggerScheduleRequest
	28, // 29: state.v1.StateService.CancelSchedule:input_type -> state.v1.CancelScheduleRequest
	9,  // 30: state.v1.StateService.CreateTask:input_type -> state.v1.CreateTaskRequest
	10, // 31: state.v1.StateService.GetTask:input_type -> state.v1.GetTaskRequest
	11, // 32: state.v1.StateService.GetTaskByScheduleAndNode:input_type -> state.v1.GetTaskByScheduleAndNodeRequest
	12, // 33: state.v1.StateService.DeleteTask:input_type -> state.v1.DeleteTaskRequest
	14, // 34: state.v1.StateService.ListTasks:input_type -> state.v1.ListTasksRequest
	30, // 35: state.v1.StateService.ResetTask:input_type -> state.v1.ResetTaskRequest
	31, // 36: state.v1.StateService.GetSchedulerInitStatus:input_type -> state.v1.GetSchedulerInitStatusRequest
	33, // 37: state.v1.StateService.TriggerRerun:input_type -> state.v1.TriggerRerunRequest
	35, // 38: state.v1.StateService.TriggerSingleNodeRun:input_type -> state.v1.TriggerSingleNodeRunRequest
	37, // 39: state.v1.StateService.TriggerRebase:input_type -> state.v1.TriggerRebaseRequest
	17, // 40: state.v1.StateService.GetTaskExecution:input_type -> state.v1.GetTaskExecutionRequest
	19, // 41: state.v1.StateService.ListTaskExecutions:input_type -> state.v1.ListTaskExecutionsRequest
	8,  // 42: state.v1.StateService.CreateScheduler:output_type -> state.v1.SchedulerResponse
	8,  // 43: state.v1.StateService.GetScheduler:output_type -> state.v1.SchedulerResponse
	8,  // 44: state.v1.StateService.CancelScheduler:output_type -> state.v1.SchedulerResponse
	22, // 45: state.v1.StateService.ActivateSchedule:output_type -> state.v1.ActivateScheduleResponse
	25, // 46: state.v1.StateService.ListAllSchedules:output_type -> state.v1.ListAllSchedulesResponse
	27, // 47: state.v1.StateService.TriggerSchedule:output_type -> state.v1.TriggerScheduleResponse
	29, // 48: state.v1.StateService.CancelSchedule:output_type -> state.v1.CancelScheduleResponse
	16, // 49: state.v1.StateService.CreateTask:output_type -> state.v1.TaskResponse
	16, // 50: state.v1.StateService.GetTask:output_type -> state.v1.TaskResponse
	16, // 51: state.v1.StateService.GetTaskByScheduleAndNode:output_type -> state.v1.TaskResponse
	13, // 52: state.v1.StateService.DeleteTask:output_type -> state.v1.DeleteTaskResponse
	15, // 53: state.v1.StateService.ListTasks:output_type -> state.v1.ListTasksResponse
	16, // 54: state.v1.StateService.ResetTask:output_type -> state.v1.TaskResponse
	32, // 55: state.v1.StateService.GetSchedulerInitStatus:output_type -> state.v1.GetSchedulerInitStatusResponse
	34, // 56: state.v1.StateService.TriggerRerun:output_type -> state.v1.TriggerRerunResponse
	36, // 57: state.v1.StateService.TriggerSingleNodeRun:output_type -> state.v1.TriggerSingleNodeRunResponse
	38, // 58: state.v1.StateService.TriggerRebase:output_type -> state.v1.TriggerRebaseResponse
	18, // 59: state.v1.StateService.GetTaskExecution:output_type -> state.v1.TaskExecutionResponse
	20, // 60: state.v1.StateService.ListTaskExecutions:output_type -> state.v1.ListTaskExecutionsResponse
	42, // [42:61] is the sub-list for method output_type
	23, // [23:42] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_proto_state_v1_state_proto_init() }
func file_proto_state_v1_state_proto_init() {
	if File_proto_state_v1_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_state_v1_state_proto_rawDesc), len(file_proto_state_v1_state_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_state_v1_state_proto_goTypes,
		DependencyIndexes: file_proto_state_v1_state_proto_depIdxs,
		EnumInfos:         file_proto_state_v1_state_proto_enumTypes,
		MessageInfos:      file_proto_state_v1_state_proto_msgTypes,
	}.Build()
	File_proto_state_v1_state_proto = out.File
	file_proto_state_v1_state_proto_goTypes = nil
	file_proto_state_v1_state_proto_depIdxs = nil
}
