{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "continuo.postgresql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "continuo.labels" . | nindent 4 }}
    app.kubernetes.io/name: postgresql
type: Opaque
stringData:
  password: {{ include "continuo.generatedSecret" (dict "root" $ "secretName" (include "continuo.postgresql.fullname" .) "key" "password") | quote }}
{{- end }}
