{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "continuo.postgresql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "continuo.labels" . | nindent 4 }}
    app.kubernetes.io/name: postgresql
spec:
  clusterIP: None
  selector:
    {{- include "continuo.selectorLabels" (dict "root" $ "service" "postgresql") | nindent 4 }}
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
{{- end }}
