{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "continuo.redis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "continuo.labels" . | nindent 4 }}
    app.kubernetes.io/name: redis
spec:
  clusterIP: None
  selector:
    {{- include "continuo.selectorLabels" (dict "root" $ "service" "redis") | nindent 4 }}
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
{{- end }}
