#!/usr/bin/env bash
# Creates the developer-local .env that docker compose reads, if it is missing.
#
# Only one variable needs generating rather than defaulting. ui builds its
# Create-PR client with octokit's createAppAuth, whose constructor rejects a
# private key that is not a syntactically valid PEM. An empty or fake string
# therefore leaves prCreator undefined and the Create-PR route reports itself as
# unconfigured, so the flow cannot be exercised against the local GitHub stub.
#
# The generated key authenticates nothing: local runs point GITHUB_API_BASE_URL at
# the stub, not github.com. Generating it per developer keeps key material out of
# the repository entirely, which matters because a committed PEM trips every
# secret scanner and reads as a real leak to anyone auditing a public repo.
#
# Safe to run repeatedly: an existing .env is never modified.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

if [ -f .env ]; then
  if grep -q '^GITHUB_APP_PRIVATE_KEY=' .env; then
    exit 0
  fi
  echo "Appending GITHUB_APP_PRIVATE_KEY to existing .env..."
else
  echo "Creating .env for local development..."
  cat > .env <<'EOF'
# Developer-local environment for docker compose. Generated by
# scripts/ensure-dev-env.sh and ignored by git — never commit this file.
EOF
fi

tmp_key="$(mktemp)"
trap 'rm -f "${tmp_key}"' EXIT

openssl genrsa -out "${tmp_key}" 2048 2>/dev/null

# ui reads this as a single-line value and expands the escapes itself
# (index.ts: .replace(/\\n/g, '\n')), so collapse the PEM to one line to match.
key_one_line="$(awk '{printf "%s\\n", $0}' "${tmp_key}")"

{
  echo ""
  echo "# Throwaway RSA key so ui can construct its GitHub App client"
  echo "# against the local stub. Authenticates nothing; regenerate freely."
  echo "GITHUB_APP_PRIVATE_KEY=${key_one_line}"
} >> .env

echo "✓ Generated a throwaway GitHub App key into .env"
