package model

import (
	"time"

	"github.com/google/uuid"
)

type OutboxStatus string

const (
	OutboxStatusPending   OutboxStatus = "pending"
	OutboxStatusProcessed OutboxStatus = "processed"
	OutboxStatusFailed    OutboxStatus = "failed"
)

type K8sStatusOutboxEntry struct {
	ID uuid.UUID `db:"id"`

	// Event identification
	EventType  string `db:"event_type"`  // 'task_succeeded', 'task_failed', 'task_retry', 'check_delayed'
	StreamName string `db:"stream_name"` // 'retry.task:v1', 'task.failed:v1', 'check.k8s:v1'

	// Task context
	TaskID       uuid.UUID `db:"task_id"`
	ScheduleID   uuid.UUID `db:"schedule_id"`
	ScheduleName string    `db:"schedule_name"`
	ServiceName  string    `db:"service_name"`
	SchemaName   string    `db:"schema_name"`
	TableName    string    `db:"table_name"`
	JobName      string    `db:"job_name"`
	NodeType     string    `db:"node_type"`

	// Event-specific data
	ErrorMessage   string `db:"error_message"`
	TaskRetryCount int    `db:"task_retry_count"`
	CheckAfter     int64  `db:"check_after"` // Unix timestamp

	// State update flags
	UpdateTaskStatus     bool       `db:"update_task_status"`
	NewTaskStatus        string     `db:"new_task_status"`
	NewRetryCount        int        `db:"new_retry_count"`
	CreateExecution      bool       `db:"create_execution"`
	ExecutionStartedAt   *time.Time `db:"execution_started_at"`
	ExecutionCompletedAt *time.Time `db:"execution_completed_at"`
	ExecutionSeconds     float64    `db:"execution_seconds"`

	// Execution identity (pre-generated by k8s-controller for S3 linking)
	ExecutionID uuid.UUID `db:"execution_id"`
	LogS3Key    string    `db:"log_s3_key"`

	// Outbox status
	Status             OutboxStatus `db:"status"`
	CreatedAt          time.Time    `db:"created_at"`
	ProcessedAt        *time.Time   `db:"processed_at"`
	OutboxRetryCount   int          `db:"outbox_retry_count"`
	MaxRetries         int          `db:"max_retries"`
	OutboxErrorMessage string       `db:"outbox_error_message"`
}
