# Code generated by gen-streams. DO NOT EDIT.
# Source: pkg/streams/contract.yaml
#
# Each enum here is a closed value set two or more services agree on. They are
# domain vocabulary, not transport: stream and consumer-group names live in
# streams_contract, which no module under domain/ imports.

from enum import StrEnum


class ParseFailureKind(StrEnum):
    """Why topology-controller could not resolve a candidate release. Declaration order is precedence."""
    INVALID_SQL = "invalid_sql"
    UNQUALIFIED_REFERENCE = "unqualified_reference"
    INVALID_ARTIFACT = "invalid_artifact"
    INTERNAL = "internal"


PARSE_FAILURE_KIND_HEALABLE = frozenset({ParseFailureKind.INVALID_SQL, ParseFailureKind.UNQUALIFIED_REFERENCE})
"""Values of ParseFailureKind a remediation attempt can fix by changing the user's source."""
