name: service_3
version: '1.0.0'
config-version: 2
profile: default

model-paths: ["models"]

models:
  service_3:
    +materialized: table
    +meta:
      owner: "test"
      criticality: "CORE"
    table_d:
      +tags: ["daily"]
    table_e:
      +tags: ["daily"]
    table_f:
      +tags: ["daily"]
    table_i:
      +tags: ["daily"]
    table_j:
      +tags: ["daily"]
    ftable_c:
      +tags: ["e2e-schedule-failure"]
    ftable_f:
      +tags: ["e2e-schedule-failure"]
    ftable_g:
      +tags: ["e2e-schedule-failure"]
    xprobe_up:
      +tags: ["xprobe"]
