{{- if and .Values.minio.enabled (not .Values.minio.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "continuo.minio.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "continuo.labels" . | nindent 4 }}
    app.kubernetes.io/name: minio
type: Opaque
stringData:
  access-key-id: "continuo"
  secret-access-key: {{ include "continuo.generatedSecret" (dict "root" $ "secretName" (include "continuo.minio.fullname" .) "key" "secret-access-key") | quote }}
{{- end }}
